abbr -a l "eza -alg --icons --color=never"
abbr -a c "eza -algs created --icons --color=never"
abbr -a d "eza -alg --icons --color=never -d */"
abbr -a ld "du -hs */"
# clear cache
abbr -a clear_cache "sync; echo 1 > /proc/sys/vm/drop_caches"
abbr -a rb "sudo reboot"
abbr -a lblk "lsblk -o +fstype,label,uuid,partuuid"
abbr -a umo "sudo umount"
abbr -a mo "sudo mount"
abbr -a v "vim"
abbr -a x "exit"
alias f="firefox-bin -p mio  &"
abbr -a xc "xclip -selection clipboard"
abbr -a b "bat"
abbr -a sm "eza -alg --icons --color=never -smodified -L1 -r *.mp*"
abbr -a ss "eza -alg --icons --color=never -ssize -L1 -r *.mp*"
abbr -a wpli "/home/ossi/git/ho-updates/wplocalinstall.sh -sa ga -c"
