declare let errorOccurred: boolean;
declare const useFlexDisplayElements: string[];
declare const betaExtId: "pljaalgmajnlogcgiohkhdmgpomjcihk";
declare function processError(err: any, stack: any, message: any): void;
declare let pageInfo: any;
declare const popupMenuCtaClosedKey: "popup_menu_cta_closed";
declare const showPopupMenuThemesCtaKey: "popup_menu_themes_cta";
declare const popupMenuFreeDCCtaClosedKey: "popup_menu_free_dc_cta_closed";
declare const popupMenuDCCtaClosedKey: "popup_menu_dc_cta_closed";
declare const popupMenuVPNCtaClosedKey: "popup_menu_vpn_cta_closed";
declare const shown: {};
declare const themeCTA: "";
declare let itemClicked: boolean;
declare function sendMessageWithNoResponse(message: any): void;
declare function show(elementIds: any): void;
declare function hide(elementIds: any): void;
declare function closePopup(): void;
declare function shouldShowCTAOnSite(): boolean;
declare function checkAndEnableHelp(): void;
declare function getNewBadgeText(): string;
declare function start(): Promise<void>;
