// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.cache.enabled", true);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "ab2471d7-4193-44cf-bb7e-236b60f6ee26");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1679239833);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1679239804);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1679239862);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{ae195bfb-552b-46b7-ba8a-cd6a76160872}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1679239802);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"159647\":1679239849534,\"349790427\":1679239849537}");
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"332152893\":[1679239849536]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{07c35d9b-dde7-4b0a-bcc4-5d257271f69a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1679239804);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1679239827474");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1679241603474");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1679239805910");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1679261405910");
user_pref("browser.search.region", "DE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1679239803");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230309232128");
user_pref("browser.startup.homepage_override.mstone", "111.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_9\",\"url\":\"https://www.mozilla.org/firefox/welcome/9\",\"expire\":1638144000000}");
user_pref("browser.startup.lastColdStartupCheck", 1679239803);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1679239803718");
user_pref("distribution.iniFile.exists.appversion", "111.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "63b516881faf459e9038ea9c745e0a69");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1679239803);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-de@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230309232128");
user_pref("extensions.lastAppVersion", "111.0");
user_pref("extensions.lastPlatformVersion", "111.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"76724964-ee20-4fab-aa0f-6b7d5a84c7ea\",\"pictureinpicture@mozilla.org\":\"1d946e95-252c-430a-aefa-7c617bf97086\",\"screenshots@mozilla.org\":\"6ccbac18-6898-4190-9244-b427913ec1df\",\"webcompat-reporter@mozilla.org\":\"faf0825f-8a39-4d7f-b55c-1b377eba8b0f\",\"webcompat@mozilla.org\":\"5addf1c3-48c5-45af-a389-7b98becd2f0d\",\"default-theme@mozilla.org\":\"9e035a8d-bff5-4b4c-b847-c1346a9c8a78\",\"addons-search-detection@mozilla.com\":\"4d7b4e62-82d8-4dfb-9d6d-8846a701b55b\",\"google@search.mozilla.org\":\"33826a8c-e186-46a4-a943-bc7b9bc77f2f\",\"leo_ende_de@search.mozilla.org\":\"e785fc10-2eaa-428a-8c0b-4c29b804dc9c\",\"ecosia@search.mozilla.org\":\"50f0f73a-2a98-44aa-9667-6f73eba9030e\",\"wikipedia@search.mozilla.org\":\"694aea9c-6a5d-409b-9f87-a746361310e2\",\"bing@search.mozilla.org\":\"51c4e5e8-ca6e-49ae-80ae-a0231bc635fb\",\"ddg@search.mozilla.org\":\"6965edff-81f1-40b7-9689-79320585e839\",\"ebay@search.mozilla.org\":\"66f5009b-94a4-4b08-af31-2330d6d4a379\",\"amazon@search.mozilla.org\":\"9c55dc1e-0053-4919-9a84-a8c0575ed8cd\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.accessibilityCache", "{\"slug\":\"next-generation-accessibility-engine-powering-screen-readers-and-other-ats-copy\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"accessibilityCache\"},\"features\":null},\"active\":true,\"enrollmentId\":\"d4665448-8559-495d-8588-26e065e6c3c7\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"A next generation accessibility engine powering screen readers and other ATs\",\"userFacingDescription\":\"Evaluating a major re-architecture of Firefox's accessibility engine to improve performance of screen readers and other assistive technologies.\",\"lastSeen\":\"2023-03-19T15:30:03.906Z\",\"featureIds\":[\"accessibilityCache\"],\"prefs\":[{\"name\":\"accessibility.cache.enabled\",\"branch\":\"user\",\"featureId\":\"accessibilityCache\",\"variable\":\"enabled\",\"originalValue\":null}],\"isRollout\":false}");
user_pref("nimbus.syncdatastore.accessibilityCache.enabled", true);
user_pref("nimbus.syncdatastore.fxaButtonVisibility", "{\"slug\":\"firefox-accounts-toolbar-button-default-visibility-new-users\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"fxaButtonVisibility\"},\"features\":null},\"active\":true,\"enrollmentId\":\"8b4675d7-0662-4df9-b63e-3e0164fa0cf5\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"Firefox Accounts toolbar button default visibility - new users\",\"userFacingDescription\":\"This experiment measures the impact of showing the Firefox Accounts toolbar button by default for signed-out users.\",\"lastSeen\":\"2023-03-19T15:30:03.888Z\",\"featureIds\":[\"fxaButtonVisibility\"],\"prefs\":[{\"name\":\"identity.fxaccounts.toolbar.defaultVisible\",\"branch\":\"user\",\"featureId\":\"fxaButtonVisibility\",\"variable\":\"boolean\",\"originalValue\":null}],\"isRollout\":false}");
user_pref("nimbus.syncdatastore.fxaButtonVisibility.boolean", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d8323d4c-54ac-4097-bfd0-ff82abdea780");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1679239801);
user_pref("toolkit.telemetry.cachedClientID", "d5d57acb-a1b0-4766-8e14-fa324cc20fdb");
user_pref("toolkit.telemetry.previousBuildID", "20230309232128");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
