# 6tunnel
# Autogenerated from man page /usr/share/man/man1/6tunnel.1.bz2
complete -c 6tunnel -s 1 -d 'Exit after first connection'
complete -c 6tunnel -s 4 -d 'Prefer IPv4 endpoint if the machine has both address types'
complete -c 6tunnel -s 6 -d 'Listen on IPv6 address (IPv4 is default)'
complete -c 6tunnel -s d -d 'Don\'t detach'
complete -c 6tunnel -s f -d 'Force tunneling even if remote host is not resolvable at the execution time'
complete -c 6tunnel -s h -d 'Print hex dump of every packet received or sent'
complete -c 6tunnel -s u -d 'Change UID and GID after bind()'
complete -c 6tunnel -s i -d 'Act as an IRC proxy and require user to authenticate'
complete -c 6tunnel -s I -d 'If you are using  6tunnel as an IRC proxy and the IRC server requires you to …'
complete -c 6tunnel -s l -d 'Listen on specified address (IPv4, or IPv6 if  -6 used)'
complete -c 6tunnel -s L -d 'Limit simultaneous connections'
complete -c 6tunnel -s p -d 'Write down pid to specified file'
complete -c 6tunnel -s s -d 'Connect to the remote host using specified source address'
complete -c 6tunnel -s m -d 'Binds to specified IPv6 addresses on basis of source IPv4 address'
complete -c 6tunnel -s v -d 'Be verbose and don\'t detach.  NOTES Option'
complete -c 6tunnel -s H -d 'to disable all resolver hints has been removed since proper combination of '

