# abiword
# Autogenerated from man page /usr/share/man/man1/abiword.1.bz2
complete -c abiword -s g -l geometry -d 'Specifies window geometry at startup'
complete -c abiword -s E -l plugin -d 'Execute the specified plugin instead of the main application'
complete -c abiword -l import-extension -d 'Import the given file as if it had extension EXT, overriding automatic file t…'
complete -c abiword -s u -l userprofile -d 'Use PROFILE to read and store settings instead of the default   XDG_CONFIG_HO…'
complete -c abiword -s t -l to -d 'Convert the given file to another format, writing the result to R DEST '
complete -c abiword -l to-name -d 'Only useful in conjunction with  --to= FORMAT '
complete -c abiword -l verbose -d 'Set level of verbosity [0-2], 2 giving the most detailed output'
complete -c abiword -s h -l help -d 'Display a short help message and exit'
complete -c abiword -l version -d 'Report the version of AbiWord'

