# argon2
# Autogenerated from man page /usr/share/man/man1/argon2.1.bz2
complete -c argon2 -s h -d 'Display tool usage'
complete -c argon2 -s d -d 'Use Argon2d instead of Argon2i (Argon2i is the default)'
complete -c argon2 -o id -d 'Use Argon2id instead of Argon2i (Argon2i is the default)'
complete -c argon2 -s t -d 'Sets the number of iterations to N (default = 3)'
complete -c argon2 -s m -d 'Sets the memory usage of 2^N KiB (default = 12)'
complete -c argon2 -s p -d 'Sets parallelism to N threads (default = 1)'
complete -c argon2 -s l -d 'Sets hash output length to N bytes (default = 32)'
complete -c argon2 -s e -d 'Output only encoded hash'
complete -c argon2 -s r -d 'Output only the raw bytes of the hash'
complete -c argon2 -s v -d 'Argon2 version (defaults to the most recent version, currently 13)'

