# aria_s3_copy
# Autogenerated from man page /usr/share/man/man1/aria_s3_copy.1.bz2
complete -c aria_s3_copy -s '?' -s h -l help -d 'Display help and exit'
complete -c aria_s3_copy -s k -l s3-access-key -d 'AWS access key ID'
complete -c aria_s3_copy -s r -o s3-region -d 'AWS region'
complete -c aria_s3_copy -s K -o s3-secret-key -d 'AWS secret access key ID'
complete -c aria_s3_copy -s b -o s3-bucket -d 'AWS prefix for tables'
complete -c aria_s3_copy -o s3-host-name -d 'Host name to S3 provider'
complete -c aria_s3_copy -s c -o compress -d 'Use compression'
complete -c aria_s3_copy -s o -o op -d 'Operation to execute.  One of \'from_s3\', \'to_s3\' or \'delete_from_s3\''
complete -c aria_s3_copy -s d -o database -d 'Database for copied table (second prefix)'
complete -c aria_s3_copy -s B -o s3-block-size -d 'Block size for data/index blocks in s3'
complete -c aria_s3_copy -s L -o s3-protocol-version -d 'Protocol used to communication with S3'
complete -c aria_s3_copy -s f -o force -d 'Force copy even if target exists'
complete -c aria_s3_copy -s V -o version -d 'Print version and exit'
complete -c aria_s3_copy -l s3-debug -d 'Output debug log from marias3 to stdout'
complete -c aria_s3_copy -s v -l verbose -d 'Be verbose'

