# asciidoc
# Autogenerated from man page /usr/share/man/man1/asciidoc.1.bz2
complete -c asciidoc -s a -l attribute -d 'Define or delete document attribute.  ATTRIBUTE is formatted like NAME=VALUE'
complete -c asciidoc -s b -l backend -d 'Backend output file format: docbook45, docbook5, xhtml11, html4, html5, slidy…'
complete -c asciidoc -s f -l conf-file -d 'Use configuration file CONF_FILE'
complete -c asciidoc -l doctest -d 'Run Python doctests in asciidoc module'
complete -c asciidoc -s d -l doctype -d 'Document type: article, manpage or book'
complete -c asciidoc -s c -l dump-conf -d 'Dump configuration to stdout'
complete -c asciidoc -l filter -d 'Specify the name of a filter to be loaded (used to load filters that are not …'
complete -c asciidoc -s h -l help -d 'Print help TOPIC'
complete -c asciidoc -s e -l no-conf -d 'Exclude implicitly loaded configuration files except for those named like the…'
complete -c asciidoc -s s -l no-header-footer -d 'Suppress document header and footer output'
complete -c asciidoc -s o -l out-file -d 'Write output to file OUT_FILE'
complete -c asciidoc -s n -l section-numbers -d 'Auto-number HTML article section titles.  Synonym for --attribute numbered'
complete -c asciidoc -l safe -d 'Enable safe mode.  Safe mode is disabled by default'
complete -c asciidoc -l theme -d 'Specify a theme name.  Synonym for --attribute theme=THEME'
complete -c asciidoc -s v -l verbose -d 'Verbosely print processing information and configuration file checks to stderr'
complete -c asciidoc -l version -d 'Print program version number'

