# autoconf-2
# Autogenerated from man page /usr/share/man/man1/autoconf-2.71.1.bz2
complete -c autoconf-2 -s h -l help -d 'print this help, then exit'
complete -c autoconf-2 -s V -l version -d 'print version number, then exit'
complete -c autoconf-2 -s v -l verbose -d 'verbosely report processing'
complete -c autoconf-2 -s d -l debug -d 'don\'t remove temporary files'
complete -c autoconf-2 -s f -l force -d 'consider all files obsolete'
complete -c autoconf-2 -s o -l output -d 'save output in FILE (stdout is the default)'
complete -c autoconf-2 -s W -l warnings -d 'report the warnings falling in CATEGORY . SS "Warning categories include:"'
complete -c autoconf-2 -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c autoconf-2 -s I -l include -d 'append directory DIR to search path . SS "Tracing:"'
complete -c autoconf-2 -s t -l trace -d 'report the list of calls to MACRO'
complete -c autoconf-2 -s i -l initialization -d 'also trace Autoconf\'s initialization process'

