# autoheader-2
# Autogenerated from man page /usr/share/man/man1/autoheader-2.71.1.bz2
complete -c autoheader-2 -s h -l help -d 'print this help, then exit'
complete -c autoheader-2 -s V -l version -d 'print version number, then exit'
complete -c autoheader-2 -s v -l verbose -d 'verbosely report processing'
complete -c autoheader-2 -s d -l debug -d 'don\'t remove temporary files'
complete -c autoheader-2 -s f -l force -d 'consider all files obsolete'
complete -c autoheader-2 -s W -l warnings -d 'report the warnings falling in CATEGORY . SS "Warning categories include:"'
complete -c autoheader-2 -s B -l prepend-include -d 'prepend directory DIR to search path'
complete -c autoheader-2 -s I -l include -d 'append directory DIR to search path AUTHOR Written by Roland McGrath and Akim…'

