# bbe
# Autogenerated from man page /usr/share/man/man1/bbe.1.bz2
complete -c bbe -s b -l block -d 'Block definition'
complete -c bbe -s e -l expression -d 'Add the COMMAND to the commands to be executed'
complete -c bbe -s f -l file -d 'Add the contest of script-file to commands'
complete -c bbe -s o -l output -d 'Write output to name instead of standard output'
complete -c bbe -s s -l suppress -d 'Suppress normal output, print only block contents'
complete -c bbe -s '?' -l help -d 'List all available options and their meanings'
complete -c bbe -s V -l version -d 'Show version of program. PP  BLOCK can be defined as:'

