# bcron-update
# Autogenerated from man page /usr/share/man/man8/bcron-update.8.bz2
complete -c bcron-update -o '/etc/cron.d/oldfile' -d 'The named file no longer exists and will be removed from the spool'

