# bcrontab
# Autogenerated from man page /usr/share/man/man1/bcrontab.1.bz2
complete -c bcrontab -s u -d 'Tell  bcron-spool that we are acting on behalf of the named user'
complete -c bcrontab -s l -d 'List the cronab crontab to standard output'
complete -c bcrontab -s r -d 'Remove the user\'s crontab'
complete -c bcrontab -s e -d 'Edit the current crontab.  ENVIRONMENT'

