# bg-installer
# Autogenerated from man page /usr/share/man/man1/bg-installer.1.bz2
complete -c bg-installer -s v -l verbose -d 'List the files as they are processed'
complete -c bg-installer -s n -l dry-run -d 'Don\'t modify any files, just display'
complete -c bg-installer -s c -l check -d 'Check destinations instead of installing'
complete -c bg-installer -s h -l help -d 'Display usage information and exit'

