# binutils-config
# Autogenerated from man page /usr/share/man/man8/binutils-config.8.bz2
complete -c binutils-config -l list-profiles -d 'working with cross-compilers), just a TARGET where the VERSION is picked from…'
complete -c binutils-config -s c -l get-current-profile -d 'Display the active profile for TARGET'
complete -c binutils-config -s l -d 'Show all the profiles that your system currently has installed and what versi…'
complete -c binutils-config -s u -l uninstall -d 'This is really for internal use only'

