# bootlogd
# Autogenerated from man page /usr/share/man/man8/bootlogd.8.bz2
complete -c bootlogd -s d -d 'Do not fork and run in the background'
complete -c bootlogd -s e -d 'Print escape characters to the boot log file'
complete -c bootlogd -s c -d 'Attempt to write to the logfile even if it does not yet exist'
complete -c bootlogd -s r -d 'If there is an existing logfile called logfile rename it to logfile~ unless l…'
complete -c bootlogd -s s -d 'Ensure that the data is written to the file after each line by calling  fdata…'
complete -c bootlogd -s v -d 'Show version'
complete -c bootlogd -s l -d 'Log to this logfile.  The default is /var/log/boot'
complete -c bootlogd -s p -d 'Put process-id in this file.  The default is no pidfile'

