# btrfs-select-super
# Autogenerated from man page /usr/share/man/man8/btrfs-select-super.8.bz2
complete -c btrfs-select-super -s s -l super -d 'use \\*(Aqsuperblock\'th superblock copy, valid values are 0 1 or 2 if the resp…'

