# bundle-add26
# Autogenerated from man page /usr/share/man/man1/bundle-add26.1.bz2
complete -c bundle-add26 -l version -s v -d 'Specify version requirements(s) for the added gem'
complete -c bundle-add26 -l group -s g -d 'Specify the group(s) for the added gem'
complete -c bundle-add26 -l source -s s -d 'Specify the source for the added gem'
complete -c bundle-add26 -l skip-install -d 'Adds the gem to the Gemfile but does not install it'
complete -c bundle-add26 -l optimistic -d 'Adds optimistic declaration of version '

