# bundle-list26
# Autogenerated from man page /usr/share/man/man1/bundle-list26.1.bz2
complete -c bundle-list26 -l name-only -d 'Print only the name of each gem'
complete -c bundle-list26 -l paths -d 'Print the path to each gem in the bundle'
complete -c bundle-list26 -l without-group -d 'Print all gems expect from a group'

