# bundle-check27
# Autogenerated from man page /usr/share/man/man1/bundle-check27.1.bz2
complete -c bundle-check27 -l dry-run -d 'Locks the [Gemfile(5)][Gemfile(5)] before running the command'
complete -c bundle-check27 -l gemfile -d 'Use the specified gemfile instead of the [Gemfile(5)][Gemfile(5)]'

