# bundle26
# Autogenerated from man page /usr/share/man/man1/bundle26.1.bz2
complete -c bundle26 -l no-color -d 'Print all output without color '
complete -c bundle26 -l retry -s r -d 'Specify the number of times you wish to attempt network commands '

