# bundle-list27
# Autogenerated from man page /usr/share/man/man1/bundle-list27.1.bz2
complete -c bundle-list27 -l name-only -d 'Print only the name of each gem'
complete -c bundle-list27 -l paths -d 'Print the path to each gem in the bundle'
complete -c bundle-list27 -l without-group -d 'Print all gems expect from a group'

