# bundle-check26
# Autogenerated from man page /usr/share/man/man1/bundle-check26.1.bz2
complete -c bundle-check26 -l dry-run -d 'Locks the [Gemfile(5)][Gemfile(5)] before running the command'
complete -c bundle-check26 -l gemfile -d 'Use the specified gemfile instead of the [Gemfile(5)][Gemfile(5)]'

