# bundle-remove27
# Autogenerated from man page /usr/share/man/man1/bundle-remove27.1.bz2
complete -c bundle-remove27 -l install -d 'Runs bundle install after the given gems have been removed from the Gemfile, …'

