# bundle-exec26
# Autogenerated from man page /usr/share/man/man1/bundle-exec26.1.bz2
complete -c bundle-exec26 -l keep-file-descriptors -d 'Exec in Ruby 2. 0 began discarding non-standard file descriptors'

