# bundle-show27
# Autogenerated from man page /usr/share/man/man1/bundle-show27.1.bz2
complete -c bundle-show27 -l paths -d 'List the paths of all gems that are required by your [Gemfile(5)][Gemfile(5)]…'

