# bundle-add27
# Autogenerated from man page /usr/share/man/man1/bundle-add27.1.bz2
complete -c bundle-add27 -l version -s v -d 'Specify version requirements(s) for the added gem'
complete -c bundle-add27 -l group -s g -d 'Specify the group(s) for the added gem'
complete -c bundle-add27 -l source -s s -d 'Specify the source for the added gem'
complete -c bundle-add27 -l git -d 'Specify the git source for the added gem'
complete -c bundle-add27 -l branch -d 'Specify the git branch for the added gem'
complete -c bundle-add27 -l skip-install -d 'Adds the gem to the Gemfile but does not install it'
complete -c bundle-add27 -l optimistic -d 'Adds optimistic declaration of version '

