# bundle-exec27
# Autogenerated from man page /usr/share/man/man1/bundle-exec27.1.bz2
complete -c bundle-exec27 -l keep-file-descriptors -d 'Exec in Ruby 2. 0 began discarding non-standard file descriptors'

