# bundle-viz26
# Autogenerated from man page /usr/share/man/man1/bundle-viz26.1.bz2
complete -c bundle-viz26 -l file -s f -d 'The name to use for the generated file.  See --format option '
complete -c bundle-viz26 -l format -s F -d 'This is output format option.  Supported format is png, jpg, svg, dot '
complete -c bundle-viz26 -l requirements -s R -d 'Set to show the version of each required dependency'
complete -c bundle-viz26 -l version -s v -d 'Set to show each gem version'

