# bundle-platform27
# Autogenerated from man page /usr/share/man/man1/bundle-platform27.1.bz2
complete -c bundle-platform27 -l ruby -d 'It will display the ruby directive information, so you don\'t have to parse it…'

