# ccmakedep
# Autogenerated from man page /usr/share/man/man1/ccmakedep.1.bz2
complete -c ccmakedep -s a -d 'Append the dependencies to the file instead of replacing existing dependencies'
complete -c ccmakedep -o cc -d 'Use this compiler to generate dependencies'
complete -c ccmakedep -s f -d Filename
complete -c ccmakedep -s s -d 'Starting string delimiter'
complete -c ccmakedep -s v -d 'Be verbose: display the C compiler command before running it'
complete -c ccmakedep -s D -d and
complete -c ccmakedep -s U -d 'options to define and undefine symbols and'
complete -c ccmakedep -s I -d 'to set the include path'
complete -c ccmakedep -o f- -d 'sends the output to standard output instead of modifying an existing file'

