# cert-sync
# Autogenerated from man page /usr/share/man/man1/cert-sync.1.bz2
complete -c cert-sync -l quiet -d 'Suppress verbose output'
complete -c cert-sync -l user -d 'Populate the per-user store in the user\'s home directory, instead of the  sys…'

