# cli-generate
# Autogenerated from man page /usr/share/man/man1/cli-generate.1.bz2
complete -c cli-generate -s c -d 'Output C source code'
complete -c cli-generate -s h -d 'Output C header file'
complete -c cli-generate -s m -d 'Output a UNIX man page'
complete -c cli-generate -s w -d 'Output HTML (web) markup'
complete -c cli-generate -s v -l verbose
complete -c cli-generate -s t -l type -d 'The type of the file to generate'

