# cmatrix
# Autogenerated from man page /usr/share/man/man1/cmatrix.1.bz2
complete -c cmatrix -s a -d 'Asynchronous scroll'
complete -c cmatrix -s b -d 'Bold characters on'
complete -c cmatrix -s B -d 'All bold characters (overrides -b)'
complete -c cmatrix -s f -d 'Force the linux $TERM type to be on'
complete -c cmatrix -s l -d 'Linux mode (sets "matrix. fnt" font in console)'
complete -c cmatrix -s o -d 'Use old-style scrolling'
complete -c cmatrix -s h -s '?' -d 'Print usage and exit'
complete -c cmatrix -s n -d 'No bold characters (overrides -b and -B)'
complete -c cmatrix -s s -d '"Screensaver" mode, exits on first keystroke'
complete -c cmatrix -s m -d '"Lambda" mode, every character becomes a lambda'
complete -c cmatrix -s x -d 'X window mode, use if your xterm is using mtx. pcf'
complete -c cmatrix -s V -d 'Print version information and exit'
complete -c cmatrix -s u -d 'Screen update delay 0 - 9, default 4'
complete -c cmatrix -s C -d 'Use this color for matrix (default green)'

