# crontab
# Autogenerated from man page /usr/share/man/man1/crontab.1.bz2
complete -c crontab -s u -d 'Tell  bcron-spool that we are acting on behalf of the named user'
complete -c crontab -s l -d 'List the cronab crontab to standard output'
complete -c crontab -s r -d 'Remove the user\'s crontab'
complete -c crontab -s e -d 'Edit the current crontab.  ENVIRONMENT'

