# dbmmanage
# Autogenerated from man page /usr/share/man/man1/dbmmanage.1.bz2
complete -c dbmmanage -s d -d 'crypt encryption (default, except on Win32, Netware)'
complete -c dbmmanage -s m -d 'MD5 encryption (default on Win32, Netware)'
complete -c dbmmanage -s s -d 'SHA1 encryption'
complete -c dbmmanage -s p -d 'plaintext (not recommended)      . SS "Commands"'

