# dd
# Autogenerated from man page /usr/share/man/man1/dd.1.bz2
complete -c dd -l help -d 'display this help and exit'
complete -c dd -l version -d 'output version information and exit AUTHOR Written by Paul Rubin, David MacKe…'

