# devlink-sb
# Autogenerated from man page /usr/share/man/man8/devlink-sb.8.bz2
complete -c devlink-sb -s V
complete -c devlink-sb -s n -d 'devlink sb show  [  DEV  [  sb SB_INDEX  ] ] devlink sb pool show  [  DEV  [ …'

