# devlink-dpipe
# Autogenerated from man page /usr/share/man/man8/devlink-dpipe.8.bz2
complete -c devlink-dpipe -s V -d 'devlink dpipe table show  DEV [   name TABLE_NAME  ] devlink dpipe table set …'

