# devlink-resource
# Autogenerated from man page /usr/share/man/man8/devlink-resource.8.bz2
complete -c devlink-resource -s v -d 'devlink resource show DEV devlink resource help devlink resource set DEV path…'

