# dhcpd
# Autogenerated from man page /usr/share/man/man8/dhcpd.8.bz2
complete -c dhcpd -s 4 -d 'or '
complete -c dhcpd -s 6 -d arguments
complete -c dhcpd -o 4o6 -d 'Participate in the DHCPv4 over DHCPv6 protocol specified by RFC 7341'
complete -c dhcpd -s p -d 'The UDP port number on which  dhcpd should listen'
complete -c dhcpd -s s -d 'Specify an address or host name to which  dhcpd should send replies rather th…'
complete -c dhcpd -s f -d 'Force dhcpd to run as a foreground process instead of as a daemon in the back…'
complete -c dhcpd -s d -d 'Send log messages to the standard error descriptor'
complete -c dhcpd -s q -d 'Be quiet at startup'
complete -c dhcpd -s t -d 'Test the configuration file'
complete -c dhcpd -s T -d 'Test the lease file'
complete -c dhcpd -o user -d 'Setuid to user after completing privileged operations, such as creating socke…'
complete -c dhcpd -o group -d 'Setgid to group after completing privileged operations, such as creating sock…'
complete -c dhcpd -o chroot -d 'Chroot to directory'
complete -c dhcpd -o tf -d 'Specify a file into which the entire startup state of the server and all the …'
complete -c dhcpd -o play -d 'Specify a file from which the entire startup state of the server and all the …'
complete -c dhcpd -l version -d 'Print version number and exit'
complete -c dhcpd -o cf -d 'Path to alternate configuration file'
complete -c dhcpd -o lf -d 'Path to alternate lease file'
complete -c dhcpd -o pf -d 'Path to alternate pid file'
complete -c dhcpd -l no-pid -d 'Option to disable writing pid files'

