# dmeventd
# Autogenerated from man page /usr/share/man/man8/dmeventd.8.bz2
complete -c dmeventd -s d
complete -c dmeventd -o dd
complete -c dmeventd -o ddd -d ') to increase the detail of debug messages sent to syslog'
complete -c dmeventd -s f
complete -c dmeventd -s h
complete -c dmeventd -s l
complete -c dmeventd -s '?'
complete -c dmeventd -s R
complete -c dmeventd -s V

