# docker-swarm-leave
# Autogenerated from man page /usr/share/man/man1/docker-swarm-leave.1.bz2
complete -c docker-swarm-leave -s f -l force -d '	Force this node to leave the swarm, ignoring warnings'
complete -c docker-swarm-leave -s h -l help -d '	help for leave SEE ALSO'

