# docker-volume-create
# Autogenerated from man page /usr/share/man/man1/docker-volume-create.1.bz2
complete -c docker-volume-create -s o -l opt -d '$ docker volume create --driver fake --opt tardis=blue --opt timey=wimey Thes…'
complete -c docker-volume-create -s d -l driver -d '	Specify volume driver name'
complete -c docker-volume-create -s h -l help -d '	help for create'
complete -c docker-volume-create -l label -d '	Set metadata for a volume'

