# docker-load
# Autogenerated from man page /usr/share/man/man1/docker-load.1.bz2
complete -c docker-load -s h -l help -d '	help for load'
complete -c docker-load -s i -l input -d '	Read from tar archive file, instead of STDIN'
complete -c docker-load -s q -l quiet -d '	Suppress the load output SEE ALSO'

