# docker-checkpoint-rm
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-rm.1.bz2
complete -c docker-checkpoint-rm -l checkpoint-dir -d '	Use a custom checkpoint storage directory'
complete -c docker-checkpoint-rm -s h -l help -d '	help for rm SEE ALSO'

