# docker-plugin-rm
# Autogenerated from man page /usr/share/man/man1/docker-plugin-rm.1.bz2
complete -c docker-plugin-rm -s f -l force -d '	Force the removal of an active plugin'
complete -c docker-plugin-rm -s h -l help -d '	help for rm SEE ALSO'

