# docker-plugin-upgrade
# Autogenerated from man page /usr/share/man/man1/docker-plugin-upgrade.1.bz2
complete -c docker-plugin-upgrade -l disable-content-trust -d '	Skip image verification'
complete -c docker-plugin-upgrade -l grant-all-permissions -d '	Grant all permissions necessary to run the plugin'
complete -c docker-plugin-upgrade -s h -l help -d '	help for upgrade'
complete -c docker-plugin-upgrade -l skip-remote-check -d '	Do not check if specified remote plugin matches existing plugin image SEE AL…'

