# docker-stop
# Autogenerated from man page /usr/share/man/man1/docker-stop.1.bz2
complete -c docker-stop -s h -l help -d '	help for stop'
complete -c docker-stop -s t -l time -d '	Seconds to wait for stop before killing it SEE ALSO'

