# docker-builder-prune
# Autogenerated from man page /usr/share/man/man1/docker-builder-prune.1.bz2
complete -c docker-builder-prune -s a -l all -d '	Remove all unused build cache, not just dangling ones'
complete -c docker-builder-prune -l filter -d '	Provide filter values (e. g.  \'until=24h\')'
complete -c docker-builder-prune -s f -l force -d '	Do not prompt for confirmation'
complete -c docker-builder-prune -s h -l help -d '	help for prune'
complete -c docker-builder-prune -l keep-storage -d '	Amount of disk space to keep for cache SEE ALSO'

