# docker-manifest-create
# Autogenerated from man page /usr/share/man/man1/docker-manifest-create.1.bz2
complete -c docker-manifest-create -s a -l amend -d '	Amend an existing manifest list'
complete -c docker-manifest-create -s h -l help -d '	help for create'
complete -c docker-manifest-create -l insecure -d '	Allow communication with an insecure registry SEE ALSO'

