# docker-swarm-unlock-key
# Autogenerated from man page /usr/share/man/man1/docker-swarm-unlock-key.1.bz2
complete -c docker-swarm-unlock-key -s h -l help -d '	help for unlock-key'
complete -c docker-swarm-unlock-key -s q -l quiet -d '	Only display token'
complete -c docker-swarm-unlock-key -l rotate -d '	Rotate unlock key SEE ALSO'

