# docker-swarm-update
# Autogenerated from man page /usr/share/man/man1/docker-swarm-update.1.bz2
complete -c docker-swarm-update -l autolock -d '	Change manager autolocking setting (true|false)'
complete -c docker-swarm-update -l cert-expiry -d '	Validity period for node certificates (ns|us|ms|s|m|h)'
complete -c docker-swarm-update -l dispatcher-heartbeat -d '	Dispatcher heartbeat period (ns|us|ms|s|m|h)'
complete -c docker-swarm-update -l external-ca -d '	Specifications of one or more certificate signing endpoints'
complete -c docker-swarm-update -s h -l help -d '	help for update'
complete -c docker-swarm-update -l max-snapshots -d '	Number of additional Raft snapshots to retain'
complete -c docker-swarm-update -l snapshot-interval -d '	Number of log entries between Raft snapshots'
complete -c docker-swarm-update -l task-history-limit -d '	Task history retention limit SEE ALSO'

