# docker-context-export
# Autogenerated from man page /usr/share/man/man1/docker-context-export.1.bz2
complete -c docker-context-export -s h -l help -d '	help for export'
complete -c docker-context-export -l kubeconfig -d '	Export as a kubeconfig file SEE ALSO'

