# docker-ps
# Autogenerated from man page /usr/share/man/man1/docker-ps.1.bz2
complete -c docker-ps -s a -l all -d '	Show all containers (default shows just running)'
complete -c docker-ps -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-ps -l format -d '	Pretty-print containers using a Go template'
complete -c docker-ps -s h -l help -d '	help for ps'
complete -c docker-ps -s n -l last -s 1 -d '	Show n last created containers (includes all states)'
complete -c docker-ps -s l -l latest -d '	Show the latest created container (includes all states)'
complete -c docker-ps -l no-trunc -d '	Don\'t truncate output'
complete -c docker-ps -s q -l quiet -d '	Only display container IDs'
complete -c docker-ps -s s -l size -d '	Display total file sizes SEE ALSO'

