# docker-context-rm
# Autogenerated from man page /usr/share/man/man1/docker-context-rm.1.bz2
complete -c docker-context-rm -s f -l force -d '	Force the removal of a context in use'
complete -c docker-context-rm -s h -l help -d '	help for rm SEE ALSO'

