# docker-volume-rm
# Autogenerated from man page /usr/share/man/man1/docker-volume-rm.1.bz2
complete -c docker-volume-rm -s f -l force -d '	Force the removal of one or more volumes'
complete -c docker-volume-rm -s h -l help -d '	help for rm EXAMPLE $ docker volume rm hello hello SEE ALSO'

