# docker-stack
# Autogenerated from man page /usr/share/man/man1/docker-stack.1.bz2
complete -c docker-stack -s h -l help -d '	help for stack'
complete -c docker-stack -l kubeconfig -d '	Kubernetes config file'
complete -c docker-stack -l orchestrator -d '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO'

