# docker-container-attach
# Autogenerated from man page /usr/share/man/man1/docker-container-attach.1.bz2
complete -c docker-container-attach -l detach-keys -d 'the <sequence> is either a letter [a-Z], or the ctrl- combined with any of th…'
complete -c docker-container-attach -s h -l help -d '	help for attach'
complete -c docker-container-attach -l no-stdin -d '	Do not attach STDIN'
complete -c docker-container-attach -l sig-proxy -d '	Proxy all received signals to the process SEE ALSO'

