# docker-system-prune
# Autogenerated from man page /usr/share/man/man1/docker-system-prune.1.bz2
complete -c docker-system-prune -s a -l all -d '	Remove all unused images not just dangling ones'
complete -c docker-system-prune -l filter -d '	Provide filter values (e. g.  \'label==\')'
complete -c docker-system-prune -s f -l force -d '	Do not prompt for confirmation'
complete -c docker-system-prune -s h -l help -d '	help for prune'
complete -c docker-system-prune -l volumes -d '	Prune volumes SEE ALSO'

