# docker-stack-deploy
# Autogenerated from man page /usr/share/man/man1/docker-stack-deploy.1.bz2
complete -c docker-stack-deploy -s c -l compose-file -d '	Path to a Compose file, or "-" to read from stdin'
complete -c docker-stack-deploy -s h -l help -d '	help for deploy'
complete -c docker-stack-deploy -l namespace -d '	Kubernetes namespace to use'
complete -c docker-stack-deploy -l prune -d '	Prune services that are no longer referenced'
complete -c docker-stack-deploy -l resolve-image -d '	Query the registry to resolve image digest and supported platforms ("always"…'
complete -c docker-stack-deploy -l with-registry-auth -d '	Send registry authentication details to Swarm agents OPTIONS INHERITED FROM …'
complete -c docker-stack-deploy -l kubeconfig -d '	Kubernetes config file'
complete -c docker-stack-deploy -l orchestrator -d '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO'

