# docker-container-inspect
# Autogenerated from man page /usr/share/man/man1/docker-container-inspect.1.bz2
complete -c docker-container-inspect -s f -l format -d '	Format the output using the given Go template'
complete -c docker-container-inspect -s h -l help -d '	help for inspect'
complete -c docker-container-inspect -s s -l size -d '	Display total file sizes SEE ALSO'

