# docker-trust-key-load
# Autogenerated from man page /usr/share/man/man1/docker-trust-key-load.1.bz2
complete -c docker-trust-key-load -s h -l help -d '	help for load'
complete -c docker-trust-key-load -l name -d '	Name for the loaded key SEE ALSO'

