# docker-container-ls
# Autogenerated from man page /usr/share/man/man1/docker-container-ls.1.bz2
complete -c docker-container-ls -s a -l all -d '	Show all containers (default shows just running)'
complete -c docker-container-ls -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-container-ls -l format -d '	Pretty-print containers using a Go template'
complete -c docker-container-ls -s h -l help -d '	help for ls'
complete -c docker-container-ls -s n -l last -s 1 -d '	Show n last created containers (includes all states)'
complete -c docker-container-ls -s l -l latest -d '	Show the latest created container (includes all states)'
complete -c docker-container-ls -l no-trunc -d '	Don\'t truncate output'
complete -c docker-container-ls -s q -l quiet -d '	Only display container IDs'
complete -c docker-container-ls -s s -l size -d '	Display total file sizes SEE ALSO'

