# docker-swarm-join
# Autogenerated from man page /usr/share/man/man1/docker-swarm-join.1.bz2
complete -c docker-swarm-join -l advertise-addr -d '	Advertised address (format: [:port])'
complete -c docker-swarm-join -l availability -d '	Availability of the node ("active"|"pause"|"drain")'
complete -c docker-swarm-join -l data-path-addr -d '	Address or interface to use for data path traffic (format: )'
complete -c docker-swarm-join -s h -l help -d '	help for join'
complete -c docker-swarm-join -l listen-addr -d '	Listen address (format: [:port])'
complete -c docker-swarm-join -l token -d '	Token for entry into the swarm SEE ALSO'

