# docker-history
# Autogenerated from man page /usr/share/man/man1/docker-history.1.bz2
complete -c docker-history -l format -d '	Pretty-print images using a Go template'
complete -c docker-history -s h -l help -d '	help for history'
complete -c docker-history -s H -l human -d '	Print sizes and dates in human readable format'
complete -c docker-history -l no-trunc -d '	Don\'t truncate output'
complete -c docker-history -s q -l quiet -d '	Only show image IDs SEE ALSO'

