# docker-system-df
# Autogenerated from man page /usr/share/man/man1/docker-system-df.1.bz2
complete -c docker-system-df -l format -d '	Pretty-print images using a Go template'
complete -c docker-system-df -s h -l help -d '	help for df'
complete -c docker-system-df -s v -l verbose -d '	Show detailed information on space usage SEE ALSO'

