# docker-plugin-create
# Autogenerated from man page /usr/share/man/man1/docker-plugin-create.1.bz2
complete -c docker-plugin-create -l compress -d '	Compress the context using gzip'
complete -c docker-plugin-create -s h -l help -d '	help for create SEE ALSO'

