# docker-network-prune
# Autogenerated from man page /usr/share/man/man1/docker-network-prune.1.bz2
complete -c docker-network-prune -l filter -d '	Provide filter values (e. g.  \'until=\')'
complete -c docker-network-prune -s f -l force -d '	Do not prompt for confirmation'
complete -c docker-network-prune -s h -l help -d '	help for prune SEE ALSO'

