# docker-secret-ls
# Autogenerated from man page /usr/share/man/man1/docker-secret-ls.1.bz2
complete -c docker-secret-ls -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-secret-ls -l format -d '	Pretty-print secrets using a Go template'
complete -c docker-secret-ls -s h -l help -d '	help for ls'
complete -c docker-secret-ls -s q -l quiet -d '	Only display IDs SEE ALSO'

