# docker
# Autogenerated from man page /usr/share/man/man1/docker.1.bz2
complete -c docker -l help -d '  Print usage statement'
complete -c docker -l config -d '  Specifies the location of the Docker client configuration files'
complete -c docker -s D -l debug -d '  Enable debug mode.  Default is false'
complete -c docker -s H -l host -d 'unix://[/path/to/socket] to use'
complete -c docker -s l -l log-level -d '  Set the logging level.  Default is info'
complete -c docker -l tls -d '  Use TLS; implied by --tlsverify.  Default is false'
complete -c docker -l tlscacert -d '  Trust certs signed only by this CA'
complete -c docker -l tlscert -d '  Path to TLS certificate file'
complete -c docker -l tlskey -d '  Path to TLS key file'
complete -c docker -l tlsverify -d '  Use TLS and verify the remote (daemon: verify client, client: verify daemon)'
complete -c docker -s v -l version -d '  Print version information and quit.  Default is false.  COMMANDS'

