# docker-trust-key-generate
# Autogenerated from man page /usr/share/man/man1/docker-trust-key-generate.1.bz2
complete -c docker-trust-key-generate -l dir -d '	Directory to generate key in, defaults to current directory'
complete -c docker-trust-key-generate -s h -l help -d '	help for generate SEE ALSO'

