# docker-inspect
# Autogenerated from man page /usr/share/man/man1/docker-inspect.1.bz2
complete -c docker-inspect -s f -l format -d '	Format the output using the given Go template'
complete -c docker-inspect -s h -l help -d '	help for inspect'
complete -c docker-inspect -s s -l size -d '	Display total file sizes if the type is container'
complete -c docker-inspect -l type -d '	Return JSON for specified type SEE ALSO'

