# docker-commit
# Autogenerated from man page /usr/share/man/man1/docker-commit.1.bz2
complete -c docker-commit -s a -l author -d '	Author (e. g. , "John Hannibal Smith hannibal@a-team'
complete -c docker-commit -s c -l change -d '	Apply Dockerfile instruction to the created image'
complete -c docker-commit -s h -l help -d '	help for commit'
complete -c docker-commit -s m -l message -d '	Commit message'
complete -c docker-commit -s p -l pause -d '	Pause container during commit SEE ALSO'

