# docker-secret-create
# Autogenerated from man page /usr/share/man/man1/docker-secret-create.1.bz2
complete -c docker-secret-create -s d -l driver -d '	Secret driver'
complete -c docker-secret-create -s h -l help -d '	help for create'
complete -c docker-secret-create -s l -l label -d '	Secret labels'
complete -c docker-secret-create -l template-driver -d '	Template driver SEE ALSO'

