# docker-service-rollback
# Autogenerated from man page /usr/share/man/man1/docker-service-rollback.1.bz2
complete -c docker-service-rollback -s d -l detach -d '	Exit immediately instead of waiting for the service to converge'
complete -c docker-service-rollback -s h -l help -d '	help for rollback'
complete -c docker-service-rollback -s q -l quiet -d '	Suppress progress output SEE ALSO'

