# docker-stack-services
# Autogenerated from man page /usr/share/man/man1/docker-stack-services.1.bz2
complete -c docker-stack-services -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-stack-services -l format -d '	Pretty-print services using a Go template'
complete -c docker-stack-services -s h -l help -d '	help for services'
complete -c docker-stack-services -l namespace -d '	Kubernetes namespace to use'
complete -c docker-stack-services -s q -l quiet -d '	Only display IDs OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c docker-stack-services -l kubeconfig -d '	Kubernetes config file'
complete -c docker-stack-services -l orchestrator -d '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO'

