# docker-image-pull
# Autogenerated from man page /usr/share/man/man1/docker-image-pull.1.bz2
complete -c docker-image-pull -s a -l all-tags -d 'This command pulls all images from the fedora repository: $ docker image pull…'
complete -c docker-image-pull -l disable-content-trust -d '	Skip image verification'
complete -c docker-image-pull -s h -l help -d '	help for pull'
complete -c docker-image-pull -l platform -d '	Set platform if server is multi-platform capable'
complete -c docker-image-pull -s q -l quiet -d '	Suppress verbose output SEE ALSO'

