# docker-network-create
# Autogenerated from man page /usr/share/man/man1/docker-network-create.1.bz2
complete -c docker-network-create -l driver -d 'When you install Docker Engine it creates a bridge network automatically'
complete -c docker-network-create -l cluster-store -d 'o 2'
complete -c docker-network-create -l cluster-store-opt -d 'o 2'
complete -c docker-network-create -l cluster-advertise -d 'To read more about these options and how to configure them, see "Get started …'
complete -c docker-network-create -l internal
complete -c docker-network-create -l attachable -d '	Enable manual container attachment'
complete -c docker-network-create -l aux-address -d '	Auxiliary IPv4 or IPv6 addresses used by Network driver'
complete -c docker-network-create -l config-from -d '	The network from which to copy the configuration'
complete -c docker-network-create -l config-only -d '	Create a configuration only network'
complete -c docker-network-create -s d -d '	Driver to manage the Network'
complete -c docker-network-create -l gateway -d '	IPv4 or IPv6 Gateway for the master subnet'
complete -c docker-network-create -s h -l help -d '	help for create'
complete -c docker-network-create -l ingress -d '	Create swarm routing-mesh network'
complete -c docker-network-create -l ip-range -d '	Allocate container ip from a sub-range'
complete -c docker-network-create -l ipam-driver -d '	IP Address Management Driver'
complete -c docker-network-create -l ipam-opt -d '	Set IPAM driver specific options'
complete -c docker-network-create -l ipv6 -d '	Enable IPv6 networking'
complete -c docker-network-create -l label -d '	Set metadata on a network'
complete -c docker-network-create -s o -l opt -d '	Set driver specific options'
complete -c docker-network-create -l scope -d '	Control the network\'s scope'
complete -c docker-network-create -l subnet -d '	Subnet in CIDR format that represents a network segment SEE ALSO'

