# docker-plugin-enable
# Autogenerated from man page /usr/share/man/man1/docker-plugin-enable.1.bz2
complete -c docker-plugin-enable -s h -l help -d '	help for enable'
complete -c docker-plugin-enable -l timeout -d '	HTTP client timeout (in seconds) SEE ALSO'

