# docker-node-rm
# Autogenerated from man page /usr/share/man/man1/docker-node-rm.1.bz2
complete -c docker-node-rm -s f -l force -d '	Force remove a node from the swarm'
complete -c docker-node-rm -s h -l help -d '	help for rm SEE ALSO'

