# docker-checkpoint-ls
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint-ls.1.bz2
complete -c docker-checkpoint-ls -l checkpoint-dir -d '	Use a custom checkpoint storage directory'
complete -c docker-checkpoint-ls -s h -l help -d '	help for ls SEE ALSO'

