# docker-export
# Autogenerated from man page /usr/share/man/man1/docker-export.1.bz2
complete -c docker-export -s h -l help -d '	help for export'
complete -c docker-export -s o -l output -d '	Write to a file, instead of STDOUT SEE ALSO'

