# docker-plugin-disable
# Autogenerated from man page /usr/share/man/man1/docker-plugin-disable.1.bz2
complete -c docker-plugin-disable -s f -l force -d '	Force the disable of an active plugin'
complete -c docker-plugin-disable -s h -l help -d '	help for disable SEE ALSO'

