# docker-trust-inspect
# Autogenerated from man page /usr/share/man/man1/docker-trust-inspect.1.bz2
complete -c docker-trust-inspect -s h -l help -d '	help for inspect'
complete -c docker-trust-inspect -l pretty -d '	Print the information in a human friendly format SEE ALSO'

