# docker-trust-signer-add
# Autogenerated from man page /usr/share/man/man1/docker-trust-signer-add.1.bz2
complete -c docker-trust-signer-add -s h -l help -d '	help for add'
complete -c docker-trust-signer-add -l key -d '	Path to the signer\'s public key file SEE ALSO'

