# docker-images
# Autogenerated from man page /usr/share/man/man1/docker-images.1.bz2
complete -c docker-images -s a -l all -d '	Show all images (default hides intermediate images)'
complete -c docker-images -l digests -d '	Show digests'
complete -c docker-images -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-images -l format -d '	Pretty-print images using a Go template'
complete -c docker-images -s h -l help -d '	help for images'
complete -c docker-images -l no-trunc -d '	Don\'t truncate output'
complete -c docker-images -s q -l quiet -d '	Only show image IDs SEE ALSO'

