# docker-image-push
# Autogenerated from man page /usr/share/man/man1/docker-image-push.1.bz2
complete -c docker-image-push -s a -l all-tags -d '	Push all tagged images in the repository'
complete -c docker-image-push -l disable-content-trust -d '	Skip image signing'
complete -c docker-image-push -s h -l help -d '	help for push'
complete -c docker-image-push -s q -l quiet -d '	Suppress verbose output SEE ALSO'

