# docker-container-restart
# Autogenerated from man page /usr/share/man/man1/docker-container-restart.1.bz2
complete -c docker-container-restart -s h -l help -d '	help for restart'
complete -c docker-container-restart -s t -l time -d '	Seconds to wait for stop before killing the container SEE ALSO'

