# docker-cp
# Autogenerated from man page /usr/share/man/man1/docker-cp.1.bz2
complete -c docker-cp -s a -l archive -d '	Archive mode (copy all uid/gid information)'
complete -c docker-cp -s L -l follow-link -d '	Always follow symbol link in SRC_PATH'
complete -c docker-cp -s h -l help -d '	help for cp SEE ALSO'

