# docker-network-inspect
# Autogenerated from man page /usr/share/man/man1/docker-network-inspect.1.bz2
complete -c docker-network-inspect -s f -l format -d '	Format the output using the given Go template'
complete -c docker-network-inspect -s h -l help -d '	help for inspect'
complete -c docker-network-inspect -s v -l verbose -d '	Verbose output for diagnostics SEE ALSO'

