# docker-secret-inspect
# Autogenerated from man page /usr/share/man/man1/docker-secret-inspect.1.bz2
complete -c docker-secret-inspect -s f -l format -d '	Format the output using the given Go template'
complete -c docker-secret-inspect -s h -l help -d '	help for inspect'
complete -c docker-secret-inspect -l pretty -d '	Print the information in a human friendly format SEE ALSO'

