# docker-network-disconnect
# Autogenerated from man page /usr/share/man/man1/docker-network-disconnect.1.bz2
complete -c docker-network-disconnect -s f -l force -d '	Force the container to disconnect from a network'
complete -c docker-network-disconnect -s h -l help -d '	help for disconnect SEE ALSO'

