# docker-logs
# Autogenerated from man page /usr/share/man/man1/docker-logs.1.bz2
complete -c docker-logs -l details -d '	Show extra details provided to logs'
complete -c docker-logs -s f -l follow -d '	Follow log output'
complete -c docker-logs -s h -l help -d '	help for logs'
complete -c docker-logs -l since -d '	Show logs since timestamp (e. g.  2013-01-02T13:23:37Z) or relative (e. g'
complete -c docker-logs -s n -l tail -d '	Number of lines to show from the end of the logs'
complete -c docker-logs -s t -l timestamps -d '	Show timestamps'
complete -c docker-logs -l until -d '	Show logs before a timestamp (e. g.  2013-01-02T13:23:37Z) or relative (e. g'

