# docker-node-update
# Autogenerated from man page /usr/share/man/man1/docker-node-update.1.bz2
complete -c docker-node-update -l availability -d '	Availability of the node ("active"|"pause"|"drain")'
complete -c docker-node-update -s h -l help -d '	help for update'
complete -c docker-node-update -l label-add -d '	Add or update a node label (key=value)'
complete -c docker-node-update -l label-rm -d '	Remove a node label if exists'
complete -c docker-node-update -l role -d '	Role of the node ("worker"|"manager") SEE ALSO'

