# docker-version
# Autogenerated from man page /usr/share/man/man1/docker-version.1.bz2
complete -c docker-version -s f -l format -d '	Format the output using the given Go template'
complete -c docker-version -s h -l help -d '	help for version'
complete -c docker-version -l kubeconfig -d '	Kubernetes config file SEE ALSO'

