# docker-service-ps
# Autogenerated from man page /usr/share/man/man1/docker-service-ps.1.bz2
complete -c docker-service-ps -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-service-ps -l format -d '	Pretty-print tasks using a Go template'
complete -c docker-service-ps -s h -l help -d '	help for ps'
complete -c docker-service-ps -l no-resolve -d '	Do not map IDs to Names'
complete -c docker-service-ps -l no-trunc -d '	Do not truncate output'
complete -c docker-service-ps -s q -l quiet -d '	Only display task IDs SEE ALSO'

