# docker-plugin-push
# Autogenerated from man page /usr/share/man/man1/docker-plugin-push.1.bz2
complete -c docker-plugin-push -l disable-content-trust -d '	Skip image signing'
complete -c docker-plugin-push -s h -l help -d '	help for push SEE ALSO'

