# docker-context-ls
# Autogenerated from man page /usr/share/man/man1/docker-context-ls.1.bz2
complete -c docker-context-ls -l format -d '	Pretty-print contexts using a Go template'
complete -c docker-context-ls -s h -l help -d '	help for ls'
complete -c docker-context-ls -s q -l quiet -d '	Only show context names SEE ALSO'

