# docker-events
# Autogenerated from man page /usr/share/man/man1/docker-events.1.bz2
complete -c docker-events -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-events -l format -d '	Format the output using the given Go template'
complete -c docker-events -s h -l help -d '	help for events'
complete -c docker-events -l since -d '	Show all events created since timestamp'
complete -c docker-events -l until -d '	Stream events until this timestamp SEE ALSO'

