# docker-rmi
# Autogenerated from man page /usr/share/man/man1/docker-rmi.1.bz2
complete -c docker-rmi -s f -l force -d '	Force removal of the image'
complete -c docker-rmi -s h -l help -d '	help for rmi'
complete -c docker-rmi -l no-prune -d '	Do not delete untagged parents SEE ALSO'

