# docker-context-update
# Autogenerated from man page /usr/share/man/man1/docker-context-update.1.bz2
complete -c docker-context-update -l default-stack-orchestrator -d '	Default orchestrator for stack operations to use with this context (swarm|ku…'
complete -c docker-context-update -l description -d '	Description of the context'
complete -c docker-context-update -l docker -d '	set the docker endpoint'
complete -c docker-context-update -s h -l help -d '	help for update'
complete -c docker-context-update -l kubernetes -d '	set the kubernetes endpoint SEE ALSO'

