# docker-image-import
# Autogenerated from man page /usr/share/man/man1/docker-image-import.1.bz2
complete -c docker-image-import -l platform -d 'daemon.  # docker image import --platform=linux . \\linuximage. tar See also'
complete -c docker-image-import -s c -l change -d '	Apply Dockerfile instruction to the created image'
complete -c docker-image-import -s h -l help -d '	help for import'
complete -c docker-image-import -s m -l message -d '	Set commit message for imported image'

