# docker-service-logs
# Autogenerated from man page /usr/share/man/man1/docker-service-logs.1.bz2
complete -c docker-service-logs -l details -d '	Show extra details provided to logs'
complete -c docker-service-logs -s f -l follow -d '	Follow log output'
complete -c docker-service-logs -s h -l help -d '	help for logs'
complete -c docker-service-logs -l no-resolve -d '	Do not map IDs to Names in output'
complete -c docker-service-logs -l no-task-ids -d '	Do not include task IDs in output'
complete -c docker-service-logs -l no-trunc -d '	Do not truncate output'
complete -c docker-service-logs -l raw -d '	Do not neatly format logs'
complete -c docker-service-logs -l since -d '	Show logs since timestamp (e. g.  2013-01-02T13:23:37Z) or relative (e. g'
complete -c docker-service-logs -s n -l tail -d '	Number of lines to show from the end of the logs'
complete -c docker-service-logs -s t -l timestamps -d '	Show timestamps SEE ALSO'

