# docker-swarm-init
# Autogenerated from man page /usr/share/man/man1/docker-swarm-init.1.bz2
complete -c docker-swarm-init -l advertise-addr -d '	Advertised address (format: [:port])'
complete -c docker-swarm-init -l autolock -d '	Enable manager autolocking (requiring an unlock key to start a stopped manag…'
complete -c docker-swarm-init -l availability -d '	Availability of the node ("active"|"pause"|"drain")'
complete -c docker-swarm-init -l cert-expiry -d '	Validity period for node certificates (ns|us|ms|s|m|h)'
complete -c docker-swarm-init -l data-path-addr -d '	Address or interface to use for data path traffic (format: )'
complete -c docker-swarm-init -l data-path-port -d '	Port number to use for data path traffic (1024 - 49151)'
complete -c docker-swarm-init -l default-addr-pool -d '	default address pool in CIDR format'
complete -c docker-swarm-init -l default-addr-pool-mask-length -d '	default address pool subnet mask length'
complete -c docker-swarm-init -l dispatcher-heartbeat -d '	Dispatcher heartbeat period (ns|us|ms|s|m|h)'
complete -c docker-swarm-init -l external-ca -d '	Specifications of one or more certificate signing endpoints'
complete -c docker-swarm-init -l force-new-cluster -d '	Force create a new cluster from current state'
complete -c docker-swarm-init -s h -l help -d '	help for init'
complete -c docker-swarm-init -l listen-addr -d '	Listen address (format: [:port])'
complete -c docker-swarm-init -l max-snapshots -d '	Number of additional Raft snapshots to retain'
complete -c docker-swarm-init -l snapshot-interval -d '	Number of log entries between Raft snapshots'
complete -c docker-swarm-init -l task-history-limit -d '	Task history retention limit SEE ALSO'

