# docker-manifest-annotate
# Autogenerated from man page /usr/share/man/man1/docker-manifest-annotate.1.bz2
complete -c docker-manifest-annotate -l arch -d '	Set architecture'
complete -c docker-manifest-annotate -s h -l help -d '	help for annotate'
complete -c docker-manifest-annotate -l os -d '	Set operating system'
complete -c docker-manifest-annotate -l os-features -d '	Set operating system feature'
complete -c docker-manifest-annotate -l os-version -d '	Set operating system version'
complete -c docker-manifest-annotate -l variant -d '	Set architecture variant SEE ALSO'

