# docker-image-rm
# Autogenerated from man page /usr/share/man/man1/docker-image-rm.1.bz2
complete -c docker-image-rm -s f -l force -d '	Force removal of the image'
complete -c docker-image-rm -s h -l help -d '	help for rm'
complete -c docker-image-rm -l no-prune -d '	Do not delete untagged parents SEE ALSO'

