# docker-rm
# Autogenerated from man page /usr/share/man/man1/docker-rm.1.bz2
complete -c docker-rm -s f -l force -d '	Force the removal of a running container (uses SIGKILL)'
complete -c docker-rm -s h -l help -d '	help for rm'
complete -c docker-rm -s l -l link -d '	Remove the specified link'
complete -c docker-rm -s v -l volumes -d '	Remove anonymous volumes associated with the container SEE ALSO'

