# docker-trust-signer-remove
# Autogenerated from man page /usr/share/man/man1/docker-trust-signer-remove.1.bz2
complete -c docker-trust-signer-remove -s f -l force -d '	Do not prompt for confirmation before removing the most recent signer'
complete -c docker-trust-signer-remove -s h -l help -d '	help for remove SEE ALSO'

