# docker-login
# Autogenerated from man page /usr/share/man/man1/docker-login.1.bz2
complete -c docker-login -s h -l help -d '	help for login'
complete -c docker-login -s p -l password -d '	Password'
complete -c docker-login -l password-stdin -d '	Take the password from stdin'
complete -c docker-login -s u -l username -d '	Username SEE ALSO'

