# docker-stack-rm
# Autogenerated from man page /usr/share/man/man1/docker-stack-rm.1.bz2
complete -c docker-stack-rm -s h -l help -d '	help for rm'
complete -c docker-stack-rm -l namespace -d '	Kubernetes namespace to use OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c docker-stack-rm -l kubeconfig -d '	Kubernetes config file'
complete -c docker-stack-rm -l orchestrator -d '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO'

