# docker-stack-ls
# Autogenerated from man page /usr/share/man/man1/docker-stack-ls.1.bz2
complete -c docker-stack-ls -l all-namespaces -d '	List stacks from all Kubernetes namespaces'
complete -c docker-stack-ls -l format -d '	Pretty-print stacks using a Go template'
complete -c docker-stack-ls -s h -l help -d '	help for ls'
complete -c docker-stack-ls -l namespace -d '	Kubernetes namespaces to use OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c docker-stack-ls -l kubeconfig -d '	Kubernetes config file'
complete -c docker-stack-ls -l orchestrator -d '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO'

