# docker-config-create
# Autogenerated from man page /usr/share/man/man1/docker-config-create.1.bz2
complete -c docker-config-create -s h -l help -d '	help for create'
complete -c docker-config-create -s l -l label -d '	Config labels'
complete -c docker-config-create -l template-driver -d '	Template driver SEE ALSO'

