# docker-manifest-push
# Autogenerated from man page /usr/share/man/man1/docker-manifest-push.1.bz2
complete -c docker-manifest-push -s h -l help -d '	help for push'
complete -c docker-manifest-push -l insecure -d '	Allow push to an insecure registry'
complete -c docker-manifest-push -s p -l purge -d '	Remove the local manifest list after push SEE ALSO'

