# docker-save
# Autogenerated from man page /usr/share/man/man1/docker-save.1.bz2
complete -c docker-save -s h -l help -d '	help for save'
complete -c docker-save -s o -l output -d '	Write to a file, instead of STDOUT SEE ALSO'

