# docker-container-kill
# Autogenerated from man page /usr/share/man/man1/docker-container-kill.1.bz2
complete -c docker-container-kill -s h -l help -d '	help for kill'
complete -c docker-container-kill -s s -l signal -d '	Signal to send to the container SEE ALSO'

