# docker-info
# Autogenerated from man page /usr/share/man/man1/docker-info.1.bz2
complete -c docker-info -s f -l format -d '	Format the output using the given Go template'
complete -c docker-info -s h -l help -d '	help for info SEE ALSO'

