# docker-volume-prune
# Autogenerated from man page /usr/share/man/man1/docker-volume-prune.1.bz2
complete -c docker-volume-prune -l filter -d '	Provide filter values (e. g.  \'label=\')'
complete -c docker-volume-prune -s f -l force -d '	Do not prompt for confirmation'
complete -c docker-volume-prune -s h -l help -d '	help for prune SEE ALSO'

