# docker-pull
# Autogenerated from man page /usr/share/man/man1/docker-pull.1.bz2
complete -c docker-pull -s a -l all-tags -d '	Download all tagged images in the repository'
complete -c docker-pull -l disable-content-trust -d '	Skip image verification'
complete -c docker-pull -s h -l help -d '	help for pull'
complete -c docker-pull -l platform -d '	Set platform if server is multi-platform capable'
complete -c docker-pull -s q -l quiet -d '	Suppress verbose output SEE ALSO'

