# docker-update
# Autogenerated from man page /usr/share/man/man1/docker-update.1.bz2
complete -c docker-update -l blkio-weight -d '	Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0)'
complete -c docker-update -l cpu-period -d '	Limit CPU CFS (Completely Fair Scheduler) period'
complete -c docker-update -l cpu-quota -d '	Limit CPU CFS (Completely Fair Scheduler) quota'
complete -c docker-update -l cpu-rt-period -d '	Limit the CPU real-time period in microseconds'
complete -c docker-update -l cpu-rt-runtime -d '	Limit the CPU real-time runtime in microseconds'
complete -c docker-update -s c -l cpu-shares -d '	CPU shares (relative weight)'
complete -c docker-update -l cpus -d '	Number of CPUs'
complete -c docker-update -l cpuset-cpus -d '	CPUs in which to allow execution (0-3, 0,1)'
complete -c docker-update -l cpuset-mems -d '	MEMs in which to allow execution (0-3, 0,1)'
complete -c docker-update -s h -l help -d '	help for update'
complete -c docker-update -l kernel-memory -d '	Kernel memory limit'
complete -c docker-update -s m -l memory -d '	Memory limit'
complete -c docker-update -l memory-reservation -d '	Memory soft limit'
complete -c docker-update -l memory-swap -d '	Swap limit equal to memory plus swap: \'-1\' to enable unlimited swap'
complete -c docker-update -l pids-limit -d '	Tune container pids limit (set -1 for unlimited)'
complete -c docker-update -l restart -d '	Restart policy to apply when a container exits SEE ALSO'

