# docker-service-scale
# Autogenerated from man page /usr/share/man/man1/docker-service-scale.1.bz2
complete -c docker-service-scale -s d -l detach -d '	Exit immediately instead of waiting for the service to converge'
complete -c docker-service-scale -s h -l help -d '	help for scale SEE ALSO'

