# docker-container-stats
# Autogenerated from man page /usr/share/man/man1/docker-container-stats.1.bz2
complete -c docker-container-stats -s a -l all -d '	Show all containers (default shows just running)'
complete -c docker-container-stats -l format -d '	Pretty-print images using a Go template'
complete -c docker-container-stats -s h -l help -d '	help for stats'
complete -c docker-container-stats -l no-stream -d '	Disable streaming stats and only pull the first result'
complete -c docker-container-stats -l no-trunc -d '	Do not truncate output SEE ALSO'

