# docker-plugin-inspect
# Autogenerated from man page /usr/share/man/man1/docker-plugin-inspect.1.bz2
complete -c docker-plugin-inspect -s f -l format -d '	Format the output using the given Go template'
complete -c docker-plugin-inspect -s h -l help -d '	help for inspect SEE ALSO'

