# docker-stack-ps
# Autogenerated from man page /usr/share/man/man1/docker-stack-ps.1.bz2
complete -c docker-stack-ps -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-stack-ps -l format -d '	Pretty-print tasks using a Go template'
complete -c docker-stack-ps -s h -l help -d '	help for ps'
complete -c docker-stack-ps -l namespace -d '	Kubernetes namespace to use'
complete -c docker-stack-ps -l no-resolve -d '	Do not map IDs to Names'
complete -c docker-stack-ps -l no-trunc -d '	Do not truncate output'
complete -c docker-stack-ps -s q -l quiet -d '	Only display task IDs OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c docker-stack-ps -l kubeconfig -d '	Kubernetes config file'
complete -c docker-stack-ps -l orchestrator -d '	Orchestrator to use (swarm|kubernetes|all) SEE ALSO'

