# docker-trust-revoke
# Autogenerated from man page /usr/share/man/man1/docker-trust-revoke.1.bz2
complete -c docker-trust-revoke -s h -l help -d '	help for revoke'
complete -c docker-trust-revoke -s y -l yes -d '	Do not prompt for confirmation SEE ALSO'

