# docker-image-prune
# Autogenerated from man page /usr/share/man/man1/docker-image-prune.1.bz2
complete -c docker-image-prune -s a -l all -d '	Remove all unused images, not just dangling ones'
complete -c docker-image-prune -l filter -d '	Provide filter values (e. g.  \'until=\')'
complete -c docker-image-prune -s f -l force -d '	Do not prompt for confirmation'
complete -c docker-image-prune -s h -l help -d '	help for prune SEE ALSO'

