# docker-image-ls
# Autogenerated from man page /usr/share/man/man1/docker-image-ls.1.bz2
complete -c docker-image-ls -s a -l all -d '	Show all images (default hides intermediate images)'
complete -c docker-image-ls -l digests -d '	Show digests'
complete -c docker-image-ls -s f -l filter -d '	Filter output based on conditions provided'
complete -c docker-image-ls -l format -d '	Pretty-print images using a Go template'
complete -c docker-image-ls -s h -l help -d '	help for ls'
complete -c docker-image-ls -l no-trunc -d '	Don\'t truncate output'
complete -c docker-image-ls -s q -l quiet -d '	Only show image IDs SEE ALSO'

