# dracut
# Autogenerated from man page /usr/share/man/man8/dracut.8.bz2
complete -c dracut -l kver -d 'set the kernel version'
complete -c dracut -s f -l force -d 'overwrite existing initramfs file'
complete -c dracut -s a -l 'add<list' -d 'add a space-separated list of dracut modules to the default set of modules'
complete -c dracut -l 'force-add<list' -d 'force to add a space-separated list of dracut modules to the default set of m…'
complete -c dracut -s o -l 'omit<list' -d 'omit a space-separated list of dracut modules'
complete -c dracut -s m -l modules -d 'specify a space-separated list of dracut modules to call when building the in…'
complete -c dracut -s d -l 'drivers<list' -d 'specify a space-separated list of kernel modules to exclusively include in th…'
complete -c dracut -l 'add-drivers<list' -d 'specify a space-separated list of kernel modules to add to the initramfs'
complete -c dracut -l force-drivers -d 'See add-drivers above'
complete -c dracut -l 'omit-drivers<list' -d 'specify a space-separated list of kernel modules not to add to the initramfs'
complete -c dracut -l 'filesystems<list' -d 'specify a space-separated list of kernel filesystem modules to exclusively in…'
complete -c dracut -s k -l 'kmoddir<kernel' -d 'specify the directory, where to look for kernel modules'
complete -c dracut -l 'fwdir<dir>++' -d 'specify additional directories, where to look for firmwares'
complete -c dracut -l kernel-cmdline -d 'specify default kernel command line parameters'
complete -c dracut -l kernel-only -d 'only install kernel drivers and firmware files'
complete -c dracut -l no-kernel -d 'do not install kernel drivers and firmware files'
complete -c dracut -l early-microcode -d 'Combine early microcode with ramdisk'
complete -c dracut -l no-early-microcode -d 'Do not combine early microcode with ramdisk'
complete -c dracut -l print-cmdline -d 'print the kernel command line for the current disk layout'
complete -c dracut -l mdadmconf -d 'include local /etc/mdadm. conf'
complete -c dracut -l nomdadmconf -d 'do not include local /etc/mdadm. conf'
complete -c dracut -l lvmconf -d 'include local /etc/lvm/lvm. conf'
complete -c dracut -l nolvmconf -d 'do not include local /etc/lvm/lvm. conf'
complete -c dracut -l fscks -d 'add a space-separated list of fsck tools, in addition to dracut'
complete -c dracut -l nofscks -d 'inhibit installation of any fsck tools'
complete -c dracut -l strip -d 'strip binaries in the initramfs (default)'
complete -c dracut -l nostrip -d 'do not strip binaries in the initramfs'
complete -c dracut -l hardlink -d 'hardlink files in the initramfs (default)'
complete -c dracut -l nohardlink -d 'do not hardlink files in the initramfs'
complete -c dracut -l 'prefix<dir>' -d 'prefix initramfs files with the specified directory'
complete -c dracut -l noprefix -d 'do not prefix initramfs files (default)'
complete -c dracut -s h -l help -d 'display help text and exit'
complete -c dracut -l debug -d 'output debug information of the build process'
complete -c dracut -s v -l verbose -d 'increase verbosity level (default is info(4))'
complete -c dracut -l version -d 'display version and exit'
complete -c dracut -s q -l quiet -d 'decrease verbosity level (default is info(4))'
complete -c dracut -s c -l 'conf<dracut' -d 'specify configuration file to use. sp Default: /etc/dracut. conf'
complete -c dracut -l 'confdir<configuration' -d 'specify configuration directory to use. sp Default: /etc/dracut. conf. d'
complete -c dracut -l 'tmpdir<temporary' -d 'specify temporary directory to use. sp Default: /var/tmp'
complete -c dracut -s r -l sysroot -d 'specify the sysroot directory to collect files from'
complete -c dracut -l 'sshkey<sshkey' -d 'ssh key file used with ssh-client module'
complete -c dracut -l 'logfile<logfile>' -d 'logfile to use; overrides any setting from the configuration files'
complete -c dracut -s l -l local -d 'activates the local mode'
complete -c dracut -s H -l hostonly -d 'Host-Only mode: Install only what is needed for booting the local host instea…'
complete -c dracut -s N -l no-hostonly -d 'Disable Host-Only mode'
complete -c dracut -l persistent-policy -d 'Use <policy> to address disks and partitions'
complete -c dracut -l fstab -d 'Use /etc/fstab instead of /proc/self/mountinfo'
complete -c dracut -l add-fstab -d 'Add entries of <filename> to the initramfs /etc/fstab'
complete -c dracut -l mount -d 'Mount <device> on <mountpoint> with <filesystem type> in the initramfs'
complete -c dracut -l add-device -d 'Bring up <device> in initramfs, <device> should be the device name'
complete -c dracut -s i -l include -d 'include the files in the SOURCE directory into the TARGET directory in the fi…'
complete -c dracut -s I -l install -d 'install the space separated list of files into the initramfs. if n \\{\\ . sp '
complete -c dracut -l install-optional -d 'install the space separated list of files into the initramfs, if they exist'
complete -c dracut -l gzip -d 'Compress the generated initramfs using gzip'
complete -c dracut -l bzip2 -d 'Compress the generated initramfs using bzip2. if n \\{\\ . sp . \\}'
complete -c dracut -l lzma -d 'Compress the generated initramfs using lzma. if n \\{\\ . sp . \\}'
complete -c dracut -l xz -d 'Compress the generated initramfs using xz. if n \\{\\ . sp . \\}'
complete -c dracut -l lzo -d 'Compress the generated initramfs using lzop'
complete -c dracut -l lz4 -d 'Compress the generated initramfs using lz4'
complete -c dracut -l zstd -d 'Compress the generated initramfs using Zstandard'
complete -c dracut -l 'compress<compressor>' -d 'Compress the generated initramfs using the passed compression program'
complete -c dracut -l no-compress -d 'Do not compress the generated initramfs'
complete -c dracut -l reproducible -d 'Create reproducible images'
complete -c dracut -l no-reproducible -d 'Do not create reproducible images'
complete -c dracut -l list-modules -d 'List all available dracut modules'
complete -c dracut -s M -l show-modules -d 'Print included module\'s name to standard output during build'
complete -c dracut -l keep -d 'Keep the initramfs temporary directory for debugging purposes'
complete -c dracut -l printsize -d 'Print out the module install size'
complete -c dracut -s L -l 'stdlog<level>' -d '[0-6] Specify logging level (to standard error)'
complete -c dracut -l regenerate-all -d 'Regenerate all initramfs images at the default location with the kernel versi…'
complete -c dracut -l loginstall -d 'Log all files installed from the host to <DIR>'
complete -c dracut -l uefi -d 'Instead of creating an initramfs image, dracut will create an UEFI executable…'
complete -c dracut -l no-uefi -d 'Disables UEFI mode'
complete -c dracut -l no-machineid -d 'affects the default output filename of --uefi and will discard the <MACHINE_I…'
complete -c dracut -l uefi-stub -d 'Specifies the UEFI stub loader, which will load the attached kernel, initramf…'
complete -c dracut -l uefi-splash-image -d 'Specifies the UEFI stub loader\'s splash image.  Requires bitmap ('
complete -c dracut -l kernel-image -d 'Specifies the kernel image, which to include in the UEFI executable'
complete -c dracut -l add
complete -c dracut -l force-add
complete -c dracut -l omit
complete -c dracut -l drivers
complete -c dracut -l add-drivers
complete -c dracut -l omit-drivers
complete -c dracut -l filesystems
complete -c dracut -l kmoddir
complete -c dracut -l fwdir
complete -c dracut -l prefix
complete -c dracut -l conf
complete -c dracut -l confdir
complete -c dracut -l tmpdir
complete -c dracut -l sshkey
complete -c dracut -l logfile
complete -c dracut -l hostonly-cmdline
complete -c dracut -l no-hostonly-cmdline
complete -c dracut -l no-hostonly-default-device
complete -c dracut -l hostonly-i18n
complete -c dracut -l no-hostonly-i18n
complete -c dracut -l compress
complete -c dracut -l profile
complete -c dracut -l ro-mnt
complete -c dracut -l stdlog

