# dracut-catimages
# Autogenerated from man page /usr/share/man/man8/dracut-catimages.8.bz2
complete -c dracut-catimages -s f -l force -d 'overwrite existing initramfs file'
complete -c dracut-catimages -s i -l imagedir -d 'Directory with additional images to add (default: /boot/dracut/)'
complete -c dracut-catimages -s o -l overlaydir -d 'Overlay directory, which contains additional files that will be used to creat…'
complete -c dracut-catimages -l nooverlay -d 'Do not use the overlay directory'
complete -c dracut-catimages -l noimagedir -d 'Do not use the additional image directory'
complete -c dracut-catimages -s h -l help -d 'display help text and exit'
complete -c dracut-catimages -l debug -d 'output debug information of the build process'
complete -c dracut-catimages -s v -l verbose -d 'verbose output during the build process'

