# dumpelf
# Autogenerated from man page /usr/share/man/man1/dumpelf.1.bz2
complete -c dumpelf -s h -l help -d 'Show condensed usage and exit'
complete -c dumpelf -s V -l version -d 'Print version and exit'
complete -c dumpelf -s v -l verbose -d 'Be verbose (can be used more than once)'

