# ebuild
# Autogenerated from man page /usr/share/man/man1/ebuild.1.bz2
complete -c ebuild -l debug -d 'Run bash with the -x option, causing it to output verbose debugging informati…'
complete -c ebuild -l color -d 'Enable or disable color output.   This option will override NOCOLOR (see make'
complete -c ebuild -l force -d 'When used together with the digest or manifest command, this option forces re…'
complete -c ebuild -l ignore-default-opts -d 'Do not use the EBUILD_DEFAULT_OPTS environment variable'

