# ecpg
# Autogenerated from man page /usr/share/man/man1/ecpg.1.bz2
complete -c ecpg -s c -d 'Automatically generate certain C code from SQL code'
complete -c ecpg -s C -d 'Set a compatibility mode.  mode can be INFORMIX, INFORMIX_SE, or ORACLE'
complete -c ecpg -s D -d 'Define a C preprocessor symbol'
complete -c ecpg -s h -d 'Process header files'
complete -c ecpg -s i -d 'Parse system include files as well'
complete -c ecpg -s I -d 'Specify an additional include path, used to find files included via EXEC SQL …'
complete -c ecpg -s o -d 'Specifies that ecpg should write all its output to the given filename'
complete -c ecpg -s t -d 'Turn on autocommit of transactions'
complete -c ecpg -s v -d 'Print additional information including the version and the "include" path'
complete -c ecpg -l version -d 'Print the ecpg version and exit'
complete -c ecpg -o '?
.br
--help' -d 'Show help about ecpg command line arguments, and exit'
complete -c ecpg -s r
complete -c ecpg -s '?'
complete -c ecpg -l help
complete -c ecpg -o I/usr/local/pgsql/include
complete -c ecpg -o L/usr/local/pgsql/lib -o lecpg

