# elogind
# Autogenerated from man page /usr/share/man/man8/elogind.8.bz2
complete -c elogind -s D -l daemon -d 'Daemonize elogind by double-forking into background'
complete -c elogind -s h -l help -d 'Show the help text and exit'

