# emaint
# Autogenerated from man page /usr/share/man/man1/emaint.1.bz2
complete -c emaint -s C -l clean -d 'Cleans the logs from PORTAGE_LOGDIR'
complete -c emaint -s p -l pretend -d 'Sets pretend mode (same as -c, --check) for use with the -C, --clean OPTION'
complete -c emaint -s c -l check -d 'Check for any problems that may exist'
complete -c emaint -s f -l fix -d 'Fix any problems that may exist.  OPTIONS logs command only'
complete -c emaint -s t -l time -d 'Changes the minimum age NUM (in days) of the logs to be listed or deleted'
complete -c emaint -s y -l yes -d 'Do not prompt for emerge invocations.  OPTIONS sync command only'
complete -c emaint -s a -l auto -d 'Sync repositories which have their auto-sync setting set yes, true'
complete -c emaint -s A -l allrepos -d 'Sync all repositories which have a sync-uri specified'
complete -c emaint -s r -l repo -d 'Sync the repository specified'
complete -c emaint -l sync-submodule -d 'Restrict sync to the specified submodule(s)'

