# etc-update
# Autogenerated from man page /usr/share/man/man1/etc-update.1.bz2
complete -c etc-update -s d -l debug -d 'Run with shell tracing enabled'
complete -c etc-update -s h -l help -d 'Surprisingly, show the help output'
complete -c etc-update -s p -l preen -d 'Automerge trivial changes only and quit'
complete -c etc-update -s v -l verbose -d 'Show settings and important decision info while running'

