# eventlogadm
# Autogenerated from man page /usr/share/man/man8/eventlogadm.8.bz2
complete -c eventlogadm -s s -d 'The -s option causes eventlogadm to load the configuration file given as FILE…'
complete -c eventlogadm -s d -d 'The -d option causes eventlogadm to emit debugging information'
complete -c eventlogadm -s o -d 'The -o addsource option creates a new event log source'
complete -c eventlogadm -s h -d 'Print usage information'

