# filezilla
# Autogenerated from man page /usr/share/man/man1/filezilla.1.bz2
complete -c filezilla -s c -l site -d 'Connect to the given site from the Site Manager'
complete -c filezilla -s a -l local -d 'Sets the local site to the given path'
complete -c filezilla -s h -l help -d 'Displays a help dialog listing these commandline options'
complete -c filezilla -s l -l logontype -d 'Set a special logontype, can only be used in combination with a FTP URL as ar…'
complete -c filezilla -s s -l sitemanager -d 'Start with Site Manager opened'
complete -c filezilla -s v -l version -d 'Display version number of FileZilla.  ENVIRONMENT'

