# flameshot
# Autogenerated from man page /usr/share/man/man1/flameshot.1.bz2
complete -c flameshot -s a -l autostart
complete -c flameshot -l check
complete -c flameshot -s c -l clipboard
complete -c flameshot -s d -l delay
complete -c flameshot -s f -l filename
complete -c flameshot -s g -l print-geometry
complete -c flameshot -s h -l help
complete -c flameshot -s k -l contrastcolor
complete -c flameshot -s m -l maincolor
complete -c flameshot -s n -l number
complete -c flameshot -s p -l path
complete -c flameshot -l pin
complete -c flameshot -s r -l raw
complete -c flameshot -l region
complete -c flameshot -s s -l accept-on-select
complete -c flameshot -l showhelp
complete -c flameshot -s t -l trayicon
complete -c flameshot -s u -l upload

