# fontimage
# Autogenerated from man page /usr/share/man/man1/fontimage.1.bz2
complete -c fontimage -l help -d 'Provide a description with a list of the available options'
complete -c fontimage -l width -d 'Specifies the width of the output image'
complete -c fontimage -l height -d 'Specifies the height of the output image'
complete -c fontimage -l pixelsize -d 'Specifies the pixelsize used to display the text'
complete -c fontimage -l text -d 'Specifies a line of text to be displayed.  The string must be in UTF-8'
complete -c fontimage -s o -d 'Specifies the output filename for the image'
complete -c fontimage -l usage -d 'Display the usage description'
complete -c fontimage -l version -d 'Display the current version SEE ALSO fontforge (1)'

