# fsadm
# Autogenerated from man page /usr/share/man/man8/fsadm.8.bz2
complete -c fsadm -s e -l ext-offline
complete -c fsadm -s l -l lvresize
complete -c fsadm -s f -l force
complete -c fsadm -s h -l help
complete -c fsadm -s n -l dry-run
complete -c fsadm -s v -l verbose
complete -c fsadm -s y -l yes
complete -c fsadm -s c -l cryptresize

