# gentest
# Autogenerated from man page /usr/share/man/man1/gentest.1.bz2
complete -c gentest -s U -d 'Specify the user and password to use when logging on on the shares'
complete -c gentest -s s -d 'Seed the random number generator with the specified value'
complete -c gentest -s o -d 'Set the number of operations to perform'
complete -c gentest -s a -d 'Print the operations that are performed'
complete -c gentest -s A -d 'Backtrack to find minimal number of operations required to make the response …'
complete -c gentest -s i -d 'Specify a file containing the names of fields that have to be ignored (such a…'
complete -c gentest -s O -d 'Enable oplocks'
complete -c gentest -s S -d 'Set preset seeds file.  The default is gentest_seeds. dat'
complete -c gentest -s L -d 'Use preset seeds'
complete -c gentest -s F -d 'Fast reconnect (just close files)'
complete -c gentest -s C -d 'Continuous analysis mode'
complete -c gentest -s X -d 'Analyse even when the test succeeded'

