# glsa-check
# Autogenerated from man page /usr/share/man/man1/glsa-check.1.bz2
complete -c glsa-check -s l -l list
complete -c glsa-check -s d -l dump -l print
complete -c glsa-check -s t -l test
complete -c glsa-check -s p -l pretend
complete -c glsa-check -s f -l fix
complete -c glsa-check -s i -l inject
complete -c glsa-check -s n -l nocolor
complete -c glsa-check -s h -l help
complete -c glsa-check -s V -l version
complete -c glsa-check -s v -l verbose
complete -c glsa-check -s c -l cve
complete -c glsa-check -s q -l quiet
complete -c glsa-check -s m -l mail
complete -c glsa-check -s r -l reverse -d 'EXAMPLES glsa-check -t all Test the system against all GLSAs in the GLSA repo…'

