# gsf
# Autogenerated from man page /usr/share/man/man1/gsf.1.bz2
complete -c gsf -s '?' -l help -d 'Show help options'
complete -c gsf -s v -l version -d 'Display gsf\'s version  . SS "Subcommands"'

