# haveged
# Autogenerated from man page /usr/share/man/man8/haveged.8.bz2
complete -c haveged -s b -l buffer -d 'Set collection buffer size to nnn KW.  Default is 128KW (or 512KB)'
complete -c haveged -s c -l command -d 'Switch to command mode and send a command to an already running  haveged proc…'
complete -c haveged -s d -l data -d 'Set data cache size to nnn KB.  Default is 16 or as determined dynamically'
complete -c haveged -s f -l file -d 'Set output file path for non-daemon use'
complete -c haveged -s F -l Foreground -d 'Run daemon in foreground.  Do not fork and detach'
complete -c haveged -s e -l once -d 'Provide entropy to the kernel once and quit immediatelly'
complete -c haveged -s i -l inst -d 'Set instruction cache size to nnn KB'
complete -c haveged -s n -l number -d 'Set number of bytes written to the output file'
complete -c haveged -s o -l onlinetest -d 'Specify online tests to run'
complete -c haveged -s p -l pidfile -d 'Set file path for the daemon pid file.  Default is "/var/run/haveged. pid",'
complete -c haveged -s r -l run -d 'Set run level for daemon interface:  n = 0 Run as daemon - must be root'
complete -c haveged -s v -l verbose -d 'Set diagnostic bitmap as sum of following options:  1=Show build/tuning summa…'
complete -c haveged -s w -l write -d 'Set write_wakeup_threshold of daemon interface to nnn bits'
complete -c haveged -s V -l version -d 'Print version information and exit'
complete -c haveged -s '?' -l help -d 'This summary of program options'

