# hostname
# Autogenerated from man page /usr/share/man/man1/hostname.1.bz2
complete -c hostname -s a -l alias -d 'Display the alias name of the host (if used)'
complete -c hostname -s d -l domain -d 'Display the name of the DNS domain (this is the FQDN without the segment up t…'
complete -c hostname -s F -l file -d 'Read the new host name from the specified file'
complete -c hostname -s f -l fqdn -l long -d 'Display the FQDN (Fully Qualified Domain Name)'
complete -c hostname -s h -l help -d 'Print a usage message and exit'
complete -c hostname -s i -l ip-address -d 'Display the IP address(es) of the host'
complete -c hostname -s n -l node -d 'Display the DECnet node name'
complete -c hostname -s s -l short -d 'Display the short host name.  This is the host name cut at the first dot'
complete -c hostname -s V -l version -d 'Print version information on standard output and exit successfully'
complete -c hostname -s v -l verbose -d 'Be verbose and tell what\'s going on'
complete -c hostname -s y -l yp -l nis -d 'Display the NIS domain name.  If a parameter is given (or '

