# idevicerestore
# Autogenerated from man page /usr/local/share/man/man1/idevicerestore.1
complete -c idevicerestore -s i -l ecid -d 'target specific device by its hexadecimal ECID e. g'
complete -c idevicerestore -s u -l udid -d 'target specific device by its 40-digit device UDID'
complete -c idevicerestore -s e -l erase -d 'perform a full restore, erasing all data (defaults to update)'
complete -c idevicerestore -s c -l custom -d 'restore with a custom firmware'
complete -c idevicerestore -s l -l latest -d 'use latest available firmware (with download on demand)'
complete -c idevicerestore -s s -l cydia -d 'use Cydia\'s signature service instead of Apple\'s'
complete -c idevicerestore -s x -l exclude -d 'exclude nor/baseband upgrade'
complete -c idevicerestore -s t -l shsh -d 'fetch TSS record and save to . shsh file, then exit'
complete -c idevicerestore -s p -l pwn -d 'put device in pwned DFU mode and exit (limera1n devices only)'
complete -c idevicerestore -s n -l no-action -d 'do not perform any restore action'
complete -c idevicerestore -s C -l cache-path -d 'use specified directory for caching extracted or other reused files'
complete -c idevicerestore -s d -l debug -d 'enable communication debugging'
complete -c idevicerestore -s h -l help -d 'prints usage information'
complete -c idevicerestore -s v -l version -d 'prints version information'

