# ideviceenterrecovery
# Autogenerated from man page /usr/share/man/man1/ideviceenterrecovery.1.bz2
complete -c ideviceenterrecovery -s d -l debug -d 'enable communication debugging'
complete -c ideviceenterrecovery -s h -l help -d 'prints usage information'
complete -c ideviceenterrecovery -s v -l version -d 'prints version information'

