# idevicepair
# Autogenerated from man page /usr/share/man/man1/idevicepair.1.bz2
complete -c idevicepair -s u -l udid -d 'target specific device by UDID'
complete -c idevicepair -s d -l debug -d 'enable communication debugging'
complete -c idevicepair -s h -l help -d 'prints usage information'
complete -c idevicepair -s v -l version -d 'prints version information'

