# ifnames-2
# Autogenerated from man page /usr/share/man/man1/ifnames-2.71.1.bz2
complete -c ifnames-2 -s h -l help -d 'print this help, then exit'
complete -c ifnames-2 -s V -l version -d 'print version number, then exit AUTHOR Written by David J'

