# imake
# Autogenerated from man page /usr/share/man/man1/imake.1.bz2
complete -c imake -o Ddefine -d 'This option is passed directly to cpp'
complete -c imake -o Idirectory -d 'This option is passed directly to cpp'
complete -c imake -o Udefine -d 'This option is passed directly to cpp'
complete -c imake -o Ttemplate -d 'This option specifies the name of the master template file (which is usually …'
complete -c imake -s f -d 'This option specifies the name of the per-directory input file'
complete -c imake -s C -d 'This option specifies the name of the '
complete -c imake -s s -d 'This option specifies the name of the make description file to be generated b…'
complete -c imake -s e -d 'This option indicates the imake should execute the generated Makefile'
complete -c imake -s v -d 'This option indicates that imake should print the cpp command line that it is…'
complete -c imake -s T

