# init
# Autogenerated from man page /usr/share/man/man8/init.8.bz2
complete -c init -s s -d 'Single user mode boot'
complete -c init -s b -d 'Boot directly into a single user shell without running any other startup scri…'
complete -c init -s a -d 'The LILO boot loader adds the word "auto" to the command line if it booted th…'
complete -c init -s z -d 'The argument to -z is ignored'
complete -c init -l version -d 'This argument, when used on its own, displays the current version of init to …'

