# irb27
# Autogenerated from man page /usr/share/man/man1/irb27.1.bz2
complete -c irb27 -l version -d 'Prints the version of irb27.  Pp'
complete -c irb27 -s E
complete -c irb27 -l encoding -d 'Same as `ruby -E\' '
complete -c irb27 -s I -d 'Same as `ruby -I\' .  Specifies $LOAD_PATH directory Pp'
complete -c irb27 -s U -d 'Same as `ruby -U\' '
complete -c irb27 -s d -d 'Same as `ruby -d\' .  Sets $DEBUG to true.  Pp'
complete -c irb27 -s f -d 'Suppresses read of ~/. irbrc.  Pp'
complete -c irb27 -s w -d 'Same as `ruby -w\' .  Pp Pp'
complete -c irb27 -s W -d 'Same as `ruby -W\' .  Pp'
complete -c irb27 -s h
complete -c irb27 -l help -d 'Prints a summary of the options.  Pp'
complete -c irb27 -s r -d 'Same as `ruby -r\'.  Causes irb to load the library using require.  Pp'
complete -c irb27 -l inspect -d 'Uses `inspect\' for output (default except for bc mode) Pp'
complete -c irb27 -l noinspect -d 'Doesn\'t use inspect for output Pp'
complete -c irb27 -l multiline -d 'Uses multiline editor module.  Pp'
complete -c irb27 -l nomultiline -d 'Doesn\'t use multiline editor module.  Pp'
complete -c irb27 -l singleline -d 'Uses singleline editor module.  Pp'
complete -c irb27 -l nosingleline -d 'Doesn\'t use singleline editor module.  Pp Pp'
complete -c irb27 -l echo -d 'Show result(default).  Pp'
complete -c irb27 -l noecho -d 'Don\'t show result.  Pp Pp'
complete -c irb27 -l colorize -d 'Use colorization.  Pp'
complete -c irb27 -l nocolorize -d 'Don\'t use colorization.  Pp Pp'
complete -c irb27 -l verbose -d 'Show details.  Pp'
complete -c irb27 -l noverbose -d 'Don\'t show details.  Pp'
complete -c irb27 -l prompt
complete -c irb27 -l prompt-mode -d 'Switch prompt mode'
complete -c irb27 -l inf-ruby-mode -d 'Uses prompt appropriate for inf-ruby-mode on emacs'
complete -c irb27 -l simple-prompt -d 'Makes prompts simple.  Pp'
complete -c irb27 -l noprompt -d 'No prompt mode.  Pp'
complete -c irb27 -l tracer -d 'Displays trace for each execution of commands.  Pp'
complete -c irb27 -l back-trace-limit -d 'Displays backtrace top n and tail n Ns.  The default value is 16'

