# irb26
# Autogenerated from man page /usr/share/man/man1/irb26.1.bz2
complete -c irb26 -l version -d 'Prints the version of irb26.  Pp'
complete -c irb26 -s E
complete -c irb26 -l encoding -d 'Same as `ruby -E\' '
complete -c irb26 -s I -d 'Same as `ruby -I\' .  Specifies $LOAD_PATH directory Pp'
complete -c irb26 -s U -d 'Same as `ruby -U\' '
complete -c irb26 -s d -d 'Same as `ruby -d\' .  Sets $DEBUG to true.  Pp'
complete -c irb26 -s f -d 'Suppresses read of ~/. irbrc.  Pp'
complete -c irb26 -s h
complete -c irb26 -l help -d 'Prints a summary of the options.  Pp'
complete -c irb26 -s r -d 'Same as `ruby -r\'.  Causes irb to load the library using require.  Pp'
complete -c irb26 -l inspect -d 'Uses `inspect\' for output (default except for bc mode) Pp'
complete -c irb26 -l noinspect -d 'Doesn\'t use inspect for output Pp'
complete -c irb26 -l readline -d 'Uses Readline extension module.  Pp'
complete -c irb26 -l noreadline -d 'Doesn\'t use Readline extension module.  Pp'
complete -c irb26 -l prompt
complete -c irb26 -l prompt-mode -d 'Switch prompt mode'
complete -c irb26 -l inf-ruby-mode -d 'Uses prompt appropriate for inf-ruby-mode on emacs.  Suppresses --readline'
complete -c irb26 -l simple-prompt -d 'Makes prompts simple.  Pp'
complete -c irb26 -l noprompt -d 'No prompt mode.  Pp'
complete -c irb26 -l tracer -d 'Displays trace for each execution of commands.  Pp'
complete -c irb26 -l back-trace-limit -d 'Displays backtrace top n and tail n Ns.  The default value is 16.  Pp'
complete -c irb26 -l irb_debug -d 'Sets internal debug level to n (not for popular use) Pp El Pp ENVIRONMENT -ta…'

