# irqtop
# Autogenerated from man page /usr/share/man/man1/irqtop.1.bz2
complete -c irqtop -s o -l output
complete -c irqtop -s d -l delay
complete -c irqtop -s s -l sort
complete -c irqtop -s S -l softirq
complete -c irqtop -s V -l version
complete -c irqtop -s h -l help

