# itstool
# Autogenerated from man page /usr/share/man/man1/itstool.1.bz2
complete -c itstool -s o
complete -c itstool -l out -d 'output PO template to the file OUT. pot'
complete -c itstool -s m
complete -c itstool -l merge -d 'merge from an MO file MOFILE and output translated XML files for source XMLFI…'
complete -c itstool -s l
complete -c itstool -l lang -d 'explicitly set the language code output to XML'
complete -c itstool -s j
complete -c itstool -l join -d 'join translations from MOFILES into a multilingual file based on source XMLFI…'
complete -c itstool -s i
complete -c itstool -l its -d 'load the ITS rules in the file ITS (can specify multiple times)'
complete -c itstool -s n
complete -c itstool -l no-builtins -d 'do not apply the built-in ITS rules that ship with itstool'
complete -c itstool -s s
complete -c itstool -l strict -d 'exit with error when PO files contain broken XML'
complete -c itstool -s d
complete -c itstool -l load-dtd -d 'load external DTDs used by input XML files'
complete -c itstool -s k
complete -c itstool -l keep-entities -d 'keep entity references unexpanded in PO files'
complete -c itstool -s p
complete -c itstool -l param -d 'define ITS parameter NAME to the value VALUE (can specify multiple times) AUT…'

