# jpegexiforient
# Autogenerated from man page /usr/share/man/man1/jpegexiforient.1.bz2
complete -c jpegexiforient -l help -d 'display this help and exit'
complete -c jpegexiforient -l version -d 'output version information and exit'
complete -c jpegexiforient -s n -d 'Do not output the trailing newline'
complete -c jpegexiforient -l ----+-------------+----------- -d '  1   | top         | left side   2   | top         | right side   3   | bott…'
complete -c jpegexiforient -s 1 -s 8 -d 'Set orientation value 1 .  8 AUTHOR  Guido Vollbeding <guido@jpegclub'

