# keygen
# Autogenerated from man page /usr/share/man/man8/keygen.8.bz2
complete -c keygen -s p
complete -c keygen -s q -d 'gethostname() function, normally the DNS name of the host, is used'
complete -c keygen -s T
complete -c keygen -s S
complete -c keygen -s c
complete -c keygen -s b -d 'Set the modulus for generating identity keys to modulus bits'
complete -c keygen -s C -d 'Select the OpenSSL cipher to use for password-protected keys'
complete -c keygen -s d -d 'Enable debugging'
complete -c keygen -s e -d 'Extract the IFF or GQ public parameters from the IFFkey or GQkey keys file pr…'
complete -c keygen -s G -d 'Generate a new encrypted GQ key file for the Guillou-Quisquater (GQ) identity…'
complete -c keygen -s I
complete -c keygen -s V
complete -c keygen -s H -d 'Generate a new encrypted RSA public/private host key file'
complete -c keygen -s i -d 'Set the optional Autokey group name to'
complete -c keygen -s s -d '@ character, is also used in certificate subject and issuer names in the form'
complete -c keygen -s l -d 'Set the lifetime for certificates to'
complete -c keygen -s m -d 'Set the modulus for generating files to modulus bits'
complete -c keygen -s M -d 'Generate a new keys file containing 10 MD5 keys and 10 SHA keys'
complete -c keygen -s P -d 'Generate a new private certificate used by the PC identity scheme'

