# ldbrename
# Autogenerated from man page /usr/share/man/man1/ldbrename.1.bz2
complete -c ldbrename -s h -d 'Show list of available options'
complete -c ldbrename -s H -d 'LDB URL to connect to.  See ldb(3) for details'
complete -c ldbrename -s o -d 'Extra ldb options, such as modules'

