# ldrdf
# Autogenerated from man page /usr/share/man/man1/ldrdf.1.bz2
complete -c ldrdf -s o -d 'Specify an output file.   The default output filename is . RI \' aout. rdx \''
complete -c ldrdf -s v -d 'Increase verbosity level'
complete -c ldrdf -s p -d 'Change alignment value to which multiple segments combigned into a single seg…'

