# lftp
# Autogenerated from man page /usr/share/man/man1/lftp.1.bz2
complete -c lftp -s d -d 'Switch on debugging mode'
complete -c lftp -s e -d 'Execute given commands and don\'t exit'
complete -c lftp -s p -d 'Use the given port to connect'
complete -c lftp -s u -d 'Use the given username and password to connect'
complete -c lftp -l norc -d 'Don\'t execute rc files from the home directory'
complete -c lftp -l rcfile -d 'Execute commands from the file.  May be specified multiple times'
complete -c lftp -s f -d 'Execute commands in the file and exit'
complete -c lftp -s c -d 'Execute the given commands and exit'
complete -c lftp -s a
complete -c lftp -s k -l 'kilobytes	T' -d 'like --block-size=1024 T}'
complete -c lftp -s l -l 'long	T' -d 'use a long listing format T}'
complete -c lftp -s q -l 'quiet	don\'t'
complete -c lftp -s s -l 'size	print' -d '	--filesize	T{ if printing size, only print size for files T}'
complete -c lftp -s i -l 'nocase	T' -d 'case-insensitive pattern matching T}'
complete -c lftp -s I -l 'sortnocase	T' -d 'sort names case-insensitively T}'
complete -c lftp -s D -l 'dirsfirst	T' -d 'list directories first T} 	--sort=OPT	T{ "name", "size", "date" T}'
complete -c lftp -o 'S		sort' -d '	--user, --group, 	--perms, --date, 	--linkcount, --links	show individual fie…'
complete -c lftp -s H -l 'si	likewise'
complete -c lftp -l 'kilobytes	like' -l block-size
complete -c lftp -s m -l 'megabytes	like'
complete -c lftp -s S -l 'separate-dirs	do'
complete -c lftp -l 'summarize	display' -d '	--exclude=PAT	exclude files that match PAT echo  [ -n ] string'
complete -c lftp -s r
complete -c lftp -o 'c	Clear'
complete -c lftp -o 'l	List' -d 'jobs [ OPTS ] [ job_no.  ]'
complete -c lftp -o 'd	T' -d 'create directories the same as file names and get the files into them instead…'
complete -c lftp -o 'E	delete'
complete -c lftp -o 'e	delete'
complete -c lftp -o 'a	use'
complete -c lftp -s P
complete -c lftp -s O -d 'specifies base directory or URL where files should be placed T} mirror [ OPTS…'
complete -c lftp -s F -l directory -d 'mirror a single directory or globbed group (e. g.  /path/to/dir*) T}'
complete -c lftp -l target-directory -d 'target base path or URL T}'
complete -c lftp -s v -l verbose -d 'verbose operation T} 	--log=FILE	T{ write lftp commands being executed to FIL…'
complete -c lftp -o 'a		T' -d 'same as --allow-chown --allow-suid --no-umask T} RX is an extended regular ex…'
complete -c lftp -o vvv
complete -c lftp -l only-newer -d 'only newer files even if size is different'
complete -c lftp -l upload-older -d 'the target side is remote)'
complete -c lftp -l depth-first -l no-empty-dirs
complete -c lftp -s n -d 'set maximum number of connections (default is taken from pget:default-n setti…'
complete -c lftp -o 'E	T' -d 'delete source files after successful transfer (dangerous) T}'
complete -c lftp -l delete
complete -c lftp -l move
complete -c lftp -o 'v	Be'
complete -c lftp -o 'Q	T' -d 'Output in a format that can be used to re-queue.  Useful with --delete'
complete -c lftp -l 'only-new	T' -d 'stop if the metadata is known already or the torrent is complete.  T}'
complete -c lftp -l 'only-incomplete	T' -d 'stop if the torrent is already complete.  T}'
complete -c lftp -l dht-bootstrap -d 'bootstrap DHT by sending a query to specified node'
complete -c lftp -l 'share	T' -d 'share specified file or directory using BitTorrent protocol'

