# llvm-as
# Autogenerated from man page /usr/lib/llvm/13/share/man/man1/llvm-as.1.bz2
complete -c llvm-as -s f -d 'Enable binary output on terminals'
complete -c llvm-as -o help -d 'Print a summary of command line options'
complete -c llvm-as -s o -d 'Specify the output file name'

