# llvm-stress
# Autogenerated from man page /usr/lib/llvm/13/share/man/man1/llvm-stress.1.bz2
complete -c llvm-stress -s o -d 'Specify the output filename'
complete -c llvm-stress -o size -d 'Specify the size of the generated . ll file'
complete -c llvm-stress -o seed -d 'Specify the seed to be used for the randomly generated instructions'

