# locale-gen
# Autogenerated from man page /usr/share/man/man8/locale-gen.8.bz2
complete -c locale-gen -s a -l ask -d 'Ask before generating each locale'
complete -c locale-gen -s A -l all -d 'Generate all possible locales'
complete -c locale-gen -s c -l config -d 'Use specified config file rather than default /etc/locale. gen'
complete -c locale-gen -s d -l destdir -d 'Look for locale definitions and store generated locale data in the specified …'
complete -c locale-gen -s G -l generate -d 'Only generate the specified locale (implies --keep --update); format of local…'
complete -c locale-gen -s h -l help -d 'Show the help output (imagine that)'
complete -c locale-gen -s j -l jobs -d 'Generate the specified number of locales in parallel'
complete -c locale-gen -s k -l keep -d 'Keep all existing locales even if they are not in the config file'
complete -c locale-gen -s l -l list -d 'List all the locales that we think should exist according to the config'
complete -c locale-gen -s q -l quiet -d 'Only spit out errors'
complete -c locale-gen -s u -l update -d 'Only generate locales that do not already exist (normally existing locales ar…'
complete -c locale-gen -s V -l version -d 'Report the program version'

