# locktest
# Autogenerated from man page /usr/share/man/man1/locktest.1.bz2
complete -c locktest -s U -d 'Specify the user and password to use when logging on on the shares'
complete -c locktest -s s -d 'Seed the random number generator with the specified value'
complete -c locktest -s o -d 'Set the number of operations to perform'
complete -c locktest -s a -d 'Print the operations that are performed'
complete -c locktest -s A -d 'Backtrack to find minimal number of operations required to make the response …'
complete -c locktest -s O -d 'Enable oplocks'
complete -c locktest -s u -d 'Hide unlock fails'
complete -c locktest -s E -d 'enable exact error code checking'
complete -c locktest -s Z -d 'enable the zero/zero lock'
complete -c locktest -s R -d 'set lock range'
complete -c locktest -s B -d 'set lock base'
complete -c locktest -s M -d 'set min lock length'
complete -c locktest -s k -d 'Use kerberos'

