# lsb-release
# Autogenerated from man page /usr/share/man/man1/lsb-release.1.bz2
complete -c lsb-release -s v -l version -d 'Display the version of the LSB specification against which the distribution i…'
complete -c lsb-release -s i -l id -d 'Display the string id of the distributor'
complete -c lsb-release -s d -l description -d 'Display the single line text description of the distribution'
complete -c lsb-release -s r -l release -d 'Display the release number of the distribution'
complete -c lsb-release -s c -l codename -d 'Display the codename according to the distribution release'
complete -c lsb-release -s a -l all -d 'Display all of the above information'
complete -c lsb-release -s s -l short -d 'Use short output format for information requested by other options (or versio…'
complete -c lsb-release -s h -l help -d 'Display this message.  FILES'

