# lvmconf
# Autogenerated from man page /usr/share/man/man8/lvmconf.8.bz2
complete -c lvmconf -l disable-cluster -d 'Set locking_type to the default non-clustered type'
complete -c lvmconf -l enable-cluster -d 'Set locking_type to the default clustered type on this system'
complete -c lvmconf -l disable-halvm -d 'Set locking_type to the default non-clustered type'
complete -c lvmconf -l enable-halvm -d 'Set locking_type suitable for HA LVM use'
complete -c lvmconf -l file -d 'Apply the changes to configfile instead of the default /etc/lvm/lvm. conf'
complete -c lvmconf -l lockinglib -d 'Set external locking_library locking library to load if an external locking t…'
complete -c lvmconf -l lockinglibdir
complete -c lvmconf -l services -d 'In addition to setting the lvm configuration, also enable or disable related …'
complete -c lvmconf -l mirrorservice -d 'Also enable or disable optional cmirrord service when handling services (appl…'
complete -c lvmconf -l startstopservices -d 'In addition to enabling or disabling related services, start or stop them imm…'

