# lvmetad
# Autogenerated from man page /usr/share/man/man8/lvmetad.8.bz2
complete -c lvmetad -s f -d 'Don\'t fork, but run in the foreground'
complete -c lvmetad -s h -s '?' -d 'Show help information'
complete -c lvmetad -s l -d 'Specify the levels of log messages to generate as a comma separated list'
complete -c lvmetad -s p -d 'Path to the pidfile.  This overrides both the built-in default (/run/lvmetad'
complete -c lvmetad -s s -d 'Path to the socket file'
complete -c lvmetad -s t -d 'The daemon may shutdown after being idle for the given time (in seconds)'
complete -c lvmetad -s V -d 'Display the version of lvmetad daemon.  ENVIRONMENT VARIABLES'

