# make_method
# Autogenerated from man page /usr/share/man/man1/make_method.1.bz2
complete -c make_method -l help -d 'Prints a short summary of the options'
complete -c make_method -l name -d 'Specifies the published name of the method being encoded'
complete -c make_method -l namespace -d 'Specifies a namespace that the code of the method will be evaluated in, when …'
complete -c make_method -l type -d 'Specify the type for the resulting file'
complete -c make_method -l version -d 'Specify a version stamp for the code routine'
complete -c make_method -l hidden -d 'If this is passe, the resulting file will include a tag that tells the server…'
complete -c make_method -l signature -l signature -d 'Specify one or more signatures for the method'
complete -c make_method -l helptext -d 'Specify the help text for the method as a simple string on the command line'
complete -c make_method -l helpfile -d 'Read the help text for the method from the file specified'
complete -c make_method -l code -d 'Read the actual code for the routine from the file specified'
complete -c make_method -l output -d 'Write the resulting \\s-1XML\\s0 representation to the specified file'
complete -c make_method -l base -d 'This is a special, \\*(L"all-in-one\\*(R" option'

