# mapropos
# Autogenerated from man page /usr/share/man/man1/mapropos.1.bz2
complete -c mapropos -s a -d 'Instead of showing only the title lines, show the complete manual pages, just…'
complete -c mapropos -s C -d 'Specify an alternative configuration file in man. conf 5 format'
complete -c mapropos -s f -d 'Search for all words in expression in manual page names only'
complete -c mapropos -s k -d 'Support the full expression syntax.  It is the default for mapropos'
complete -c mapropos -s M -d 'Use the colon-separated path instead of the default list of paths searched fo…'
complete -c mapropos -s m -d 'Prepend the colon-separated paths to the list of paths searched for makewhati…'
complete -c mapropos -s O -d 'Show the values associated with the key outkey instead of the manual descript…'
complete -c mapropos -s S -d 'Restrict the search to pages for the specified machine 1 architecture'
complete -c mapropos -s s -d 'Restrict the search to the specified section of the manual'
complete -c mapropos -s i -d 'If term is a regular expression, it is evaluated case-insensitively'

