# masktest
# Autogenerated from man page /usr/share/man/man1/masktest.1.bz2
complete -c masktest -s U -d 'Specify the user and password to use when logging on on the shares'
complete -c masktest -s s -d 'Seed the random number generator with the specified value'
complete -c masktest -s n -d 'Set the number of operations to perform'
complete -c masktest -s a -d 'Print the operations that are performed'
complete -c masktest -s M -d 'Maximum protocol to use'
complete -c masktest -s f -d 'Specify characters that can be used when generating file names'
complete -c masktest -s E -d 'Abort when difference in behaviour is found'
complete -c masktest -s m -d 'Specify characters used for wildcards'
complete -c masktest -s v -d 'Be verbose'

