# metalog
# Autogenerated from man page /usr/share/man/man8/metalog.8.bz2
complete -c metalog -s a -l async -d 'Improve performance by using buffers (bug log files won\'t get updated in real…'
complete -c metalog -s B -l daemonize -d 'Have the server start in background (daemonization)'
complete -c metalog -s c -l consolelevel -d 'Set the console log level (Linux only)'
complete -c metalog -s C -l configfile -d 'Use an alternate configuration file'
complete -c metalog -s g -l group -d 'Change the GID of the metalog process'
complete -c metalog -s h -l help -d 'Output help information and exit'
complete -c metalog -s N -l no-kernel -d 'Do not attempt to log messages from the kernel'
complete -c metalog -s P -l pidfile -d 'Use an alternate file to store the process number'
complete -c metalog -s s -l sync -l synchronous -d 'Start in synchronous mode, with no bufferization'
complete -c metalog -s v -l verbose -d 'Run in verbose mode (useful for debugging behavior)'

