# miniunzip
# Autogenerated from man page /usr/share/man/man1/miniunzip.1.bz2
complete -c miniunzip -s l -l v -d 'List the files in the archive without extracting them'
complete -c miniunzip -s o -d 'Overwrite files without prompting for confirmation'
complete -c miniunzip -s x -d 'Extract files (default)'
complete -c miniunzip -s d -d 'these must be supplied before any other arguments and are:'

