# mkbitmap
# Autogenerated from man page /usr/share/man/man1/mkbitmap.1.bz2
complete -c mkbitmap -s h -l help -d 'print help message and exit'
complete -c mkbitmap -s v -l version -d 'print version info and exit'
complete -c mkbitmap -s l -l license -d 'print license info and exit. PD . SS Input/output options:'
complete -c mkbitmap -s o -l output -d 'write output to this file'
complete -c mkbitmap -s x -l nodefaults -d 'Turn off default options'
complete -c mkbitmap -s i -l invert -d 'Invert the input image'
complete -c mkbitmap -s f -l filter -d 'Apply a highpass filter to the image'
complete -c mkbitmap -s n -l nofilter -d 'Turn off highpass filtering'
complete -c mkbitmap -s b -l blur -d 'Blur the image'
complete -c mkbitmap -s s -l scale -d 'Scale the image by an integer factor n>0'
complete -c mkbitmap -s 1 -l linear -d 'Use linear interpolation when scaling to a higher resolution'
complete -c mkbitmap -s 3 -l cubic -d 'Use cubic interpolation when scaling to a higher resolution'
complete -c mkbitmap -s t -l threshold -d 'Set the threshold grey value for bilevel conversion'
complete -c mkbitmap -s g -l grey -d 'Disable bilevel conversion'

