# mman
# Autogenerated from man page /usr/share/man/man1/mman.1.bz2
complete -c mman -s a -d 'Display all matching manual pages'
complete -c mman -s C -d 'Use the specified file instead of the default configuration file'
complete -c mman -s c -d 'Copy the manual page to the standard output instead of using less 1 to pagina…'
complete -c mman -s f -d 'A synonym for whatis 1'
complete -c mman -s h -d 'Display only the SYNOPSIS lines of the requested manual pages'
complete -c mman -s k -d 'A synonym for apropos 1'
complete -c mman -s l -d 'A synonym for mandoc 1.  The name arguments are interpreted as filenames'
complete -c mman -s M -d 'Override the list of directories to search for manual pages'
complete -c mman -s m -d 'Augment the list of directories to search for manual pages'
complete -c mman -s S -d 'Only show pages for the specified machine 1 architecture'
complete -c mman -s w -d 'List the pathnames of all matching manual pages instead of displaying any of …'

