# mono-configuration-crypto
# Autogenerated from man page /usr/share/man/man1/mono-configuration-crypto.1.bz2
complete -c mono-configuration-crypto -s h -s '?' -l help -d 'Show usage information'
complete -c mono-configuration-crypto -s v -l verbose -d 'Show verbose information (including exception stacktraces)'
complete -c mono-configuration-crypto -s m -l machine -l global -d 'Use machine (global) store for all the key actions'
complete -c mono-configuration-crypto -s u -l user -l local -d 'Use local (user) store for all the key actions'
complete -c mono-configuration-crypto -s l -l list -d 'List all the key container names in the store'
complete -c mono-configuration-crypto -s c -l create -d 'Creates an RSA public/private key pair'
complete -c mono-configuration-crypto -s i -l import -d 'Imports key to a container'
complete -c mono-configuration-crypto -s x -l export -d 'Exports key from a container'
complete -c mono-configuration-crypto -s r -l remove -d 'Remove a container.  Physically removes the container file from disk'
complete -c mono-configuration-crypto -s f -l file -d 'File name for import or export operations'
complete -c mono-configuration-crypto -o cf -l config-file -d 'Config file name'
complete -c mono-configuration-crypto -s n -l name -d 'Container name'
complete -c mono-configuration-crypto -s s -l size -d 'Key size'
complete -c mono-configuration-crypto -s p -l path -d 'Application physical path'
complete -c mono-configuration-crypto -s d -l dec -l decrypt -d 'Decrypt configuration section'
complete -c mono-configuration-crypto -s e -l enc -l encrypt -d 'Encrypt configuration section'

