# msoelim
# Autogenerated from man page /usr/share/man/man1/msoelim.1.bz2
complete -c msoelim -s C -d 'Recognise . so when not followed by a space character'
complete -c msoelim -s r -d 'Compatibility with GNU groff\'s msoelim soelim (does nothing)'
complete -c msoelim -s t -d 'Compatibility with GNU groff\'s msoelim soelim (does nothing)'
complete -c msoelim -s v -d 'Compatibility with GNU groff\'s msoelim soelim (does nothing)'
complete -c msoelim -s I -d 'This option specify directories where msoelim searches for files (both those …'

