# mupdf
# Autogenerated from man page /usr/share/man/man1/mupdf.1.bz2
complete -c mupdf -s p -d 'Uses the given password to open an encrypted PDF file'
complete -c mupdf -s r -d 'Changes the initial zoom level, specified as the resolution in dpi'
complete -c mupdf -s A -d 'Changes the anti-aliasing quality, specified as a number of bits between 0 (o…'
complete -c mupdf -s C -d 'Sets the full-page tint using hexadecimal color syntax'
complete -c mupdf -s W -d 'Page width in points for EPUB layout'
complete -c mupdf -s H -d 'Page height in points for EPUB layout'
complete -c mupdf -s S -d 'Font size in points for EPUB layout'
complete -c mupdf -s U -d 'User style sheet for EPUB layout'

