# my_print_defaults
# Autogenerated from man page /usr/share/man/man1/my_print_defaults.1.bz2
complete -c my_print_defaults -l user
complete -c my_print_defaults -l password
complete -c my_print_defaults -l host -d 'The output consists of options, one per line, in the form that they would be …'
complete -c my_print_defaults -l help
complete -c my_print_defaults -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c my_print_defaults -l config-file
complete -c my_print_defaults -l defaults-file
complete -c my_print_defaults -s c -d 'Read only the given option file.  oc o 2. 3'
complete -c my_print_defaults -l debug
complete -c my_print_defaults -s '#' -d 'Write a debugging log.  A typical debug_options string is d:t:o,file_name'
complete -c my_print_defaults -l defaults-extra-file
complete -c my_print_defaults -l extra-file
complete -c my_print_defaults -s e -d 'Read this option file after the global option file but (on Unix) before the u…'
complete -c my_print_defaults -l defaults-group-suffix
complete -c my_print_defaults -s g -d 'In addition to the groups named on the command line, read groups that have th…'
complete -c my_print_defaults -l login-path
complete -c my_print_defaults -s l -d 'Read options from the named login path in the . mylogin. cnf login path file'
complete -c my_print_defaults -l no-defaults
complete -c my_print_defaults -s n -d 'Return an empty string'
complete -c my_print_defaults -l show
complete -c my_print_defaults -s s -d 'my_print_defaults masks passwords by default'
complete -c my_print_defaults -l verbose
complete -c my_print_defaults -s v -d 'Verbose mode.  Print more information about what the program does.  oc o 2. 3'
complete -c my_print_defaults -l version
complete -c my_print_defaults -s V -d 'Display version information and exit'

