# mysql_client_test
# Autogenerated from man page /usr/share/man/man1/mysql_client_test.1.bz2
complete -c mysql_client_test -l help
complete -c mysql_client_test -s '?'
complete -c mysql_client_test -l basedir
complete -c mysql_client_test -s b
complete -c mysql_client_test -l count
complete -c mysql_client_test -s t
complete -c mysql_client_test -l database
complete -c mysql_client_test -s D
complete -c mysql_client_test -l debug
complete -c mysql_client_test -s '#'
complete -c mysql_client_test -l getopt-ll-test
complete -c mysql_client_test -s g
complete -c mysql_client_test -l host
complete -c mysql_client_test -s h
complete -c mysql_client_test -l password
complete -c mysql_client_test -s p
complete -c mysql_client_test -l port
complete -c mysql_client_test -s P
complete -c mysql_client_test -l server-arg
complete -c mysql_client_test -s A
complete -c mysql_client_test -l show-tests
complete -c mysql_client_test -s T
complete -c mysql_client_test -l silent
complete -c mysql_client_test -s s
complete -c mysql_client_test -l socket
complete -c mysql_client_test -s S
complete -c mysql_client_test -l testcase
complete -c mysql_client_test -s c
complete -c mysql_client_test -l user
complete -c mysql_client_test -s u
complete -c mysql_client_test -s v
complete -c mysql_client_test -l vardir

