# mysql
# Autogenerated from man page /usr/share/man/man1/mysql.server.1.bz2
complete -c mysql -l basedir
complete -c mysql -l datadir
complete -c mysql -l pid-file
complete -c mysql -l service-startup-timeout
complete -c mysql -l use-mysqld_safe
complete -c mysql -l use-manager

