# mysqltest
# Autogenerated from man page /usr/share/man/man1/mysqltest.1.bz2
complete -c mysqltest -l test-file -d option
complete -c mysqltest -l help
complete -c mysqltest -s '?'
complete -c mysqltest -l basedir
complete -c mysqltest -s b
complete -c mysqltest -l character-sets-dir
complete -c mysqltest -l compress
complete -c mysqltest -s C
complete -c mysqltest -l connect-timeout
complete -c mysqltest -l continue-on-error
complete -c mysqltest -l cursor-protocol
complete -c mysqltest -l database
complete -c mysqltest -s D
complete -c mysqltest -l debug
complete -c mysqltest -s '#'
complete -c mysqltest -l debug-check
complete -c mysqltest -l debug-info
complete -c mysqltest -l host
complete -c mysqltest -s h
complete -c mysqltest -l logdir
complete -c mysqltest -l mark-progress
complete -c mysqltest -l max-connect-retries
complete -c mysqltest -l max-connections
complete -c mysqltest -l no-defaults
complete -c mysqltest -l non-blocking-api
complete -c mysqltest -l overlay-dir
complete -c mysqltest -l password
complete -c mysqltest -s p
complete -c mysqltest -l plugin-dir
complete -c mysqltest -l port
complete -c mysqltest -s P
complete -c mysqltest -l prologue
complete -c mysqltest -l source -d 'command as the first line of the test file.  oc o 2. 3'
complete -c mysqltest -l protocol
complete -c mysqltest -l ps-protocol
complete -c mysqltest -l quiet
complete -c mysqltest -l silent -d 'oc o 2. 3'
complete -c mysqltest -l record
complete -c mysqltest -s r
complete -c mysqltest -l result-file -d 'option, if that option is given'
complete -c mysqltest -s R
complete -c mysqltest -l result-format-version
complete -c mysqltest -l server-arg
complete -c mysqltest -s A
complete -c mysqltest -l tmpdir -d or
complete -c mysqltest -l core -d 'oc o 2. 3'
complete -c mysqltest -l server-file
complete -c mysqltest -s F
complete -c mysqltest -s s
complete -c mysqltest -l sleep
complete -c mysqltest -s T
complete -c mysqltest -l socket
complete -c mysqltest -s S
complete -c mysqltest -l sp-protocol
complete -c mysqltest -l ssl
complete -c mysqltest -l skip-ssl -d 'oc o 2. 3'
complete -c mysqltest -l ssl-ca
complete -c mysqltest -l ssl-capath
complete -c mysqltest -l ssl-cert
complete -c mysqltest -l ssl-cipher
complete -c mysqltest -l ssl-key
complete -c mysqltest -l ssl-crl
complete -c mysqltest -l ssl-crlpath
complete -c mysqltest -l ssl-verify-server-cert
complete -c mysqltest -l suite-dir
complete -c mysqltest -l tail-lines
complete -c mysqltest -s x
complete -c mysqltest -l timer-file
complete -c mysqltest -s m
complete -c mysqltest -s t
complete -c mysqltest -l user
complete -c mysqltest -s u
complete -c mysqltest -l verbose
complete -c mysqltest -s v
complete -c mysqltest -l version
complete -c mysqltest -s V
complete -c mysqltest -l view-protocol

