# mysql_config
# Autogenerated from man page /usr/share/man/man1/mysql_config.1.bz2
complete -c mysql_config -l cflags
complete -c mysql_config -l include -d 'for more portable options that contain only include paths.  oc o 2. 3'
complete -c mysql_config -l libmysqld-libs
complete -c mysql_config -l embedded
complete -c mysql_config -l libs
complete -c mysql_config -l libs_r
complete -c mysql_config -l plugindir
complete -c mysql_config -l port
complete -c mysql_config -l socket
complete -c mysql_config -l variable
complete -c mysql_config -l version

