# nmap
# Autogenerated from man page /usr/share/man/man1/nmap.1.bz2
complete -c nmap -s A
complete -c nmap -o T4 -d 'for faster execution; and then the hostname'
complete -c nmap -l resolve-all -d option
complete -c nmap -o iL
complete -c nmap -o iR
complete -c nmap -l exclude
complete -c nmap -l excludefile
complete -c nmap -o PE -o PS443 -o PA80 -o PP -d options
complete -c nmap -o 'P*' -d 'options (which select ping types) can be combined'
complete -c nmap -o sn -d 'option to learn how to perform only host discovery, or use'
complete -c nmap -o Pn -d 'to skip host discovery and port scan all target addresses'
complete -c nmap -o sL
complete -c nmap -l send-ip -d 'was specified.  The'
complete -c nmap -o sP
complete -c nmap -l disable-arp-ping -d or
complete -c nmap -o P0 -d and
complete -c nmap -o PN
complete -c nmap -o PS
complete -c nmap -s p -d 'except that port type specifiers like T: are not allowed.  Examples are'
complete -c nmap -o PS22 -d and
complete -c nmap -o PS22-25
complete -c nmap -o PA
complete -c nmap -l syn -d 'convenience option to implement this stateless approach'
complete -c nmap -l state -d 'option, which categorizes packets based on connection state'
complete -c nmap -o PU
complete -c nmap -l data
complete -c nmap -l data-string
complete -c nmap -l data-length -d options
complete -c nmap -o PY
complete -c nmap -o PY22 -d and
complete -c nmap -o 'PE;' -o 'PP;' -o PM
complete -c nmap -o PO
complete -c nmap -l discovery-ignore-rst
complete -c nmap -l traceroute
complete -c nmap -s n -d 'Tells Nmap to never do reverse DNS resolution on the active IP addresses it f…'
complete -c nmap -s R
complete -c nmap -s 6
complete -c nmap -l system-dns
complete -c nmap -l dns-servers
complete -c nmap -o sZ
complete -c nmap -o sC -d 'C is a prominent character in the scan name, usually the first'
complete -c nmap -o sS
complete -c nmap -o sT
complete -c nmap -o sU
complete -c nmap -l host-timeout -d 'to skip slow hosts'
complete -c nmap -o sY
complete -c nmap -o 'sN;' -o 'sF;' -o sX
complete -c nmap -l scanflags -d 'option described in the next section) exploit a subtle loophole in the m[blue…'
complete -c nmap -o sA
complete -c nmap -o sW
complete -c nmap -o sM
complete -c nmap -o sF -d 'filtered port, while a FIN scan treats the same as open|filtered'
complete -c nmap -o sI
complete -c nmap -o sO
complete -c nmap -s b
complete -c nmap -o p- -d 'to scan ports from 1 through 65535'
complete -c nmap -l exclude-ports
complete -c nmap -s F
complete -c nmap -s r
complete -c nmap -l port-ratio
complete -c nmap -l top-ports
complete -c nmap -o sV
complete -c nmap -o sR -d 'is an alias for'
complete -c nmap -l allports
complete -c nmap -l version-intensity
complete -c nmap -l version-light
complete -c nmap -l version-all
complete -c nmap -l version-trace
complete -c nmap -l packet-trace
complete -c nmap -s O -d '“incremental” class, which means that they increment the ID field in the IP h…'
complete -c nmap -l osscan-limit
complete -c nmap -l 'osscan-guess;' -l fuzzy
complete -c nmap -l max-os-tries
complete -c nmap -l script
complete -c nmap -l datadir -d '$NMAPDIR ~/'
complete -c nmap -l script-args
complete -c nmap -l script-args-file
complete -c nmap -l script-help
complete -c nmap -l 'script;' -d 'ftp-anon script, you would run nmap --script-help ftp-anon'
complete -c nmap -l script-trace
complete -c nmap -l script-updatedb
complete -c nmap -l min-hostgroup -l max-hostgroup
complete -c nmap -l min-parallelism -l max-parallelism
complete -c nmap -l scan-delay -d 'option, discussed later, is another way to do this'
complete -c nmap -l min-rtt-timeout -l max-rtt-timeout -l initial-rtt-timeout
complete -c nmap -l max-retries
complete -c nmap -s T -d 'template) is to allow ten retransmissions'
complete -c nmap -l script-timeout
complete -c nmap -l max-scan-delay
complete -c nmap -l min-rate -l max-rate
complete -c nmap -l defeat-rst-ratelimit
complete -c nmap -l defeat-icmp-ratelimit
complete -c nmap -l nsock-engine
complete -c nmap -o T3 -d 'does nothing'
complete -c nmap -o T5 -d 'caps that value at 5 ms'
complete -c nmap -o T2 -d 'because they think it is less likely to crash hosts or because they consider …'
complete -c nmap -o T0 -d and
complete -c nmap -o T1 -d 'may be useful for avoiding IDS alerts, they will take an extraordinarily long…'
complete -c nmap -s f -l mtu
complete -c nmap -l send-eth -d 'option to bypass the IP layer and send raw ethernet frames'
complete -c nmap -s D
complete -c nmap -s S
complete -c nmap -s e -d 'option and'
complete -c nmap -l source-port -s g
complete -c nmap -l ip-options -l ip-options
complete -c nmap -l ttl
complete -c nmap -l randomize-hosts
complete -c nmap -l spoof-mac
complete -c nmap -l proxies
complete -c nmap -l badsum
complete -c nmap -l adler32
complete -c nmap -o oX -o oN -d 'myscan. xml for brevity, more descriptive names are generally recommended'
complete -c nmap -o oG- -d or
complete -c nmap -o 'oXscan.xml' -d 'normal format output files named G- and Xscan. xml respectively'
complete -c nmap -l webxml -d or
complete -c nmap -l stylesheet -d 'options to create portable XML files that render as HTML on any web-connected…'
complete -c nmap -o oS
complete -c nmap -o oG
complete -c nmap -o oA
complete -c nmap -s v -o vlevel
complete -c nmap -o vv
complete -c nmap -o v3
complete -c nmap -s d -o dlevel
complete -c nmap -o dd
complete -c nmap -o d9 -d 'sets level nine'
complete -c nmap -l reason
complete -c nmap -l stats-every
complete -c nmap -o p20-30
complete -c nmap -l open
complete -c nmap -l iflist
complete -c nmap -l append-output
complete -c nmap -l resume
complete -c nmap -l noninteractive
complete -c nmap -l no-stylesheet
complete -c nmap -l unprivileged -d 'option in other situations'
complete -c nmap -l servicedb -d or
complete -c nmap -l versiondb -d 'options), that location is used for that file'
complete -c nmap -l privileged
complete -c nmap -l release-memory
complete -c nmap -o 'V;' -l version
complete -c nmap -o 'h;' -l help

