# nordvpn
# Autogenerated from man page /usr/share/man/man1/nordvpn.1.bz2
complete -c nordvpn -l help -s h -d 'Display syntax for the given operation'
complete -c nordvpn -l version -s v -d 'Display version and exit'

