# ntpdsim
# Autogenerated from man page /usr/share/man/man8/ntpdsim.8.bz2
complete -c ntpdsim -s B -d 'Specify beep delay (3600) s'
complete -c ntpdsim -s C -d 'Specify network jitter parameter (0) s'
complete -c ntpdsim -s O -d 'Specify initial time offset (0) s'
complete -c ntpdsim -s S -d 'Specify simulation duration (86400) s'
complete -c ntpdsim -s T -d 'Specify initial frequency offset (0) PPM'
complete -c ntpdsim -s W -d 'Specify oscillator wander parameter (0) PPM/s'
complete -c ntpdsim -s Y -d 'Specify network propagation delay (. 001) s'
complete -c ntpdsim -s Z -d 'Specify server processing delay (. 001) s.  FILES'

