# ntpdate
# Autogenerated from man page /usr/share/man/man8/ntpdate.8.bz2
complete -c ntpdate -s u -d 'ntpd ) is running on the same host'
complete -c ntpdate -s 4
complete -c ntpdate -s 6
complete -c ntpdate -s a -d 'Enable the authentication function and specify the key identifier to be used …'
complete -c ntpdate -s B -d 'Force the time to always be slewed using the adjtime() system call, even if t…'
complete -c ntpdate -s b -d 'Force the time to be stepped using the settimeofday() system call, rather tha…'
complete -c ntpdate -s d -d 'Enable the debugging mode, in which ntpdate will go through all the steps, bu…'
complete -c ntpdate -s e -d 'Specify the processing delay to perform an authentication function as the val…'
complete -c ntpdate -s k -d 'Specify the path for the authentication key file as the string keyfile '
complete -c ntpdate -s o -d 'Specify the NTP version for outgoing packets as the integer version , which c…'
complete -c ntpdate -s p -d 'Specify the number of samples to be acquired from each server as the integer …'
complete -c ntpdate -s q -d 'Query only - don\'t set the clock'
complete -c ntpdate -s s -d 'Divert logging output from the standard output (default) to the system syslog…'
complete -c ntpdate -s t -d 'Specify the maximum time waiting for a server response as the value timeout ,…'
complete -c ntpdate -s v -d 'Be verbose'

