# ntpdc
# Autogenerated from man page /usr/share/man/man8/ntpdc.8.bz2
complete -c ntpdc -s 4
complete -c ntpdc -s 6 -d 'COMMAND LINE OPTIONS'
complete -c ntpdc -s i
complete -c ntpdc -s n -d 'ntpdc will attempt to read interactive format commands from the standard input'
complete -c ntpdc -s c -d 'The following argument is interpreted as an interactive format command and is…'
complete -c ntpdc -s d -d 'Turn on debugging mode'
complete -c ntpdc -s l -d 'Obtain a list of peers which are known to the server(s)'
complete -c ntpdc -s p -d 'Print a list of the peers known to the server as well as a summary of their s…'
complete -c ntpdc -s s -d 'Print a list of the peers known to the server as well as a summary of their s…'

