# ntpq
# Autogenerated from man page /usr/share/man/man8/ntpq.8.bz2
complete -c ntpq -s 4 -d 'Force DNS resolution of following host names on the command line to the IPv4 …'
complete -c ntpq -s 6 -d 'Force DNS resolution of following host names on the command line to the IPv6 …'
complete -c ntpq -s c -d 'The following argument is interpreted as an interactive format command and is…'
complete -c ntpq -s d -d 'Turn on debugging mode'
complete -c ntpq -s i -d 'Force ntpq to operate in interactive mode'
complete -c ntpq -s n -d 'Output all host addresses in dotted-quad numeric format rather than convertin…'
complete -c ntpq -s p -d 'Print a list of the peers known to the server as well as a summary of their s…'

