# ntptrace
# Autogenerated from man page /usr/share/man/man8/ntptrace.8.bz2
complete -c ntptrace -s m -d 'Sets the upper limit of the number of hosts to check (default: unlimited)'
complete -c ntptrace -s n -d 'Turns off the printing of host names; instead, host IP addresses are given'

