# nullmailer-dsn
# Autogenerated from man page /usr/share/man/man1/nullmailer-dsn.1.bz2
complete -c nullmailer-dsn -l diagnostic-code -d 'Sets the actual diagnostic code issued by the mail transport'
complete -c nullmailer-dsn -l envelope-id -d 'Original envelope ID'
complete -c nullmailer-dsn -l last-attempt -d 'Sets the time of the last attempted delivery'
complete -c nullmailer-dsn -l max-lines -d 'Sets the maximum number of lines of the original message to copy into the gen…'
complete -c nullmailer-dsn -l orig-timestamp -d 'Sets the time of the original message'
complete -c nullmailer-dsn -l remote -d 'Sets the name of the remote MTA server'
complete -c nullmailer-dsn -l retry-until -d 'Sets the time of the (future) final delivery attempt.  No default'

