# nullmailer-inject
# Autogenerated from man page /usr/share/man/man1/nullmailer-inject.1.bz2
complete -c nullmailer-inject -s a -d 'Use only the command line arguments as recipient addresses'
complete -c nullmailer-inject -s b -d 'Use both the command line arguments and data from the message header as recip…'
complete -c nullmailer-inject -s e -d 'Use either the command line arguments (if there are any) or data from the mes…'
complete -c nullmailer-inject -s f -d 'Set the envelope sender address to R sender '
complete -c nullmailer-inject -s h -d 'Use only data from the message header as the recipient addresses'
complete -c nullmailer-inject -s n -d 'Do not queue the message, but print the reformatted contents to standard outp…'
complete -c nullmailer-inject -s v -d 'Print out the envelope (sender and recipient addresses) preceding the message…'

