# openssl-openssl-dsaparam
# Autogenerated from man page /usr/share/man/man1/openssl-openssl-dsaparam.1ssl.bz2
complete -c openssl-openssl-dsaparam -o help -d 'Print out a usage message'
complete -c openssl-openssl-dsaparam -o inform -d 'This specifies the input format'
complete -c openssl-openssl-dsaparam -o outform -d 'This specifies the output format, the options have the same meaning and defau…'
complete -c openssl-openssl-dsaparam -o in -d 'This specifies the input filename to read parameters from or standard input i…'
complete -c openssl-openssl-dsaparam -o out -d 'This specifies the output filename parameters to'
complete -c openssl-openssl-dsaparam -o noout -d 'This option inhibits the output of the encoded version of the parameters'
complete -c openssl-openssl-dsaparam -o text -d 'This option prints out the \\s-1DSA\\s0 parameters in human readable form'
complete -c openssl-openssl-dsaparam -s C -d 'This option converts the parameters into C code'
complete -c openssl-openssl-dsaparam -o genkey -d 'This option will generate a \\s-1DSA\\s0 either using the specified or generate…'
complete -c openssl-openssl-dsaparam -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c openssl-openssl-dsaparam -o writerand -d 'Writes random data to the specified file upon exit'

