# openrc-shutdown
# Autogenerated from man page /usr/share/man/man8/openrc-shutdown.8.bz2
complete -c openrc-shutdown -s c -d 'Cancel a pending shutdown'
complete -c openrc-shutdown -s d -d 'Do not write the wtmp boot record'
complete -c openrc-shutdown -s D -d 'Print the action that would be taken without executing it'
complete -c openrc-shutdown -s H -d 'Stop all services, kill all remaining processes and halt the system'
complete -c openrc-shutdown -s k -d 'Stop all services, kill all processes and boot directly into a new kernel loa…'
complete -c openrc-shutdown -s p -d 'Stop all services, kill all processes and power off the system'
complete -c openrc-shutdown -s R -d 'instruct openrc-init to re-exec itself'
complete -c openrc-shutdown -s r -d 'Stop all services, kill all processes and reboot the system'
complete -c openrc-shutdown -s s -d 'Stop all services, kill all processes and move to single user mode'
complete -c openrc-shutdown -s w -d 'Wrrite a wtmp shutdown record and do nothing else'

