# openssl-openssl-rand
# Autogenerated from man page /usr/share/man/man1/openssl-openssl-rand.1ssl.bz2
complete -c openssl-openssl-rand -o help -d 'Print out a usage message'
complete -c openssl-openssl-rand -o out -d 'Write to file instead of standard output'
complete -c openssl-openssl-rand -o rand -d 'A file or files containing random data used to seed the random number generat…'
complete -c openssl-openssl-rand -o writerand -d 'Writes random data to the specified file upon exit'
complete -c openssl-openssl-rand -o base64 -d 'Perform base64 encoding on the output'

