# openrc-run
# Autogenerated from man page /usr/share/man/man8/openrc-run.8.bz2
complete -c openrc-run -s d -d 'Set xtrace on in the shell to assist in debugging'
complete -c openrc-run -s D -d 'Ignore all dependency information the service supplies'
complete -c openrc-run -s s -d 'Only run the command if the service has been started'
complete -c openrc-run -s S -d 'Only run the command if the service has been stopped'
complete -c openrc-run -s q -d 'Turns off all informational output the service generates'
complete -c openrc-run -s v -d 'Turns on any extra informational output the service generates'
complete -c openrc-run -s Z -d 'Shows which services would be stopped and/or started without actually stoppin…'

