# openrc
# Autogenerated from man page /usr/share/man/man8/openrc.8.bz2
complete -c openrc -s n -d 'Do not stop any services'
complete -c openrc -s o -d 'Override the next runlevel to change into when leaving single user or boot ru…'
complete -c openrc -s s -d 'Run the service specified with the rest of the arguments'
complete -c openrc -s S -d 'Output the RC system type, if any'
complete -c openrc -s h -d 'Display usage information and exit'
complete -c openrc -s C -d 'Disable color output'
complete -c openrc -s V -d 'Display software version'
complete -c openrc -s v -d 'Run verbosely'
complete -c openrc -s q -d 'Run quietly (repeat to suppress errors)'

