# openssl-openssl-spkac
# Autogenerated from man page /usr/share/man/man1/openssl-openssl-spkac.1ssl.bz2
complete -c openssl-openssl-spkac -o help -d 'Print out a usage message'
complete -c openssl-openssl-spkac -o in -d 'This specifies the input filename to read from or standard input if this opti…'
complete -c openssl-openssl-spkac -o out -d 'Specifies the output filename to write to or standard output by default'
complete -c openssl-openssl-spkac -o key -d 'Create an \\s-1SPKAC\\s0 file using the private key in keyfile'
complete -c openssl-openssl-spkac -o keyform -d 'Whether the key format is \\s-1PEM, DER,\\s0 or an engine-backed key'
complete -c openssl-openssl-spkac -o passin -d 'The input file password source'
complete -c openssl-openssl-spkac -o challenge -d 'Specifies the challenge string if an \\s-1SPKAC\\s0 is being created'
complete -c openssl-openssl-spkac -o spkac -d 'Allows an alternative name form the variable containing the \\s-1SPKAC'
complete -c openssl-openssl-spkac -o spksect -d 'Allows an alternative name form the section containing the \\s-1SPKAC'
complete -c openssl-openssl-spkac -o noout -d 'Don\'t output the text version of the \\s-1SPKAC\\s0 (not used if an \\s-1SPKAC\\s…'
complete -c openssl-openssl-spkac -o pubkey -d 'Output the public key of an \\s-1SPKAC\\s0 (not used if an \\s-1SPKAC\\s0 is bein…'
complete -c openssl-openssl-spkac -o verify -d 'Verifies the digital signature on the supplied \\s-1SPKAC. \\s0'

