# openssl-openssl-tsget
# Autogenerated from man page /usr/share/man/man1/openssl-openssl-tsget.1ssl.bz2
complete -c openssl-openssl-tsget -s h -d 'The \\s-1URL\\s0 of the \\s-1HTTP/HTTPS\\s0 server listening for timestamp reques…'
complete -c openssl-openssl-tsget -s e -d 'If the -o option is not given this argument specifies the extension of the ou…'
complete -c openssl-openssl-tsget -s o -d 'This option can be specified only when just one request is sent to the server'
complete -c openssl-openssl-tsget -s v -d 'The name of the currently processed request is printed on standard error'
complete -c openssl-openssl-tsget -s d -d 'Switches on verbose mode for the underlying curl library'
complete -c openssl-openssl-tsget -s k -d '(\\s-1HTTPS\\s0) In case of certificate-based client authentication over \\s-1HT…'
complete -c openssl-openssl-tsget -s p -d '(\\s-1HTTPS\\s0) Specifies the passphrase for the private key specified by the …'
complete -c openssl-openssl-tsget -s c -d '(\\s-1HTTPS\\s0) In case of certificate-based client authentication over \\s-1HT…'
complete -c openssl-openssl-tsget -s C -d '(\\s-1HTTPS\\s0) The trusted \\s-1CA\\s0 certificate store'
complete -c openssl-openssl-tsget -s P -d '(\\s-1HTTPS\\s0) The path containing the trusted \\s-1CA\\s0 certificates to veri…'
complete -c openssl-openssl-tsget -o rand -d 'The files containing random data for seeding the random number generator'
complete -c openssl-openssl-tsget -s g -d 'The name of an \\s-1EGD\\s0 socket to get random data from.  (Optional)'

