# pam_elogind
# Autogenerated from man page /usr/share/man/man8/pam_elogind.8.bz2
complete -c pam_elogind -o auth -d 'auth      required   pam_deny. so'
complete -c pam_elogind -o account -d 'account   sufficient pam_unix. so account   required   pam_permit. so'
complete -c pam_elogind -o password -d 'password  sufficient pam_unix'
complete -c pam_elogind -o session

