# perror
# Autogenerated from man page /usr/share/man/man1/perror.1.bz2
complete -c perror -l help
complete -c perror -l info
complete -c perror -s I
complete -c perror -s '?' -d 'Display a help message and exit.  oc o 2. 3'
complete -c perror -l ndb -d 'Print the error message for a MySQL Cluster error code'
complete -c perror -l silent
complete -c perror -s s -d 'Silent mode.  Print only the error message.  oc o 2. 3'
complete -c perror -l verbose
complete -c perror -s v -d 'Verbose mode.  Print error code and message.  This is the default behavior'
complete -c perror -l version
complete -c perror -s V -d 'Display version information and exit'

