# pfm
# Autogenerated from man page /usr/share/man/man1/pfm.1.bz2
complete -c pfm -l help -d 'Print extended usage information, then exit'
complete -c pfm -s c -l colorset -d 'Start \\f(CW\\*(C`pfm\\*(C\' using the specified colorset (as defined in the '
complete -c pfm -s l -l layout -d 'Start \\f(CW\\*(C`pfm\\*(C\' using the specified column layout (as defined in the '
complete -c pfm -l login -d 'Start \\f(CW\\*(C`pfm\\*(C\' as a login shell'
complete -c pfm -s o -l sort -d 'Start \\f(CW\\*(C`pfm\\*(C\' using the specified sort mode (as shown by the F6 co…'
complete -c pfm -s s -l swap -d 'The directory that \\f(CW\\*(C`pfm\\*(C\' should initially use as swap directory'
complete -c pfm -l usage -d 'Print concise usage information, then exit'

