# phpize
# Autogenerated from man page /usr/lib64/php8.0/man/man1/phpize.1
complete -c phpize -l clean -d 'Remove all created files'
complete -c phpize -l help -d 'Prints usage information'
complete -c phpize -l version
complete -c phpize -s v -d 'Prints API version information SEE ALSO php (1) VERSION INFORMATION This manp…'

