# po4a-gettextize
# Autogenerated from man page /usr/share/man/man1/po4a-gettextize.1p.bz2
complete -c po4a-gettextize -s f -l format -d 'Format of the documentation you want to handle'
complete -c po4a-gettextize -s m -l master -d 'File containing the master document to translate'
complete -c po4a-gettextize -s M -l master-charset -d 'Charset of the file containing the document to translate'
complete -c po4a-gettextize -s l -l localized -d 'File containing the localized (translated) document'
complete -c po4a-gettextize -s L -l localized-charset -d 'Charset of the file containing the localized document'
complete -c po4a-gettextize -s p -l po -d 'File where the message catalog should be written'
complete -c po4a-gettextize -s o -l option -d 'Extra option(s) to pass to the format plugin'
complete -c po4a-gettextize -s h -l help -d 'Show a short help message'
complete -c po4a-gettextize -l help-format -d 'List the documentation formats understood by po4a'
complete -c po4a-gettextize -s V -l version -d 'Display the version of the script and exit'
complete -c po4a-gettextize -s v -l verbose -d 'Increase the verbosity of the program'
complete -c po4a-gettextize -s d -l debug -d 'Output some debugging information'
complete -c po4a-gettextize -l msgid-bugs-address -d 'Set the report address for msgid bugs'
complete -c po4a-gettextize -l copyright-holder -d 'Set the copyright holder in the \\s-1POT\\s0 header'
complete -c po4a-gettextize -l package-name -d 'Set the package name for the \\s-1POT\\s0 header'
complete -c po4a-gettextize -l package-version -d 'Set the package version for the \\s-1POT\\s0 header'

