# po4a-display-pod
# Autogenerated from man page /usr/share/man/man1/po4a-display-pod.1.bz2
complete -c po4a-display-pod -s p -d 'The PO file containing the translations'
complete -c po4a-display-pod -s m -d 'The original POD file used by po4a to generate PO file'
complete -c po4a-display-pod -s o -d 'Some options to pass to po4a-translate(1)'

