# po4a-display-man
# Autogenerated from man page /usr/share/man/man1/po4a-display-man.1.bz2
complete -c po4a-display-man -s p -d 'The PO file containing the translations'
complete -c po4a-display-man -s m -d 'The original man page'
complete -c po4a-display-man -s o -d 'Some options to pass to po4a-translate(1)'

