# po4a-normalize
# Autogenerated from man page /usr/share/man/man1/po4a-normalize.1p.bz2
complete -c po4a-normalize -s o -l option -d 'Extra option(s) to pass to the format plugin'
complete -c po4a-normalize -s b -l blank -d 'Create an blank translated document'
complete -c po4a-normalize -s h -l help -d 'Show a short help message'
complete -c po4a-normalize -l help-format -d 'List the documentation formats understood by po4a'
complete -c po4a-normalize -s f -l format -d 'Format of the documentation you want to handle'
complete -c po4a-normalize -s M -l master-charset -d 'Charset of the file containing the document to translate'
complete -c po4a-normalize -s l -l localized -d 'Name of the normalized file to produce (po4a-normalize. output by default)'
complete -c po4a-normalize -s p -l pot -d 'Pot file to produce (po4a-normalize. po by default)'

