# profiles
# Autogenerated from man page /usr/share/man/man1/profiles.1.bz2
complete -c profiles -s v -l verbose -d 'Increases verbosity of messages'
complete -c profiles -s c -s n -l change-sid -l new-sid -d 'Change all occurrences of SID1 in file by SID2'
complete -c profiles -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c profiles -l debug-stdout -d 'This will redirect debug output to STDOUT'
complete -c profiles -l configfile -d 'The file specified contains the configuration details required by the client'
complete -c profiles -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c profiles -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c profiles -l leak-report -d 'Enable talloc leak reporting on exit'
complete -c profiles -l leak-report-full -d 'Enable full talloc leak reporting on exit'
complete -c profiles -s V -l version -d 'Prints the program version number'
complete -c profiles -s '?' -l help -d 'Print a summary of command line options'
complete -c profiles -l usage -d 'Display brief usage message'

