# profile-config
# Autogenerated from man page /usr/share/man/man1/profile-config.1.bz2
complete -c profile-config -l force -d 'flag is specified, set the profile even if it doesn\'t appear to be a valid on…'

