# pspax
# Autogenerated from man page /usr/share/man/man1/pspax.1.bz2
complete -c pspax -s a -l all -d 'Show all processes'
complete -c pspax -s e -l header -d 'Print GNU_STACK/PT_LOAD markings'
complete -c pspax -s i -l ipaddr -d 'Print ipaddr info if supported'
complete -c pspax -s p -l pid -d 'Only process specified process id'
complete -c pspax -s u -l user -d 'Process user/uid #'
complete -c pspax -s g -l group -d 'Process group/gid #'
complete -c pspax -s n -l nx -d 'Only display w^x processes'
complete -c pspax -s w -l wx -d 'Only display w|x processes'
complete -c pspax -s v -l verbose -d 'Be verbose (can be used more than once)'
complete -c pspax -s B -l nobanner -d 'Don\\*(Aqt display the header'
complete -c pspax -s h -l help -d 'Show condensed usage and exit'
complete -c pspax -s V -l version -d 'Print version and exit'

