# pspell-config
# Autogenerated from man page /usr/share/man/man1/pspell-config.1.bz2
complete -c pspell-config -l version -d 'outputs version information about the installed pspell'
complete -c pspell-config -l datadir -d 'displays the data directory'
complete -c pspell-config -l pkgdatadir -d 'displays the aspell package directory AUTHOR This manual page was written by …'

