# ptargrep-2
# Autogenerated from man page /usr/share/man/man1/ptargrep-2.400.0-perl-5.36.0.1.bz2
complete -c ptargrep-2 -l basename -s b -d 'When matching files are extracted, ignore the directory path from the archive…'
complete -c ptargrep-2 -l ignore-case -s i -d 'Make pattern matching case-insensitive'
complete -c ptargrep-2 -l list-only -s l -d 'Print the pathname of each matching file from the archive to \\s-1STDOUT'
complete -c ptargrep-2 -l verbose -s v -d 'Log debugging info to \\s-1STDERR. \\s0'

