# pvck
# Autogenerated from man page /usr/share/man/man8/pvck.8.bz2
complete -c pvck -l commandprofile
complete -c pvck -l config
complete -c pvck -s d -l debug
complete -c pvck -l driverloaded
complete -c pvck -s h -l help
complete -c pvck -l labelsector
complete -c pvck -l lockopt
complete -c pvck -l longhelp
complete -c pvck -l profile
complete -c pvck -s q -l quiet
complete -c pvck -s t -l test
complete -c pvck -s v -l verbose
complete -c pvck -l version
complete -c pvck -s y -l yes

