# q
# Autogenerated from man page /usr/share/man/man1/q.1.bz2
complete -c q -s i -l install -d 'Install symlinks for applets'
complete -c q -s o -l overlays -d 'Print available overlays (read from repos. conf)'
complete -c q -s e -l envvar -d 'Print used environment variables and found values'
complete -c q -s m -l masks -d 'Print the masks from package. mask files found'
complete -c q -l root -d 'Set the ROOT env var'
complete -c q -s v -l verbose -d 'Report full package versions, emit more elaborate output'
complete -c q -s q -l quiet -d 'Tighter output; suppress warnings'
complete -c q -s C -l nocolor -d 'Don\'t output color'
complete -c q -l color -d 'Force color in output'
complete -c q -s h -l help -d 'Print this help and exit'
complete -c q -s V -l version -d 'Print version and exit.  APPLETS'

