# qatom
# Autogenerated from man page /usr/share/man/man1/qatom.1.bz2
complete -c qatom -s F -l format -d 'Specify a custom  output  format.   The default format is '
complete -c qatom -s c -l compare -d 'Compare two atoms'
complete -c qatom -s s -l scompare -d 'Compare two atoms in the given order data, query'
complete -c qatom -s p -l print -d 'Print reconstructed atom'
complete -c qatom -s l -l lookup -d 'Lookup atom in tree'
complete -c qatom -l root -d 'Set the ROOT env var'
complete -c qatom -s v -l verbose -d 'Force all expansions, basically treat all [ like {'
complete -c qatom -s q -l quiet -d 'Ignored for compatibility with other qapplets'
complete -c qatom -s C -l nocolor -d 'Ignored for compatibility with other qapplets'
complete -c qatom -l color -d 'Force color in output'
complete -c qatom -s h -l help -d 'Print this help and exit'
complete -c qatom -s V -l version -d 'Print version and exit'

