# qcheck
# Autogenerated from man page /usr/share/man/man1/qcheck.1.bz2
complete -c qcheck -s F -l format -d 'Custom output format (default: %[CATEGORY]%[PN])'
complete -c qcheck -s s -l skip -d 'Ignore files matching the regular expression <arg>'
complete -c qcheck -s u -l update -d 'Update missing files, chksum and mtimes for packages'
complete -c qcheck -s A -l noafk -d 'Ignore missing files'
complete -c qcheck -s B -l badonly -d 'Only print pkgs containing bad files'
complete -c qcheck -s H -l nohash -d 'Ignore differing/unknown file chksums'
complete -c qcheck -s T -l nomtime -d 'Ignore differing file mtimes'
complete -c qcheck -s P -l skip-protected -d 'Ignore files in CONFIG_PROTECT-ed paths'
complete -c qcheck -s p -l prelink -d 'Undo prelink when calculating checksums'
complete -c qcheck -l root -d 'Set the ROOT env var'
complete -c qcheck -s v -l verbose -d 'Report full package versions, emit more elaborate output'
complete -c qcheck -s q -l quiet -d 'Tighter output; suppress warnings'
complete -c qcheck -s C -l nocolor -d 'Don\'t output color'
complete -c qcheck -l color -d 'Force color in output'
complete -c qcheck -s h -l help -d 'Print this help and exit'
complete -c qcheck -s V -l version -d 'Print version and exit'

