# qfile
# Autogenerated from man page /usr/share/man/man1/qfile.1.bz2
complete -c qfile -s F -l format -d 'Print matched atom using given format string'
complete -c qfile -s S -l slots -d 'Display installed packages with slots'
complete -c qfile -s R -l root-prefix -d 'Assume arguments are already prefixed by $ROOT'
complete -c qfile -s d -l dir -d 'Only consider basename of argument and also match directories, this option ma…'
complete -c qfile -s o -l orphans -d 'List orphan files'
complete -c qfile -s x -l exclude -d 'Don\'t look in package <arg> (used with --orphans)'
complete -c qfile -s P -l skip-plibreg -d 'Don\'t look in the prunelib registry'
complete -c qfile -l root -d 'Set the ROOT env var'
complete -c qfile -s v -l verbose -d 'Print package versions and symlink targets for matches, warn about problems w…'
complete -c qfile -s q -l quiet -d 'Don\'t print matching file for matches, just the package'
complete -c qfile -s C -l nocolor -d 'Don\'t output color'
complete -c qfile -l color -d 'Force color in output'
complete -c qfile -s h -l help -d 'Print this help and exit'
complete -c qfile -s V -l version -d 'Print version and exit.  FINDING FILE OWNERS'

