# qmanifest
# Autogenerated from man page /usr/share/man/man1/qmanifest.1.bz2
complete -c qmanifest -s g -l generate -d 'Generate thick Manifests'
complete -c qmanifest -s s -l signas -d 'Sign generated Manifest using GPG key'
complete -c qmanifest -s p -l passphrase -d 'Ask for GPG key password (instead of relying on gpg-agent)'
complete -c qmanifest -s d -l dir -d 'Treat arguments as directories'
complete -c qmanifest -s o -l overlay -d 'Treat arguments as overlay names'
complete -c qmanifest -l root -d 'Set the ROOT env var'
complete -c qmanifest -s v -l verbose -d 'Report full package versions, emit more elaborate output'
complete -c qmanifest -s q -l quiet -d 'Tighter output; suppress warnings'
complete -c qmanifest -s C -l nocolor -d 'Don\'t output color'
complete -c qmanifest -l color -d 'Force color in output'
complete -c qmanifest -s h -l help -d 'Print this help and exit'
complete -c qmanifest -s V -l version -d 'Print version and exit.  GENERATING A SIGNED TREE'

