# qpkg
# Autogenerated from man page /usr/share/man/man1/qpkg.1.bz2
complete -c qpkg -s c -l clean -d 'clean pkgdir of files that are not installed'
complete -c qpkg -s E -l eclean -d 'clean pkgdir of files that are not in the tree anymore'
complete -c qpkg -s p -l pretend -d 'pretend only'
complete -c qpkg -s P -l pkgdir -d 'alternate package directory'
complete -c qpkg -l root -d 'Set the ROOT env var'
complete -c qpkg -s v -l verbose -d 'Check and report MD5 hash mismatches during install'
complete -c qpkg -s q -l quiet -d 'Ignored for compatibility with other qapplets'
complete -c qpkg -s C -l nocolor -d 'Don\'t output color'
complete -c qpkg -l color -d 'Force color in output'
complete -c qpkg -s h -l help -d 'Print this help and exit'
complete -c qpkg -s V -l version -d 'Print version and exit'

