# qsearch
# Autogenerated from man page /usr/share/man/man1/qsearch.1.bz2
complete -c qsearch -s a -l all -d 'List the descriptions of every package in the cache'
complete -c qsearch -s s -l search -d 'Regex search package basenames'
complete -c qsearch -s S -l desc -d 'Regex search package descriptions (or homepage when using -H)'
complete -c qsearch -s N -l name-only -d 'Only show package name'
complete -c qsearch -s H -l homepage -d 'Show homepage info instead of description'
complete -c qsearch -s R -l repo -d 'Show repository the ebuild originates from'
complete -c qsearch -s F -l format -d 'Print matched atom using given format string'
complete -c qsearch -l root -d 'Set the ROOT env var'
complete -c qsearch -s v -l verbose -d 'Ignored for compatibility with other qapplets'
complete -c qsearch -s q -l quiet -d 'Ignored for compatibility with other qapplets'
complete -c qsearch -s C -l nocolor -d 'Don\'t output color'
complete -c qsearch -l color -d 'Force color in output'
complete -c qsearch -s h -l help -d 'Print this help and exit'
complete -c qsearch -s V -l version -d 'Print version and exit'

