# qsize
# Autogenerated from man page /usr/share/man/man1/qsize.1.bz2
complete -c qsize -s f -l filesystem -d 'Show size used on disk'
complete -c qsize -s s -l sum -d 'Include a summary'
complete -c qsize -s S -l sum-only -d 'Show just the summary'
complete -c qsize -s m -l megabytes -d 'Display all sizes in megabytes'
complete -c qsize -s k -l kilobytes -d 'Display all sizes in kilobytes'
complete -c qsize -s b -l bytes -d 'Display all sizes in bytes'
complete -c qsize -s i -l ignore -d 'Filter out entries matching <arg>, which is a regular expression, before calc…'
complete -c qsize -s F -l format -d 'Print matched atom using given format string'
complete -c qsize -l root -d 'Set the ROOT env var'
complete -c qsize -s v -l verbose -d 'Ignored for compatibility with other qapplets'
complete -c qsize -s q -l quiet -d 'Ignored for compatibility with other qapplets'
complete -c qsize -s C -l nocolor -d 'Don\'t output color'
complete -c qsize -l color -d 'Force color in output'
complete -c qsize -s h -l help -d 'Print this help and exit'
complete -c qsize -s V -l version -d 'Print version and exit'

