# qtbz2
# Autogenerated from man page /usr/share/man/man1/qtbz2.1.bz2
complete -c qtbz2 -s d -l dir -d 'Change to specified directory'
complete -c qtbz2 -s j -l join -d 'Join: <tar. bz2> <xpak> <tbz2>'
complete -c qtbz2 -s s -l split -d 'Split a tbz2 into a tar. bz2 + xpak'
complete -c qtbz2 -s t -l tarbz2 -d 'Just split the tar. bz2'
complete -c qtbz2 -s x -l xpak -d 'Just split the xpak'
complete -c qtbz2 -s O -l stdout -d 'Write files to stdout'
complete -c qtbz2 -l root -d 'Set the ROOT env var'
complete -c qtbz2 -s v -l verbose -d 'Print some files and sizes while joining and splitting'
complete -c qtbz2 -s q -l quiet -d 'Ignored for compatibility with other qapplets'
complete -c qtbz2 -s C -l nocolor -d 'Don\'t output color'
complete -c qtbz2 -l color -d 'Force color in output'
complete -c qtbz2 -s h -l help -d 'Print this help and exit'
complete -c qtbz2 -s V -l version -d 'Print version and exit'

