# qtegrity
# Autogenerated from man page /usr/share/man/man1/qtegrity.1.bz2
complete -c qtegrity -s a -l add -d 'Add file to store of known-good digests'
complete -c qtegrity -s i -l ignore-non-existent -d 'Be silent if recorded file no longer exists'
complete -c qtegrity -s s -l show-matches -d 'Show recorded digests that match with known-good digests'
complete -c qtegrity -l root -d 'Set the ROOT env var'
complete -c qtegrity -s v -l verbose -d 'Report full package versions, emit more elaborate output'
complete -c qtegrity -s q -l quiet -d 'Tighter output; suppress warnings'
complete -c qtegrity -s C -l nocolor -d 'Don\'t output color'
complete -c qtegrity -l color -d 'Force color in output'
complete -c qtegrity -s h -l help -d 'Print this help and exit'
complete -c qtegrity -s V -l version -d 'Print version and exit.  RELEVANT FILES'

