# quickpkg
# Autogenerated from man page /usr/share/man/man1/quickpkg.1.bz2
complete -c quickpkg -l ignore-default-opts -d 'Causes the QUICKPKG_DEFAULT_OPTS environment variable to be ignored'
complete -c quickpkg -l include-config -d 'Include all files protected by CONFIG_PROTECT (as a security precaution, defa…'
complete -c quickpkg -l include-unmodified-config -d 'Include files protected by CONFIG_PROTECT that have not been modified since i…'
complete -c quickpkg -l umask -d 'The umask used during package creation (default is 0077)'

