# quse
# Autogenerated from man page /usr/share/man/man1/quse.1.bz2
complete -c quse -s e -l exact -d 'Search for exact string, e. g. do not use regular expression matching'
complete -c quse -s a -l all -d 'List all ebuilds, don\'t match anything'
complete -c quse -s L -l license -d 'Use the LICENSE vs IUSE'
complete -c quse -s D -l describe -d 'Describe the USE flag, when no USE-flag given and combined with -p, lists all…'
complete -c quse -s I -l installed -d 'Only search installed packages'
complete -c quse -s p -l package -d 'Restrict matching to package or category'
complete -c quse -s R -l repo -d 'Show repository the ebuild originates from'
complete -c quse -s F -l format -d 'Print matched atom using given format string'
complete -c quse -l root -d 'Set the ROOT env var'
complete -c quse -s v -l verbose -d 'Show versions for packages that match the search'
complete -c quse -s q -l quiet -d 'Ignored for compatibility with other qapplets'
complete -c quse -s C -l nocolor -d 'Don\'t output color'
complete -c quse -l color -d 'Force color in output'
complete -c quse -s h -l help -d 'Print this help and exit'
complete -c quse -s V -l version -d 'Print version and exit'

