# qxpak
# Autogenerated from man page /usr/share/man/man1/qxpak.1.bz2
complete -c qxpak -s l -l list -d 'List the contents of an archive'
complete -c qxpak -s x -l extract -d 'Extract the contents of an archive'
complete -c qxpak -s c -l create -d 'Create an archive of a directory/files'
complete -c qxpak -s d -l dir -d 'Change to specified directory'
complete -c qxpak -s O -l stdout -d 'Write files to stdout'
complete -c qxpak -l root -d 'Set the ROOT env var'
complete -c qxpak -s v -l verbose -d 'Report full package versions, emit more elaborate output'
complete -c qxpak -s q -l quiet -d 'Tighter output; suppress warnings'
complete -c qxpak -s C -l nocolor -d 'Don\'t output color'
complete -c qxpak -l color -d 'Force color in output'
complete -c qxpak -s h -l help -d 'Print this help and exit'
complete -c qxpak -s V -l version -d 'Print version and exit'

