# rc-config
# Autogenerated from man page /usr/share/man/man1/rc-config.1.bz2
complete -c rc-config -l all -d or
complete -c rc-config -l unused -d 'the scripts of all runlevels or the scripts not assigned to any runlevel are …'

