# rc-status
# Autogenerated from man page /usr/share/man/man8/rc-status.8.bz2
complete -c rc-status -s a -d 'Show all runlevels and their services'
complete -c rc-status -s c -d 'List all services that have crashed'
complete -c rc-status -s f -d 'Select a format for the output'
complete -c rc-status -s l -d 'List all defined runlevels'
complete -c rc-status -s m -d 'Show all manually started services'
complete -c rc-status -s r -d 'Print the current runlevel name'
complete -c rc-status -s S -d 'Show all supervised services'
complete -c rc-status -s s -d 'Show all services'
complete -c rc-status -s u -d 'Show services not assigned to any runlevel'
complete -c rc-status -s C -d 'Disable color output.  runlevel Show information only for the named runlevel'

