# rc-update
# Autogenerated from man page /usr/share/man/man8/rc-update.8.bz2
complete -c rc-update -s v -d 'Show all services'
complete -c rc-update -s u -d 'Forces an update of the dependency tree cache'

