# rdf2bin
# Autogenerated from man page /usr/share/man/man1/rdf2bin.1.bz2
complete -c rdf2bin -s o -d 'Relocate at origin R relocation-origin '
complete -c rdf2bin -s p -d 'Pad segments until their size is a multiple of R segment-alignment '
complete -c rdf2bin -s f -d 'Specify the output format'

