# readbootlog
# Autogenerated from man page /usr/share/man/man1/readbootlog.1.bz2
complete -c readbootlog -s f -d 'Tells readbootlog to use a specific file instead of /var/log/boot'
complete -c readbootlog -s h -d 'Displays a brief help message'

