# resgen
# Autogenerated from man page /usr/share/man/man1/resgen.1.bz2
complete -c resgen -o compile -d 'Sp This switch instructs resgen to compile multiple files'
complete -c resgen -o usesourcepath

