# ri27
# Autogenerated from man page /usr/share/man/man1/ri27.1.bz2
complete -c ri27 -s i
complete -c ri27 -s a
complete -c ri27 -s l
complete -c ri27 -s T -d 'Synonym for -no-pager.  Pp'
complete -c ri27 -s w
complete -c ri27 -l width -d 'Set the width of the output.  Pp'
complete -c ri27 -l server -d 'Run RDoc server on the given port.  The default port is\\~8214.  Pp'
complete -c ri27 -s f
complete -c ri27 -l format -d 'Use the selected formatter'
complete -c ri27 -s h
complete -c ri27 -l help -d 'Show help and exit.  Pp'
complete -c ri27 -s v
complete -c ri27 -l version -d 'Output version information and exit'
complete -c ri27 -s d
complete -c ri27 -l doc-dir -d 'List of directories from which to source documentation in addition to the sta…'
complete -c ri27 -l no-standard-docs -d 'Do not include documentation from the Ruby standard library, site_lib, instal…'
complete -c ri27 -l dump -d 'Dump data from an ri cache or data file'

