# rman
# Autogenerated from man page /usr/share/man/man1/rman.1.bz2
complete -c rman -s h -l help -d 'Show list of command line options and exit'
complete -c rman -s v -l version -d 'Show version number and exit'
complete -c rman -s f -l filter -d 'Set the output filter.  Defaults to ASCII'
complete -c rman -s S -l source -d 'PolyglotMan tries to automatically determine whether its input  is source or …'
complete -c rman -s F -l format -l formatted -d 'PolyglotMan tries to automatically determine whether its input  is source or …'
complete -c rman -s l -l title -d 'In HTML mode this sets the <TITLE> of the man pages, given the  same paramete…'
complete -c rman -s r -l reference -l manref -d 'In HTML and SGML modes this sets the URL form by which to retrieve  other man…'
complete -c rman -s V -l volumes -d 'Set the list of valid volumes to check against when looking for  cross-refere…'
complete -c rman -s b -l subsections -d 'Try to recognize subsection titles in addition to section titles'
complete -c rman -s K -l nobreak -d 'Indicate manual pages don\'t have page breaks, so don\'t look for  footers and …'
complete -c rman -s k -l keep -d 'Keep headers and footers, as a canonical report at the end of  the page'
complete -c rman -s n -l name -d 'Set name of man page (used in roff format)'
complete -c rman -s p -l paragraph -d 'paragraph mode toggle'
complete -c rman -s s -d 'Set volume (aka section) number of man page (used in roff format)'
complete -c rman -s t -l tabstops -d 'For those macros sets that use tabs in place of spaces where  possible in ord…'

