# runc-run
# Autogenerated from man page /usr/share/man/man8/runc-run.8.bz2
complete -c runc-run -l bundle -s b -d 'Path to the root of the bundle directory.  Default is current directory'
complete -c runc-run -l console-socket -d 'Path to an AF\\_UNIX  socket which will receive a file descriptor referencing …'
complete -c runc-run -l detach -s d -d 'Detach from the container\'s process'
complete -c runc-run -l pid-file -d 'Specify the file to write the initial container process\' PID to'
complete -c runc-run -l no-subreaper -d 'Disable the use of the subreaper used to reap reparented processes'
complete -c runc-run -l no-pivot -d 'Do not use pivot root to jail process inside rootfs'
complete -c runc-run -l no-new-keyring -d 'Do not create a new session keyring for the container'
complete -c runc-run -l preserve-fds -d 'Pass N additional file descriptors to the container (stdio + $LISTEN\\_FDS + N…'
complete -c runc-run -l keep -d 'Keep container\'s state directory and cgroup'

