# runc-delete
# Autogenerated from man page /usr/share/man/man8/runc-delete.8.bz2
complete -c runc-delete -l force -s f -d 'Forcibly delete the running container, using SIGKILL signal(7) to stop it fir…'

