# runc-exec
# Autogenerated from man page /usr/share/man/man8/runc-exec.8.bz2
complete -c runc-exec -l console-socket -d 'Path to an AF\\_UNIX  socket which will receive a file descriptor referencing …'
complete -c runc-exec -l cwd -d 'Change to path in the container before executing the command'
complete -c runc-exec -l env -s e -d 'Set an environment variable name to value.  Can be specified multiple times'
complete -c runc-exec -l tty -s t -d 'Allocate a pseudo-TTY'
complete -c runc-exec -l user -s u -d 'Run the command as a user (and, optionally, group) specified by uid (and gid)'
complete -c runc-exec -l additional-gids -s g -d 'Add additional group IDs.  Can be specified multiple times'
complete -c runc-exec -l process -s p -d 'Instead of specifying all the exec parameters directly on the command line, g…'
complete -c runc-exec -l detach -s d -d 'Detach from the container\'s process'
complete -c runc-exec -l pid-file -d 'Specify the file to write the container process\' PID to'
complete -c runc-exec -l process-label -d 'Set the asm process label for the process commonly used with selinux(7)'
complete -c runc-exec -l apparmor -d 'Set the apparmor(7) profile for the process'
complete -c runc-exec -l no-new-privs -d 'Set the "no new privileges" value for the process'
complete -c runc-exec -l cap -d 'Add a capability to the bounding set for the process'
complete -c runc-exec -l preserve-fds -d 'Pass N additional file descriptors to the container (stdio + $LISTEN\\_FDS + N…'
complete -c runc-exec -l ignore-paused -d 'Allow exec in a paused container'
complete -c runc-exec -l cgroup -d 'Execute a process in a sub-cgroup'

