# runc
# Autogenerated from man page /usr/share/man/man8/runc.8.bz2
complete -c runc -l debug -d 'Enable debug logging'
complete -c runc -l log -d 'Set the log destination to path.  The default is to log to stderr'
complete -c runc -l log-format -d 'Set the log format (default is text)'
complete -c runc -l root -d 'Set the root directory to store containers\' state'
complete -c runc -l criu -d 'Set the path to the criu(8) binary used for checkpoint and restore'
complete -c runc -l systemd-cgroup -d 'Enable systemd cgroup support.  If this is set, the container spec (config'
complete -c runc -l rootless -d 'Enable or disable rootless mode'
complete -c runc -l help -s h -d 'Show help'
complete -c runc -l version -s v -d 'Show version.  SEE ALSO'

