# runc-events
# Autogenerated from man page /usr/share/man/man8/runc-events.8.bz2
complete -c runc-events -l interval -d 'Set the stats collection interval.  Default is 5s'
complete -c runc-events -l stats -d 'Show the container\'s stats once then exit.  SEE ALSO'

