# runc-update
# Autogenerated from man page /usr/share/man/man8/runc-update.8.bz2
complete -c runc-update -l resources -s r -d 'Read the new resource limtis from resources. json.  Use - to read from stdin'
complete -c runc-update -l blkio-weight -d 'Set a new io weight'
complete -c runc-update -l cpu-period -d 'Set CPU CFS period to be used for hardcapping (in microseconds)'
complete -c runc-update -l cpu-quota -d 'Set CPU usage limit within a given period (in microseconds)'
complete -c runc-update -l cpu-rt-period -d 'Set CPU realtime period to be used for hardcapping (in microseconds)'
complete -c runc-update -l cpu-rt-runtime -d 'Set CPU realtime hardcap limit (in usecs)'
complete -c runc-update -l cpu-share -d 'Set CPU shares (relative weight vs.  other containers)'
complete -c runc-update -l cpuset-cpus -d 'Set CPU(s) to use.  The list can contain commas and ranges'
complete -c runc-update -l cpuset-mems -d 'Set memory node(s) to use.  The list format is the same as for --cpuset-cpus'
complete -c runc-update -l memory -d 'Set memory limit to num bytes'
complete -c runc-update -l memory-reservation -d 'Set memory reservation, or soft limit, to num bytes'
complete -c runc-update -l memory-swap -d 'Set total memory + swap usage to num bytes.  Use -1 to unset the limit (i. e'
complete -c runc-update -l pids-limit -d 'Set the maximum number of processes allowed in the container'
complete -c runc-update -l l3-cache-schema -d 'Set the value for Intel RDT/CAT L3 cache schema'
complete -c runc-update -l mem-bw-schema -d 'Set the Intel RDT/MBA memory bandwidth schema.  SEE ALSO'

