# runc-spec
# Autogenerated from man page /usr/share/man/man8/runc-spec.8.bz2
complete -c runc-spec -l bundle -s b -d 'Set path to the root of the bundle directory'
complete -c runc-spec -l rootless -d 'Generate a configuration for a rootless container'

