# samba
# Autogenerated from man page /usr/share/man/man8/samba.8.bz2
complete -c samba -s D -l daemon -d 'If specified, this parameter causes the server to operate as a daemon'
complete -c samba -s F -l foreground -d 'If specified, this parameter causes the samba process to not daemonize, i. e'
complete -c samba -s i -l interactive -d 'If this parameter is specified it causes the server to run "interactively", n…'
complete -c samba -s M -l model -d 'This parameter can be used to specify the "process model" samba should use'
complete -c samba -l maximum-runtime -d 'Set maximum runtime of the server process till autotermination in seconds'
complete -c samba -s b -l show-build -d 'Print information about how Samba was built'
complete -c samba -s d -l debuglevel -l debug-stdout -d 'level is an integer from 0 to 10'
complete -c samba -l configfile -d 'The file specified contains the configuration details required by the server'
complete -c samba -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c samba -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c samba -l leak-report -d 'Enable talloc leak reporting on exit'
complete -c samba -l leak-report-full -d 'Enable full talloc leak reporting on exit'
complete -c samba -s V -l version -d 'Prints the program version number'
complete -c samba -s '?' -l help -d 'Print a summary of command line options'
complete -c samba -l usage -d 'Display brief usage message'
complete -c samba -s S -d 'parameter had been given'

