# samba_downgrade_db
# Autogenerated from man page /usr/share/man/man8/samba_downgrade_db.8.bz2
complete -c samba_downgrade_db -s H -d 'Link directly to a sam. ldb file instead of using path in system smb. conf'
complete -c samba_downgrade_db -s s -d 'Link directly to smb'

