# sdl2-config
# Autogenerated from man page /usr/share/man/man1/sdl2-config.1.bz2
complete -c sdl2-config -l cflags -d 'Print the compiler flags that are necessary to compile a program or library t…'
complete -c sdl2-config -l exec-prefix -d 'If specified, use  DIR instead of the installation exec prefix that SDL was b…'
complete -c sdl2-config -l libs -d 'Print the linker flags that are necessary to link a program that uses SDL'
complete -c sdl2-config -l static-libs -d 'Print the linker flags that are necessary to statically link a program that u…'
complete -c sdl2-config -l library-libs -d 'Print the linker flags that are necessary to link a library that uses SDL'
complete -c sdl2-config -l plugin-libs -d 'Print the linker flags that are necessary to link an SDL-using object that is…'
complete -c sdl2-config -l prefix -d 'If specified, use PREFIX instead of the installation prefix that SDL was buil…'
complete -c sdl2-config -l version -d 'Prints the currently installed version of SDL on standard output.  EXAMPLES'

