# secret-tool
# Autogenerated from man page /usr/share/man/man1/secret-tool.1.bz2
complete -c secret-tool -l label -d 'argument.  This label will be displayed in the password manager'
complete -c secret-tool -l all
complete -c secret-tool -l unlock

