# sendmail
# Autogenerated from man page /usr/share/man/man1/sendmail.1.bz2
complete -c sendmail -s X -d 'Ignored for compatibility'
complete -c sendmail -o bm -d 'Read mail from standard input (default)'
complete -c sendmail -o bp -d 'List information about mail queue.  This executes  mailq '
complete -c sendmail -o bs -d 'Use the SMTP protocol on standard input and standard output'
complete -c sendmail -s F -d 'Sets the full name of the sender'
complete -c sendmail -s f -d 'Sets the envelope sender address'
complete -c sendmail -s r -d 'An alternate and obsolete form of the -f flag'
complete -c sendmail -s B
complete -c sendmail -s C
complete -c sendmail -s d
complete -c sendmail -s h
complete -c sendmail -s i
complete -c sendmail -s L
complete -c sendmail -s N
complete -c sendmail -s n
complete -c sendmail -s O
complete -c sendmail -s o
complete -c sendmail -s p
complete -c sendmail -s q
complete -c sendmail -s R
complete -c sendmail -s U
complete -c sendmail -s V
complete -c sendmail -s v
complete -c sendmail -s t -d 'Read message for recipients and ignore the command-line arguments'

