# setlock
# Autogenerated from man page /usr/share/man/man8/setlock.8.bz2
complete -c setlock -s n -d 'No delay.  If  fn is locked by another process,  setlock gives up'
complete -c setlock -s N -d '(Default. ) Delay'
complete -c setlock -s x -d 'If  fn cannot be opened (or created) or locked,  setlock exits zero'
complete -c setlock -s X -d '(Default'

