# sfconvert
# Autogenerated from man page /usr/share/man/man1/sfconvert.1.bz2
complete -c sfconvert -l help -s h -d 'Print help message'
complete -c sfconvert -l version -s v -d 'Print version information'

