# sfddiff
# Autogenerated from man page /usr/share/man/man1/sfddiff.1.bz2
complete -c sfddiff -l help -d 'Provide a description with a list of the available options'
complete -c sfddiff -l ignorehints -d 'Suppress the reporting of hint/instruction differences'
complete -c sfddiff -l ignoregpos -d 'Suppress the reporting of kerning (and other \'gpos\') differences'
complete -c sfddiff -l ignoregsub -d 'Suppress the reporting of ligature (and other \'gsub\') differences'
complete -c sfddiff -l ignorenames -d 'Suppress the reporting of name string differences'
complete -c sfddiff -l ignorebitmaps -d 'Suppress the reporting of bitmap differences'
complete -c sfddiff -l exact -d 'Require outlines to match exactly'
complete -c sfddiff -l warn -d 'Warn if the outlines/references are slightly different'
complete -c sfddiff -l merge -d 'Store a merged version of the two fonts into the specified output file'
complete -c sfddiff -l usage -d 'Display the usage description'
complete -c sfddiff -l version -d 'Display the current version.  SEE ALSO fontforge(1)'

