# sfinfo
# Autogenerated from man page /usr/share/man/man1/sfinfo.1.bz2
complete -c sfinfo -l short -s s -d 'Print short single-line summary of each recognized audio file'
complete -c sfinfo -l reporterror -s r -d 'Print an error message if any of the specified files are not recognized as va…'
complete -c sfinfo -l help -s h -d 'Print help message'
complete -c sfinfo -l version -s v -d 'Print version information'

