# smbcontrol
# Autogenerated from man page /usr/share/man/man1/smbcontrol.1.bz2
complete -c smbcontrol -s t -l timeout -d 'Set timeout to seconds'
complete -c smbcontrol -s '?' -l help -d 'Print a summary of command line options'
complete -c smbcontrol -l usage -d 'Display brief usage message'
complete -c smbcontrol -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c smbcontrol -l debug-stdout -d 'This will redirect debug output to STDOUT'
complete -c smbcontrol -l configfile -d 'The file specified contains the configuration details required by the client'
complete -c smbcontrol -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c smbcontrol -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c smbcontrol -l leak-report -d 'Enable talloc leak reporting on exit'
complete -c smbcontrol -l leak-report-full -d 'Enable full talloc leak reporting on exit'
complete -c smbcontrol -s V -l version -d 'Prints the program version number'

