# softlimit
# Autogenerated from man page /usr/share/man/man8/softlimit.8.bz2
complete -c softlimit -s m -d 'Same as  -d  n  -s  n  -l  n  -a R n '
complete -c softlimit -s d -d 'Limit the data segment per process to  n bytes'
complete -c softlimit -s s -d 'Limit the stack segment per process to  n bytes'
complete -c softlimit -s l -d 'Limit the locked physical pages per process to  n bytes'
complete -c softlimit -s a -d 'Limit the total of all segments per process to  n bytes'
complete -c softlimit -s o -d 'Limit the number of open file descriptors per process to R n '
complete -c softlimit -s p -d 'Limit the number of processes per uid to R n '
complete -c softlimit -s f -d 'Limit output file sizes to  n bytes'
complete -c softlimit -s c -d 'Limit core file sizes to  n bytes. P  Efficiency  opts:'
complete -c softlimit -s r -d 'Limit the resident set size to  n bytes'
complete -c softlimit -s t -d 'Limit the CPU time to n seconds'

