# ssl-CA
# Autogenerated from man page /usr/share/man/man1/ssl-CA.pl.1ssl.bz2
complete -c ssl-CA -s h -o help -d 'Prints a usage message'
complete -c ssl-CA -o newcert -d 'Creates a new self signed certificate'
complete -c ssl-CA -o newreq -d 'Creates a new certificate request'
complete -c ssl-CA -o newreq-nodes -d 'Is like -newreq except that the private key will not be encrypted'
complete -c ssl-CA -o newca -d 'Creates a new \\s-1CA\\s0 hierarchy for use with the ca program (or the -signce…'
complete -c ssl-CA -o pkcs12 -d 'Create a PKCS#12 file containing the user certificate, private key and \\s-1CA…'
complete -c ssl-CA -o sign -o signcert -o xsign -d 'Calls the ca program to sign a certificate request'
complete -c ssl-CA -o signCA -d 'This option is the same as the -sign option except it uses the configuration …'
complete -c ssl-CA -o crl -d 'Generate a \\s-1CRL. \\s0 Executes openssl ca command'
complete -c ssl-CA -o revoke -d 'Revoke the certificate contained in the specified certfile'
complete -c ssl-CA -o verify -d 'Verifies certificates against the \\s-1CA\\s0 certificate for \\*(L"demoCA\\*(R"'

