# ssl-rehash
# Autogenerated from man page /usr/share/man/man1/ssl-rehash.1ssl.bz2
complete -c ssl-rehash -o help -s h -d 'Display a brief usage message'
complete -c ssl-rehash -o old -d 'Use old-style hashing (\\s-1MD5,\\s0 as opposed to \\s-1SHA-1\\s0) for generating…'
complete -c ssl-rehash -s n -d 'Do not remove existing links'
complete -c ssl-rehash -o compat -d 'Generate links for both old-style (\\s-1MD5\\s0) and new-style (\\s-1SHA1\\s0) ha…'

