# ssl-list
# Autogenerated from man page /usr/share/man/man1/ssl-list.1ssl.bz2
complete -c ssl-list -o help -d 'Display a usage message'
complete -c ssl-list -s 1 -d 'List the commands, digest-commands, or cipher-commands in a single column'
complete -c ssl-list -o commands -d 'Display a list of standard commands'
complete -c ssl-list -o digest-commands -d 'Display a list of message digest commands, which are typically used as input …'
complete -c ssl-list -o digest-algorithms -d 'Display a list of message digest algorithms'
complete -c ssl-list -o cipher-commands -d 'Display a list of cipher commands, which are typically used as input to the d…'
complete -c ssl-list -o cipher-algorithms -d 'Display a list of cipher algorithms'
complete -c ssl-list -o public-key-algorithms -d 'Display a list of public key algorithms, with each algorithm as a block of mu…'
complete -c ssl-list -o public-key-methods -d 'Display a list of public key method OIDs: this also includes public key metho…'

