# ssl-openssl-version
# Autogenerated from man page /usr/share/man/man1/ssl-openssl-version.1ssl.bz2
complete -c ssl-openssl-version -o help -d 'Print out a usage message'
complete -c ssl-openssl-version -s a -d 'All information, this is the same as setting all the other flags'
complete -c ssl-openssl-version -s v -d 'The current OpenSSL version'
complete -c ssl-openssl-version -s b -d 'The date the current version of OpenSSL was built'
complete -c ssl-openssl-version -s o -d 'Option information: various options set when the library was built'
complete -c ssl-openssl-version -s f -d 'Compilation flags'
complete -c ssl-openssl-version -s p -d 'Platform setting'
complete -c ssl-openssl-version -s d -d '\\s-1OPENSSLDIR\\s0 setting'

