# ssl-pkeyparam
# Autogenerated from man page /usr/share/man/man1/ssl-pkeyparam.1ssl.bz2
complete -c ssl-pkeyparam -o help -d 'Print out a usage message'
complete -c ssl-pkeyparam -o in -d 'This specifies the input filename to read parameters from or standard input i…'
complete -c ssl-pkeyparam -o out -d 'This specifies the output filename to write parameters to or standard output …'
complete -c ssl-pkeyparam -o text -d 'Prints out the parameters in plain text in addition to the encoded version'
complete -c ssl-pkeyparam -o noout -d 'Do not output the encoded version of the parameters'
complete -c ssl-pkeyparam -o engine -d 'Specifying an engine (by its unique id string) will cause pkeyparam to attemp…'

