# ssl-genpkey
# Autogenerated from man page /usr/share/man/man1/ssl-genpkey.1ssl.bz2
complete -c ssl-genpkey -o help -d 'Print out a usage message'
complete -c ssl-genpkey -o out -d 'Output the key to the specified file'
complete -c ssl-genpkey -o outform -d 'This specifies the output format \\s-1DER\\s0 or \\s-1PEM'
complete -c ssl-genpkey -o pass -d 'The output file password source'
complete -c ssl-genpkey -o engine -d 'Specifying an engine (by its unique id string) will cause genpkey to attempt …'
complete -c ssl-genpkey -o algorithm -d 'Public key algorithm to use such as \\s-1RSA, DSA\\s0 or \\s-1DH'
complete -c ssl-genpkey -o pkeyopt -d 'Set the public key algorithm option opt to value'
complete -c ssl-genpkey -o genparam -d 'Generate a set of parameters instead of a private key'
complete -c ssl-genpkey -o paramfile -d 'Some public key algorithms generate a private key based on a set of parameters'

