# st
# Autogenerated from man page /usr/share/man/man1/st.1.bz2
complete -c st -s a -d 'disable alternate screens in terminal'
complete -c st -s c -d 'defines the window class (default $TERM)'
complete -c st -s f -d 'defines the  font to use when st is run'
complete -c st -s g -d 'defines the X11 geometry string'
complete -c st -s i -d 'will fixate the position given with the -g option'
complete -c st -s n -d 'defines the window instance name (default $TERM)'
complete -c st -s o -d 'writes all the I/O to  iofile'
complete -c st -s T -d 'defines the window title (default \'st\')'
complete -c st -s t -d 'defines the window title (default \'st\')'
complete -c st -s w -d 'embeds st within the window identified by  windowid'
complete -c st -s l -d 'use a tty  line instead of a pseudo terminal'
complete -c st -s v -d 'prints version information to stderr, then exits'
complete -c st -s e -d 'st executes command instead of the shell'

