# svc
# Autogenerated from man page /usr/share/man/man8/svc.8.bz2
complete -c svc -s u -d 'Up.  If the  service is not running, start it'
complete -c svc -s d -d Down
complete -c svc -s o -d 'Once.  If the  service is not running, start it'
complete -c svc -s p -d 'Pause.  Send the  service a STOP signal'
complete -c svc -s c -d 'Continue.  Send the  service a CONT signal'
complete -c svc -s h -d 'Hangup.  Send the  service a HUP signal'
complete -c svc -s a -d 'Alarm.  Send the  service an ALRM signal'
complete -c svc -s i -d 'Interrupt.  Send the  service an INT signal'
complete -c svc -s t -d 'Terminate.  Send the  service a TERM signal'
complete -c svc -s k -d 'Kill.  Send the  service a KILL signal'
complete -c svc -s x -d 'Exit.  supervise (8) will exit as soon as the service is down'

