# testasciidoc
# Autogenerated from man page /usr/share/man/man1/testasciidoc.1.bz2
complete -c testasciidoc -s f -l conf-file -d 'Use configuration file CONF_FILE for more information about the configuration…'
complete -c testasciidoc -l force -d 'Update all test data overwriting existing data'

