# testparm
# Autogenerated from man page /usr/share/man/man1/testparm.1.bz2
complete -c testparm -s s -l suppress-prompt -d 'Without this option, testparm will prompt for a carriage return after printin…'
complete -c testparm -s v -l verbose -d 'If this option is specified, testparm will also output all options that were …'
complete -c testparm -l parameter-name -d 'Dumps the named parameter'
complete -c testparm -l section-name -d 'Dumps the named section'
complete -c testparm -l show-all-parameters -d 'Show the parameters, type, possible values'
complete -c testparm -s l -l skip-logic-checks -d 'Skip the global checks'
complete -c testparm -s '?' -l help -d 'Print a summary of command line options'
complete -c testparm -l usage -d 'Display brief usage message'
complete -c testparm -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c testparm -l debug-stdout -d 'This will redirect debug output to STDOUT'
complete -c testparm -l configfile -d 'The file specified contains the configuration details required by the client'
complete -c testparm -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c testparm -s V -l version -d 'Prints the program version number'

