# tickadj
# Autogenerated from man page /usr/share/man/man8/tickadj.8.bz2
complete -c tickadj -s a -d 'Set the kernel variable tickadj to the value'
complete -c tickadj -s A -d 'Set the kernel variable tickadj to an internally computed "optimal" value'
complete -c tickadj -s t -d 'Set the kernel variable tick to the value'
complete -c tickadj -s s -d 'Set the kernel variable dosynctodr to zero, which disables the hardware time-…'
complete -c tickadj -s q -d 'Normally, tickadj is quite verbose about what it is doing.  The'

