# tor-resolve
# Autogenerated from man page /usr/share/man/man1/tor-resolve.1.bz2
complete -c tor-resolve -s v -d 'Display verbose output'
complete -c tor-resolve -s x -d 'Perform a reverse lookup: get the PTR record for an IPv4 address'
complete -c tor-resolve -s 5 -d 'Use the SOCKS5 protocol.  (Default)'
complete -c tor-resolve -s 4 -d 'Use the SOCKS4a protocol rather than the default SOCKS5 protocol'
complete -c tor-resolve -s p -d 'Override the default SOCKS port without setting the hostname'

