# tor
# Autogenerated from man page /usr/share/man/man1/tor.1.bz2
complete -c tor -s h -l help
complete -c tor -s f -l torrc-file
complete -c tor -l allow-missing-torrc
complete -c tor -l defaults-torrc
complete -c tor -l ignore-missing-torrc
complete -c tor -l hash-password
complete -c tor -l list-fingerprint
complete -c tor -l verify-config
complete -c tor -l dump-config
complete -c tor -l service -l options
complete -c tor -l nt-service
complete -c tor -l list-torrc-options
complete -c tor -l list-deprecated-options
complete -c tor -l list-modules
complete -c tor -l version
complete -c tor -l quiet -l hush
complete -c tor -l keygen
complete -c tor -l newpass -d 'option with'
complete -c tor -l DataDirectory -d 'to control where the keys and certificates will be stored, and'
complete -c tor -l SigningKeyLifetime -d 'to control their lifetimes'
complete -c tor -l passphrase-fd
complete -c tor -l key-expiration -l format
complete -c tor -l dbg-

