# tsort
# Autogenerated from man page /usr/share/man/man1/tsort.1.bz2
complete -c tsort -l help -d 'display this help and exit'
complete -c tsort -l version -d 'output version information and exit AUTHOR Written by Mark Kettenis'

