# unixclient
# Autogenerated from man page /usr/share/man/man1/unixclient.1.bz2
complete -c unixclient -s q -d 'Quiet.  Do not print any messages'
complete -c unixclient -s Q -d '(default) Print error messages'
complete -c unixclient -s v -d 'Verbose.   Print error and status messages'
complete -c unixclient -s c -d 'Do not handle more than N simultaneous connections.  (default 10)'

