# unlink
# Autogenerated from man page /usr/share/man/man1/unlink.1.bz2
complete -c unlink -l help -d 'display this help and exit'
complete -c unlink -l version -d 'output version information and exit AUTHOR Written by Michael Stone'

