# vfstest
# Autogenerated from man page /usr/share/man/man1/vfstest.1.bz2
complete -c vfstest -s c -l command -d 'Execute the specified (semicolon-separated) commands'
complete -c vfstest -s '?' -l help -d 'Print a summary of command line options'
complete -c vfstest -l usage -d 'Display brief usage message'
complete -c vfstest -s d -l debuglevel -d 'level is an integer from 0 to 10'
complete -c vfstest -l debug-stdout -d 'This will redirect debug output to STDOUT'
complete -c vfstest -l configfile -d 'The file specified contains the configuration details required by the client'
complete -c vfstest -l option -d 'Set the smb. conf(5) option "<name>" to value "<value>" from the command line'
complete -c vfstest -s l -l log-basename -d 'Base directory name for log/debug files.  The extension "'
complete -c vfstest -l leak-report -d 'Enable talloc leak reporting on exit'
complete -c vfstest -l leak-report-full -d 'Enable full talloc leak reporting on exit'
complete -c vfstest -s V -l version -d 'Prints the program version number'

