# vifm-convert-dircolors
# Autogenerated from man page /usr/share/man/man1/vifm-convert-dircolors.1.bz2
complete -c vifm-convert-dircolors -s h -l help -d 'Displays brief help message'
complete -c vifm-convert-dircolors -s e -l environment -d 'Instructs the script to use $LS_COLORS environment variable instead of data f…'
complete -c vifm-convert-dircolors -s r -l human-readable -d 'Output patterns on separate lines'

