# vifm
# Autogenerated from man page /usr/share/man/man1/vifm.1.bz2
complete -c vifm -l select -d 'Open parent directory of the given path and select specified file in it'
complete -c vifm -s f -d 'Makes vifm instead of opening files write selection to $VIFM/vimfiles and quit'
complete -c vifm -l choose-files -d 'Sets output file to write selection into on exit instead of opening files'
complete -c vifm -l choose-dir -d 'Sets output file to write last visited directory into on exit'
complete -c vifm -l delimiter -d 'Sets separator for list of file paths written out by vifm'
complete -c vifm -l on-choose -d 'Sets command to be executed on selected files instead of opening them'
complete -c vifm -l logging -d 'Log some operational details $VIFM/log'
complete -c vifm -l server-list -d 'List available server names and exit'
complete -c vifm -l server-name -d 'Name of target or this instance (sequential numbers are appended on name conf…'
complete -c vifm -l remote -d 'Sends the rest of the command line to another instance of vifm, --server-name…'
complete -c vifm -l remote-expr -d 'passes expression to vifm server and prints result'
complete -c vifm -s c -d 'Run command-line mode <command> on startup'
complete -c vifm -l help -s h -d 'Show a brief command summary and exit vifm'
complete -c vifm -l version -s v -d 'Show version information and quit'
complete -c vifm -l no-configs -d 'Skip reading vifmrc and vifminfo'
complete -c vifm -l ---
complete -c vifm -l ----
complete -c vifm -l ------------
complete -c vifm -l ------------------
complete -c vifm -l -----------
complete -c vifm -l ----------------

