# vsftpd
# Autogenerated from man page /usr/share/man/man8/vsftpd.8.bz2
complete -c vsftpd -s v -d 'Print the version information and exit, even if other options are encountered'
complete -c vsftpd -o ooption -d 'Set a single option, value pair as per the format in the config file'

