# webapp-config
# Autogenerated from man page /usr/share/man/man8/webapp-config.8.bz2
complete -c webapp-config -l bug-report -l pretend -s p -d 'Provide output to include inside a bug-report'
complete -c webapp-config -s s -l server -d 'Set which web-server to install (-I mode) or upgrade (-U mode) for'
complete -c webapp-config -s u -l user -d 'Set which user will own any installed configuration files'
complete -c webapp-config -s g -l group -d 'Set which group will own any installed configuration files'
complete -c webapp-config -s d -l dir -d 'Specify where to create the virtual copy'
complete -c webapp-config -s h -l host -d 'Specify the fully-qualified domain name of the virtual host'
complete -c webapp-config -s D -l define -d 'Define a configuration variable for webapp-config'
complete -c webapp-config -s E -l envvar -d 'Define an environment variable that will be picked up by webapp-config'
complete -c webapp-config -l envall -d 'Imports all environment variables into the configuration process of webapp-co…'
complete -c webapp-config -s V -l verbose -d 'Use this option to increase the amount of output from the --list-installs swi…'
complete -c webapp-config -o sf -l soft -d 'Use this option to create the virtual copy using symbolic links'
complete -c webapp-config -s c -l copy -d 'Use this option to create the virtual copy by copying the files from the /usr…'
complete -c webapp-config -s S -l secure -d 'Use this option to install into the htdocs-secure directory rather than into …'
complete -c webapp-config -l default-dirs -d and
complete -c webapp-config -l virtual-files -d 'switches allow you to decide what webapp-config will do if (respectively) a d…'
complete -c webapp-config -s I -l install
complete -c webapp-config -s U -l upgrade
complete -c webapp-config -s C -l clean
complete -c webapp-config -o li -l list-installs
complete -c webapp-config -o lui -l list-unused-installs
complete -c webapp-config -o pd -l prune-database
complete -c webapp-config -o si -l show-installed
complete -c webapp-config -o spi -l show-postinst
complete -c webapp-config -o spu -l show-postupgrade
complete -c webapp-config -o ls -l list-servers
complete -c webapp-config -s '?' -l help
complete -c webapp-config -s v -l version
complete -c webapp-config -o dd
complete -c webapp-config -o vf

