# whoami
# Autogenerated from man page /usr/share/man/man1/whoami.1.bz2
complete -c whoami -l help -d 'display this help and exit'
complete -c whoami -l version -d 'output version information and exit AUTHOR Written by Richard Mlynarik'

