# xsubpp-3
# Autogenerated from man page /usr/share/man/man1/xsubpp-3.450.0-perl-5.36.0.1.bz2
complete -c xsubpp-3 -o hiertype -d 'Retains \'::\' in type names so that \\*(C+ hierarchical types can be mapped'
complete -c xsubpp-3 -o except -d 'Adds exception handling stubs to the C code'
complete -c xsubpp-3 -o typemap -d 'Indicates that a user-supplied typemap should take precedence over the defaul…'
complete -c xsubpp-3 -o output -d 'Specifies the name of the output file to generate'
complete -c xsubpp-3 -s v -d 'Prints the xsubpp version number to standard output, then exits'
complete -c xsubpp-3 -o prototypes -d 'By default xsubpp will not automatically generate prototype code for all xsubs'
complete -c xsubpp-3 -o noversioncheck -d 'Disables the run time test that determines if the object file (derived from t…'
complete -c xsubpp-3 -o nolinenumbers -d 'Prevents the inclusion of \'#line\' directives in the output'
complete -c xsubpp-3 -o nooptimize -d 'Disables certain optimizations'
complete -c xsubpp-3 -o noinout -d 'Disable recognition of \\f(CW\\*(C`IN\\*(C\', \\f(CW\\*(C`OUT_LIST\\*(C\' and \\f(CW\\*…'
complete -c xsubpp-3 -o noargtypes -d 'Disable recognition of ANSI-like descriptions of function signature'

