# yasm
# Autogenerated from man page /usr/share/man/man1/yasm.1.bz2
complete -c yasm -s a -l arch -d 'Selects the target architecture'
complete -c yasm -s f -l oformat -d 'Selects the output object format'
complete -c yasm -s g -l dformat -d 'Selects the debugging format for debug information'
complete -c yasm -s L -l lformat -d 'Selects the format/style of the output list file'
complete -c yasm -s l -l list -d 'Specifies the name of the output list file'
complete -c yasm -s m -l machine -d 'Selects the target machine architecture'
complete -c yasm -s o -l objfile -d 'Specifies the name of the output file, overriding any default name generated …'
complete -c yasm -s p -l parser -d 'Selects the parser (the assembler syntax)'
complete -c yasm -s r -l preproc -d 'Selects the preprocessor to use on the input file before passing it to the pa…'
complete -c yasm -s h -l help -d 'Prints a summary of invocation options'
complete -c yasm -l version -d 'This option causes Yasm to prints the version number of Yasm as well as a lic…'
complete -c yasm -s w -d 'This option causes Yasm to inhibit all warning messages'
complete -c yasm -o Werror -d 'This option causes Yasm to treat all warnings as errors'
complete -c yasm -o Wno-unrecognized-char -d 'Causes Yasm to not warn on unrecognized characters found in the input'
complete -c yasm -o Worphan-labels -d 'When using the NASM-compatible parser, causes Yasm to warn about labels found…'
complete -c yasm -s X -d 'Selects a specific output style for error and warning messages'
complete -c yasm -s D -d 'Pre-defines a single-line macro'
complete -c yasm -s e -l preproc-only -d 'Stops assembly after the preprocessing stage; preprocessed output is sent to …'
complete -c yasm -s I -d 'Adds directory path to the search path for include files'
complete -c yasm -s P -d 'Pre-includes file filename, making it look as though filename was prepended t…'
complete -c yasm -s U -d 'Undefines a single-line macro (may be either a built-in macro or one defined …'
complete -c yasm -s W -d 'options have two contrary forms:'
complete -c yasm -o Wname -d and
complete -c yasm -o Wno-name

