# zipmerge
# Autogenerated from man page /usr/share/man/man1/zipmerge.1.bz2
complete -c zipmerge -s D -d 'Ignore directory components in file name comparisons'
complete -c zipmerge -s h -d 'Display a short help message and exit'
complete -c zipmerge -s I -d 'Ignore case in file name comparisons This option is slow for archives with ma…'
complete -c zipmerge -s i -d 'Ask before overwriting files.  See also s'
complete -c zipmerge -s S -d 'Do not overwrite files that have the same size and CRC32 in both the source a…'
complete -c zipmerge -s s -d 'When i is given, do not before overwriting files that have the same size and …'
complete -c zipmerge -s V -d 'Display version information and exit'

