#!/bin/bash
# Download, verify (GPG) and extract the latest stage3 into /mnt/gentoo,
# then install the fstab generated by btrfs.sh.
# Usage: ./stage3.sh [VARIANT]   e.g. openrc (default), systemd, nomultilib-openrc, desktop-openrc
set -euo pipefail

VARIANT=${1:-openrc}
MNT=/mnt/gentoo                        # Mounted by btrfs.sh
FSTAB=/tmp/fstab.gentoo                # Written by btrfs.sh
BASE=https://distfiles.gentoo.org/releases/amd64/autobuilds
KEY=/usr/share/openpgp-keys/gentoo-release.asc   # Only on the Gentoo live ISO; SystemRescue uses WKD
DL=$MNT/.stage3-download               # Download to the new disk, not into the live system's RAM
# Primary key of "Gentoo Linux Release Engineering (Automated Weekly Release Key)".
# The tarball is signed by a SUBKEY of it, so we pin the primary key that GnuPG
# reports as the last field of its VALIDSIG status line.
# Cross-check at https://www.gentoo.org/downloads/signatures/
REL_KEY=13EBBDBEDE7A12775DFDB1BABB572E0E2D182910

# --- Checks ---
[ "$(id -u)" -eq 0 ] || { echo "Run as root. Aborted."; exit 1; }
mountpoint -q "$MNT" || { echo "$MNT is not mounted. Run btrfs.sh first. Aborted."; exit 1; }
[ -e "$MNT/usr" ] && { echo "$MNT already contains a system. Aborted."; exit 1; }
for t in gpg tar xz; do
    command -v "$t" >/dev/null || { echo "Missing tool: $t. Aborted."; exit 1; }
done

# Download helper: wget if available, otherwise curl
if command -v wget >/dev/null; then
    get() { wget -q --show-progress -O "$2" "$1"; }
elif command -v curl >/dev/null; then
    get() { curl -fL --progress-bar -o "$2" "$1"; }
else
    echo "Neither wget nor curl found. Aborted."; exit 1
fi

# timeout: ntpd -q / chronyd -q wait forever when no time server is reachable
if command -v chronyd >/dev/null; then timeout 30 chronyd -q || echo "WARNING: time sync failed"
elif command -v ntpd >/dev/null;  then timeout 30 ntpd -q -g || echo "WARNING: time sync failed"
elif command -v timedatectl >/dev/null; then       # SystemRescue / other systemd live systems
    timedatectl set-ntp true || true
    for _ in $(seq 15); do
        [ "$(timedatectl show -p NTPSynchronized --value 2>/dev/null)" = yes ] && break
        sleep 1
    done
fi
echo "Date: $(date)   <- must be correct, otherwise TLS/GPG fail"

# --- Temporary download dir + throwaway GPG keyring, removed on exit ---
# Trap first, so a leftover dir from a killed run is still cleaned up.
export GNUPGHOME=$DL/gnupg
cleanup() {
    gpgconf --kill gpg-agent 2>/dev/null || true
    rm -rf "$DL"
}
trap cleanup EXIT
rm -rf "$DL"                    # leftovers from an interrupted run
mkdir -p "$DL"
mkdir -m 700 "$GNUPGHOME"       # gpg refuses a world-readable home

# --- Get the Gentoo release key BEFORE downloading anything ---
if [ -f "$KEY" ]; then
    gpg --quiet --import "$KEY"                       # Gentoo live ISO
else                                                  # SystemRescue and other non-Gentoo live systems
    echo "No local Gentoo key (not a Gentoo ISO), fetching via WKD from gentoo.org..."
    gpg --quiet --auto-key-locate clear,wkd --locate-keys releng@gentoo.org \
        || { echo "Could not fetch the Gentoo release key. Aborted."; exit 1; }
fi

# verify FILE [SIGFILE] - signature must chain to the pinned release primary key.
# A bare "gpg --verify" exits 0 for ANY key in the keyring, so check VALIDSIG
# instead: its last field is the primary key of whichever subkey signed.
verify() {
    local status=$DL/gpgstatus
    gpg --status-fd 3 --verify "$@" 3>"$status" || {
        echo "SIGNATURE CHECK FAILED for $1. Aborted."; exit 1; }
    grep -q "^\[GNUPG:\] VALIDSIG .* $REL_KEY\$" "$status" || {
        echo "Signature is valid but NOT from the Gentoo release key $REL_KEY."
        echo "Aborted."; exit 1; }
}

# --- Find the latest tarball for this variant (the list itself is signed) ---
get "$BASE/latest-stage3-amd64-$VARIANT.txt" "$DL/latest.txt" \
    || { echo "No stage3 for variant '$VARIANT'. Aborted."; exit 1; }
verify "$DL/latest.txt"
# Parse the SIGNED text only, so a tampered list cannot point us at an old build
gpg --quiet --decrypt "$DL/latest.txt" > "$DL/latest.verified" 2>/dev/null
REL=$(grep -o '^[^ ]*stage3-amd64-[^ ]*\.tar\.xz' "$DL/latest.verified" | head -n1)
[ -n "$REL" ] || { echo "Could not parse latest-stage3 file. Aborted."; exit 1; }
TAR=$DL/${REL##*/}
echo "Stage3: $REL"

# --- Download tarball + signature ---
get "$BASE/$REL"     "$TAR"
get "$BASE/$REL.asc" "$TAR.asc"

# --- Verify the tarball against the same pinned key ---
verify "$TAR.asc" "$TAR"
echo "Signature OK (Gentoo release key $REL_KEY)"

# --- Extract (keep permissions, xattrs and numeric owners) ---
tar xpf "$TAR" --xattrs-include='*.*' --numeric-owner -C "$MNT"

# --- fstab: after tar, because stage3 ships its own etc/fstab ---
if [ -f "$FSTAB" ]; then
    cp "$FSTAB" "$MNT/etc/fstab"
    echo "Installed $FSTAB as $MNT/etc/fstab"
else
    echo "WARNING: $FSTAB not found, write $MNT/etc/fstab yourself."
fi

echo "Stage3 ready in $MNT"
