

#################################
# Backend Settings
#################################
backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;

#################################
# Transparency Settings
#################################
inactive-opacity = 0.90;
active-opacity = 1.00;
frame-opacity = 0.90;

opacity-rule = [
  "90:class_g = 'Xfce4-terminal'",
  "95:class_g = 'Polybar'"
];

#################################
# Fading
#################################
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];

#################################
# Shadow Settings
#################################
shadow = true;
shadow-radius = 12;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.7;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "class_g = 'Conky'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

#################################
# Blur (optional)
#################################
blur-method = "dual_kawase";
blur-strength = 7;
blur-background-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Xfce4-terminal'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

#################################
# Corner settings (optional)
#################################
corner-radius = 12;

#################################
# Misc
#################################
unredir-if-possible = false;
